### ISSUE TITLE
Consider adding a maintenance mode package

### ISSUE THREAD

**Issue by bluesurfer** [cookiecutter/cookiecutter-django#1083]
It would be nice to have a package or something that puts the website in maintenance mode. Some good choices that I found are:

1. https://github.com/fabiocaccamo/django-maintenance-mode (at application level)
2. https://github.com/alsoicode/django-maintenancemode-2 (at database level)

**Comment by Afrowave** [comment]
Very good suggestion @bluesurfer. I like the second one more.

- It is much 'DRYer' with less code.
- It is 'Heroku' friendly. 
- Changing a 'checkbox' is easier in production than having to get onto the terminal as the super user.
- You can hand this off to the client's DevOps team easily.

Of course it is also quite straight forward to add it to your project in the ```requirements``` folder.

**Comment by pydanny** [comment]
Once https://github.com/alsoicode/django-maintenancemode-2 supports Django 1.11, I'll make this happen.

**Comment by bluesurfer** [comment]
@pydanny 

Fresh news: django-maintenancemode-2 now supports Django 1.11 :)

**Comment by webyneter** [comment]
I suggest that this is to be implemented as an optional feature, via `use_maintenancemode` for instance.

**Comment by browniebroke** [comment]
What are the use cases when one need to put the website in maintenance mode? 

The main (only) one I can think of is when I need to perform a database upgrade. While having this flag accessible from the admin is super flexible, it's not super useful in this case: if you need to take your database down, the flag isn't accessible.
