### ISSUE TITLE
Django Rest Framework Theme Integration

### ISSUE THREAD

**Issue by jeffcjohnson** [cookiecutter/cookiecutter-django#1084]
Hi, I'm not sure if this is the best way to announce/discuss this but thought it might be useful for the cookiecutter-django community.  

This [DRF PR](https://github.com/tomchristie/django-rest-framework/pull/4993) was just merged into DRF and has instructions for making a quick website using the DRF base templates and cookiecutter-django's account management templates.

Of course it isn't released yet so in the meantime I just copied the new file to my templates at my_project/templates/rest_framework/base.html.

Best regards

**Comment by pydanny** [comment]
This is good news. At some point, I'll have time to work with @tomchristie on a good integration between DRF and Cookiecutter Django. Perhaps after I finish my current project.

**Comment by browniebroke** [comment]
I've tried to take a look at that old one, but infortunately, DRF browsable API is still on Bootstrap v3, while we're currently outputting a project using v5. I'm not sure what you had in mind with this idea, but this is the code I have with a custom bootstrap compilation, I'm reusing the generated CSS and including it in a custom `rest_framework/api.html` template:

```django
{% extends "rest_framework/base.html" %}
{% load static %}

{% block bootstrap_theme %}
  <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
{% endblock %}
```

And how it looks:

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/861044/145458826-3bf1a473-d875-4e2c-905d-e98a5f555635.png">

The navbar seems a bit broken and the dropdown on the button doesn't open. More subjectively, I also think the original theme looks better.

While this might be fixed pretty soon [when this PR](https://github.com/encode/django-rest-framework/pull/7411) is merged, I'm not confident in providing this in Cookiecutter Django. When Bootstrap 6 comes out, it would potentially be one more blocker for us to upgrade.

Was it the solution you had in mind @jeffcjohnson? Am I missing anything?
