### ISSUE TITLE
Issues deploying to heroku

### ISSUE THREAD

**Issue by vienoogun** [cookiecutter/cookiecutter-django#140]
I am trying to deploy the app to Heroku following the instructions, but when I get to this step:
heroku run python <project_name>/manage.py syncdb --noinput I get an error message "ImportError: No module named storages". Even after manually installing django_storages through pip in heroku, the same error shows up.

**Comment by morenoh149** [comment]
I have something very similar @theskumar my pip freeze is over there. Do we absolutely need to set the aws configs? https://github.com/pydanny/cookiecutter-django/issues/2328
