### ISSUE TITLE
Use pyinotify in local Django docker image

### ISSUE THREAD

**Issue by jayfk** [cookiecutter/cookiecutter-django#1500]
I've noticed high CPU load coming from the Django container during development. Using `pyinotify` seems to fix this issue.

> If you are using Linux and install pyinotify, kernel signals will be used to autoreload the server (rather than polling file modification timestamps each second). This offers better scaling to large projects, reduction in response time to code modification, more robust change detection, and battery usage reduction.

**Comment by saschalalala** [comment]
What does "Using `pyinotify`" exactly mean? Just install it in the Dockerfile?

**Comment by jayfk** [comment]
> What does "Using pyinotify" exactly mean? Just install it in the Dockerfile?

Exactly.

**Comment by webyneter** [comment]
Seems like it's [unmaintained](https://github.com/seb-m/pyinotify).

**Comment by browniebroke** [comment]
> It seems to be [unmaintained](https://github.com/seb-m/pyinotify).

Indeed, no updates since 2015... I don't think we'll be using it, so I'm going to close this.
