### ISSUE TITLE
Add pwned password validation

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter-django#1553]
This is authored by a Django security team member, @ubernostrum: https://github.com/ubernostrum/pwned-passwords-django

**Comment by sfdye** [comment]
I am okay to work on this.

**Comment by jayfk** [comment]
This should be configurable and off by default with a clear documentation of what it does.

**Comment by pydanny** [comment]
Agreed. Perhaps this should not be in cookiecutter.json, but instead as a documented feature?

**Comment by webyneter** [comment]
I think, it's better to have this as a native feature for added security; if none needed, let the user set `use_pwned`: `n` and he/she's good to go without one.

**Comment by browniebroke** [comment]
While I like this idea, I don't want to add yet another option for it, and it's clearly not unanimous to be included by default. The installation is _very_ simple, folks can do it post-generation if they want to.
