### ISSUE TITLE
rcssmin seems to be unmaintained

### ISSUE THREAD

**Issue by webyneter** [cookiecutter/cookiecutter-django#1554]
The last commit was on [Nov 1, 2016](https://github.com/ndparker/rcssmin).

**Comment by kishan3** [comment]
Thanks @webyneter what is the alternative to it?

**Comment by browniebroke** [comment]
Looks like there is [some activity](https://github.com/ndparker/rcssmin/commit/f9ed9a82f23f235e884e39645ccd5de7deb88d4c) on the repo, maybe it's not unmaintained after all... Let's see if a new release comes up soon.

**Comment by browniebroke** [comment]
This is currently a dependency of django-compressor, so we can't really remove it easily at the moment. However, there is [a PR open](url) to make it optional, in which case we could choose to change our config accordingly:

https://github.com/pydanny/cookiecutter-django/blob/adfa02e5c05e1da95218b05fc711249ddef52011/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L252-L258

**Comment by browniebroke** [comment]
Just had a new release: #3429
