### ISSUE TITLE
django-environ bug with default value

### ISSUE THREAD

**Issue by pablobuenaposada** [cookiecutter/cookiecutter-django#2291]
django-environ==0.4.5 package has an annoying bug where you cannot retrieve env variables if you play with the default option, example:

```
(venv) wl18dbf200479e:cookiecutter-django pablobuenaposada$ pip freeze | grep django-environ
django-environ==0.4.5
(venv) wl18dbf200479e:cookiecutter-django pablobuenaposada$ python
Python 3.6.5 (default, Sep 12 2018, 15:53:18)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import environ
>>> env = environ.Env()
>>> env('HOME')
'/Users/pablobuenaposada'
>>> env('HOME', default=False)
False
```

As you can see depending on the default value you could have unexpected results while trying to get you env variables.

You can follow this bug also in the package issue thread here: https://github.com/joke2k/django-environ/issues/192

I would at least pin the django-environ version to 0.4.4 (**doesn't support Django 2**) where this is not happening but also consider replacing this package by using `os.environ.get` directly or think in other solutions since I am not confident that the library gets fixed,

**Comment by AndreMiras** [comment]
I haven't tried yet, but https://github.com/sloria/environs seems fairly maintained and provides a similar interface

**Comment by pablobuenaposada** [comment]
I think this one is also related https://github.com/vchaptsev/cookiecutter-django-vue/issues/45

**Comment by Isaac12x** [comment]
I have faced that issue too in a different codebase.  I know this might be off-topic but check #2195

**Comment by browniebroke** [comment]
Going to close this old one as the issue linked is marked as fixed in django-environ
