### ISSUE TITLE
Elasticsearch: Optional Integration

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#2436]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)
When it comes to UX, users are dying for a search engine in specific apps... who am I kidding. If there are lots of things on a website, especially text-based, then Elasticsearch is the way to go.

Add an optional integration for Elasticsearch. For Docker users, an additional image will be supported for local development. In production, we COULD provide Amazon and Elastic.co Elasticsearch services, but it would need to be decided on. For now, the settings will be included but no docker image will be provided in production.yml.

The reason production.yml will not include this is because Elasticsearch horizontally scales. Additionally, it will hog up a lot of disk space, it's CPU intensive, and network intensive.

## Rationale

[//]: # (Why should this feature be implemented?)

Many high-end websites and applications that aim to shoot big (while also avoiding Postgres Full-Text Search in case of large data) need a search engine.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

Search engine and replacement for those trying to use PostgreSQL's Full Text Search on tables that will become humongous.

**Comment by browniebroke** [comment]
I've used Elasticsearch in the past and while it's a great tool, I'm not sure it's something I want to be added to Cookiecutter Django. Sure, high-end website might need it, but when you need it, you're probably far into the project, so it feels a bit out scope for us. 

Also there are several options for implementing search out there, one might prefer going down the Algolia route, or other engine. This is a bit like the adding React/Vue/Angular/<insert your favourite JS framework here> discussion, this is a bit too subjective, and -as far as I'm concerned- I don't have the expertise to maintain this solution myself.

I would rather encourage people to start with Postgres full text search, which is decent for a lot of people, and maybe add a section in our docs pointing to more advanced external resources if people are not satisfied by it.

**Comment by Andrew-Chen-Wang** [comment]
Yea, in retrospect, it does seem much. I could probably make a cookiecutter similar template. But I don't want to make another fork in case I open another PR. How would it stay updated with this repository?

**Comment by browniebroke** [comment]
As discussed, I'm going to close this, especially since there isn't a lot of interest at the moment.

> I could probably make a cookiecutter similar template. But I don't want to make another fork in case I open another PR. How would it stay updated with this repository?

I see what you mean, and unfortunately I don't have a good answer for this. If the cookiecutter CLI was supporting plugin (see https://github.com/cookiecutter/cookiecutter-django/discussions/3483), you could write one that would modify a generated project to add it.
