### ISSUE TITLE
Consider adding wemake-python-styleguide

### ISSUE THREAD

**Issue by sobolevn** [cookiecutter/cookiecutter-django#2456]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

I propose to add optional support of `wemake-python-styleguide`: https://github.com/wemake-services/wemake-python-styleguide

## Rationale

[//]: # (Why should this feature be implemented?)

`wemake-python-styleguide` is a quite popular alternative for 3 tools at the same time: `flake8`, `pylint`, and `black`. See: https://github.com/wemake-services/wemake-python-styleguide#what-we-are-about

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

`wemake-python-styleguide` is a very strict linter for python. It is based on `flake8` and has lots of checks. Literally 1000s of them. On the other hand it does not have type-related problems `pylint` has. It does not deal with type inference and does throw invalid violations at you.

It can be also included to the project at any time, so existing users might benefit from it also, without any code rewrites. We use `flakehell` tool to allow legacy-first integrations.

There are multiple `cookiecutter` templates that already support this tool (like [`wemake-django-template`](https://github.com/wemake-services/wemake-django-template), so I thought it might be a good idea to add it here.

If you like this idea - I would be happy to help.

**Comment by demestav** [comment]
> `wemake-python-styleguide` is a quite popular alternative for 3 tools at the same time: `flake8`, `pylint`, and `black`. 

@sobolevn I don't think it is an alternative to `black`, is it? It is unfortunate that it is [not compatible](https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/auto-formatters.html#black) with `black`. And from what I read in the documentation, the people involved in the project are not fans of auto formatters (they state their reasons), so it doesn't seem likely that the compatibility issue will be resolved any time soon.

**Comment by browniebroke** [comment]
Thanks for suggesting this but as it was already pointed out, it won't work for us if it's not compatible with black. Lots of interesting packages in there though, I'll keep an eye on it.
