### ISSUE TITLE
add freezegun/freezegun-pytest in stack tests

### ISSUE THREAD

**Issue by scwall** [cookiecutter/cookiecutter-django#2520]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)
The problem of having to mock each time unit sometimes becomes redundant and is not always simple for the user of now auto_now_add etc... freezegun. In order to solve this problem for the time units, I think it should be part of the local test requirements 

pytest freeze gun : https://github.com/ktosiek/pytest-freezegun
freezegun : https://github.com/spulec/freezegun
FreezeGun is a library that allows your Python tests to travel through time by mocking the datetime module.

## Rationale
Once the decorator or context manager have been invoked, all calls to datetime.datetime.now(), datetime.datetime.utcnow(), datetime.date.today(), time.time(), time.localtime(), time.gmtime(), and time.strftime() will return the time that has been frozen.

**Comment by browniebroke** [comment]
Thanks for the suggestion, but let's try to not add any more extra deps if they can be avoided - one could argue that we're already a bit past this point. Each dependency might slow down new Python/Django upgrades and we're already lagging a bit behind.
