### ISSUE TITLE
"Deploy to Heroku" documentation assume that Mailgun is used as email service

### ISSUE THREAD

**Issue by browniebroke** [cookiecutter/cookiecutter-django#2565]
[Someone encountered](https://stackoverflow.com/q/61343329/2261637) an issue by following our doc to deploy on Heroku.

The documentation still assumes that Mailgun is used, but the users might choose another email provider in the setup since #2435 was implemented.

We should update this page in the documentation to explain how to setup the application with the right config variables.

**Comment by Zamy97** [comment]
Hello!

A newbie in open source here but I absolutely love Cookiecutter-Django!

I remember running into this issue a few months but and I was able to get my way around this thing by using different configurations but I'd be interested in taking on this issue. :) 

The question is how would one go about handling this where do they even start? I'd be interested in hearing some guidance if you are able to provide any?

**Comment by browniebroke** [comment]
I don't think we should document in detail each provider in our docs, this seems too difficult to maintain. 

Instead, we should add a disclaimer/comment saying that our docs are for Mailgun, and that one should check what variables to setup for their provider if they picked something else.
