### ISSUE TITLE
allauth sign up doesn't use custom UserCreation form

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#2708]
## What happened?

I wanted to include some custom fields (django-recaptcha) to my UserCreation form. Turns out, the settings for allauth wasn't pointed to UserCreationForm.

## What should've happened instead?

Allauth should be configured to use the custom UserCreationForm.

## Steps to reproduce

1. Generate a new project.
2. Add a random field to the form.
3. Go to signup. It won't show up.
4. Add the setting:

```
ACCOUNT_FORMS = {"signup": "donate_anything.users.forms.UserCreationForm"}
```

Voila the form field is there. I think the creation of a user should be parallel regardless of where it happens (admin or user input). Taking a look at AbstractUser model, which the custom user model uses, the `email` attribute is set with `blank=True`, meaning it's not required. However, the allauth setting for email is set to `mandatory`. I think we should add that setting (and any other necessary configuration) for the custom user creation form.

Was this deliberate? If not, I'll make a PR.

**Comment by mpoli** [comment]
And now that the Custom UserCreationForm is in place and working, the save_user() override in app/users/adapters.py AccountAdapter isn't working. Must be a django-allauth issue. So hard to get this to work.

**Comment by Andrew-Chen-Wang** [comment]
@mpoli this is an open source project I did last year, so some things might be outdated: https://github.com/Donate-Anything/Donate-Anything Hope you find it useful in setting stuff up.

**Comment by browniebroke** [comment]
> Was this deliberate? If not, I'll make a PR.

I think it is deliberate, yes. The module for this form is just called `forms`, but the forms in it are only used in the admin, and I think the intent is to limit their usage to be admin only. The base forms are used in a way that seems to imply that too:

https://github.com/cookiecutter/cookiecutter-django/blob/0d8a91ebfeb08579bac7f200847016558086d6a5/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/forms.py#L13

Another clue in that direction is that the `UserChangeForm` [inherits](https://github.com/django/django/blob/0e656c02fe945389246f0c08f51c6db4a0849bd2/django/contrib/auth/forms.py#L150) `fields = '__all__` from Django's form, which [is discouraged](https://docs.djangoproject.com/en/4.0/topics/forms/modelforms/#selecting-the-fields-to-use) outside the admin:

> It is strongly recommended that you explicitly set all fields that should be edited in the form using the fields attribute. Failure to do so can easily lead to security problems when a form unexpectedly allows a user to set certain fields, especially when new fields are added to a model.

I think that creating a user from the admin vs when signing up are 2 operations which are generally different enough to justify a separate form. In some situation, they may be similar enough to use the same, but it's not something we can assume to be true to incorporate into the template.

I think you raised a valid problem though, which we should look at improving IMO:

1. We should make it clearer that the forms are for admin only: we could rename them or at least add a docstring to explain that.
2. Optional: create a `SignupForm` inheriting `allauth.account.forms.SignupForm` with a docstring explaining what it's for, and that new fields suitable for signup should be added here.

**Comment by Andrew-Chen-Wang** [comment]
Although it inherits from `admin_forms`, the name itself confused me. Renaming it to be AdminUserCreationForms would be helpful. I think adding the second form inheriting from allauth's forms would also be useful as it seems like many people are having to customize their User models.

**Comment by mpoli** [comment]
> 1. We should make it clearer that the forms are for admin only: we could rename them or at least add a docstring to explain that.
> 2. Optional: create a `SignupForm` inheriting `allauth.account.forms.SignupForm` with a docstring explaining what it's for, and that new fields suitable for signup should be added here.

I would go for both, it will make the life of anyone trying to customize sign up, or even to use the powers of the custom user model way easier.

**Comment by Andrew-Chen-Wang** [comment]
@mpoli I won't have time to make a PR; if you'd like to contribute, that'd be great!

**Comment by mpoli** [comment]
> @mpoli I won't have time to make a PR; if you'd like to contribute, that'd be great!

I have some clue on where to start. I will conduct some research on that and try to come up with something useful in a PR.

**Comment by mpoli** [comment]
@Andrew-Chen-Wang I think I got a kick start on the solution. Please check it out in my repo in the [feature/signupform](https://github.com/mpoli/cookiecutter-django/tree/feature/signupform) branch while I try to solve some inexplicable pre-commit failure to fix files in my local install.

**Comment by Andrew-Chen-Wang** [comment]
LGTM. I think you can PR. Two things:
- `{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/forms.py` should have the admin forms be prefixed as "AdminUserSignupForm" or something
- `{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/forms.py` end of file needs a new line I believe.

**Comment by browniebroke** [comment]
Feel free to open a draft PR if you're stuck, might be be easier to help you by commenting.

**Comment by mpoli** [comment]
@browniebroke I think I got the bulk of it working. My issue is with style. It seems that for some weird reason pre-commit/black/isort/flake8 are all green in my local machine when there are obvious style issues that get caught in CI. That's why I am delaying the PR. I will check that tomorrow and hopefully solve the pre-commit issue.

**Comment by Andrew-Chen-Wang** [comment]
@mpoli please open the PR, and we can help review what's wrong! Sometimes it just takes a lot of back and forth.
