### ISSUE TITLE
Inconsistent line length (black vs 120)

### ISSUE THREAD

**Issue by janfabry** [cookiecutter/cookiecutter-django#2720]
## What happened?

Black defines a line length of 88 characters, but other places still configure 120 characters:

 - `setup.cfg`
 - `.pylintrc`

## What should've happened instead?

Consistency: use 88 characters everywhere. Especially because some IDEs will automatically use these values to show guides in the editor.

**Comment by browniebroke** [comment]
Pull request welcome!

**Comment by luzfcb** [comment]
I think we should follow Django and ignore the standard imposed by Black.

We have widescreen display that is widely available and there is no reason to be stuck in 88 characters. The Django standard, (119 characters) is good enough for me.

So the solution to this is:

1 - Create `pyproject.toml` and include the Black custom configuration [1]. 
2 - Migrate flake8 settings to `pyproject.toml` 
3 - Migrate isort settings to `pyproject.toml` 
4 - Update the .editorconfig to follow the `max_line_length`

references:

https://github.com/django/django/blob/master/.editorconfig

https://black.readthedocs.io/en/stable/pyproject_toml.html

https://timothycrosley.github.io/isort/docs/configuration/config_files/

**Comment by luzfcb** [comment]
Flake8 does not seem to have support for reading pyproject.toml yet 
https://gitlab.com/pycqa/flake8/-/issues/428

**Comment by luzfcb** [comment]
The 2 and 3 are optional.

**Comment by janfabry** [comment]
@luzfcb Moving configuration to `pyproject.toml` is interesting, but it seems to have some consequences (based on a quick reading of the linked issues). Maybe you can open a separate issue about it, so we can keep this discussion about the line length?

(I have no preference about the actual line length chosen, I just like consistency)

**Comment by luzfcb** [comment]
@janfabry since 2 and 3 are optional, I think the way to keep consistency is executing 1 and 4 to 7.

**Comment by aitorres** [comment]
Hello! If you still need help wih this, I could follow steps 1 and 4-7

**Comment by denny-sam** [comment]
Are we still considering this? I can create a PR for this if you are open
