### ISSUE TITLE
/etc/host configuration docs needed

### ISSUE THREAD

**Issue by coreygarvey** [cookiecutter/cookiecutter-django#2759]
## What happened?
This is a bug w/ the docs, I think there is a missing section about configuring the `/etc/host` file to allow for local connections through a url like `my-dev-env.local`. I asked the question on [SO](https://stackoverflow.com/questions/63525029/unable-to-connect-to-django-app-in-docker-container-with-nginx) and the response allowed this to work for me.

Am I missing something here or is it necessary to update `etc/host`?

## What should've happened instead?
Details about configuring the `/etc/host` file on the local machine to forward the request.

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Replay file https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
[//]: # (* Logs)

**Comment by coreygarvey** [comment]
@Andrew-Chen-Wang I think we're talking about different things here. My issues are with the documentation and that it does not explain clearly how to run locally with HTTPS. I don't believe it's related to your PR.

1. nginx (`jwilder/nginx-proxy:alpine` specifically) is being defined in the Docker compose file, `local.yml`
2. I'm running `docker-compose -f local.yml`
3. This has nothing to do with the doc service

I'm following the documentation, where it's suggested to use nginx in local development to allow for testing with https ([local.yml docs](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html#local-yml))

I've moved away from Docker at the moment but the problem remains, there should be a reference in [Getting Up and Running Locally with Docker](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html) about updating one's `/etc/host` file to forward the request from `my-dev-env.local` to `127.0.0.1`.

**Comment by Andrew-Chen-Wang** [comment]
Ah I see, sorry. Brain must've been no good when reading this (I think I read documentation and 127.0.0.1 and came up with a wrong conclusion by the time I finished reading).

Try adding your hostname to the ALLOWED_HOSTS setting in your settings.py:

```
ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "my-dev-env.local"]
```

**Comment by browniebroke** [comment]
> This is a bug w/ the docs, I think there is a missing section about configuring the `/etc/host` file to allow for local connections through a url like `my-dev-env.local`.

You're correct, this is missing.

**Comment by arnav13081994** [comment]
By default 127.0.0.1 is mapped to `localhost`. This can be verified by running `$ host 127.0.0.1` or by checking `/etc/hosts` file, so would it not be easier to simply use localhost as the domain name for local dev?

**Comment by MaKaNu** [comment]
I also struggle on this topic. While I kind of know what the `/etc/hosts` is doing, I have added `my-dev-env.local`.

This seems to work correctly for the main page, but for any page with deeper access I am kicked out.

Example https://my-dev-env.local/admin works until I enter my credentials. I am then presented my a 403 Forbidden under https://my-dev-env.local/admin/login/?next=/admin/.

If I instead enter the admin page via localhost:8000/admin everything works as expected.
