### ISSUE TITLE
Upgrade to Bootstrap v5

### ISSUE THREAD

**Issue by 9mido** [cookiecutter/cookiecutter-django#2845]
https://v5.getbootstrap.com/

https://github.com/twbs/bootstrap/projects

Wouldn't be a bad idea to get a head start.

**Comment by areski** [comment]
would love to see that happening too.
There is also a version of https://github.com/django-crispy-forms/crispy-bootstrap5

**Comment by Andrew-Chen-Wang** [comment]
I agree, but we should also wait until it's out of beta.

**Comment by 9mido** [comment]
You can see the progress here.

https://github.com/twbs/bootstrap/projects

v5 looks very close to being stable and out of beta. Might as well work on some drafts and when it comes out, be done instead of waiting last minute.

**Comment by browniebroke** [comment]
You timed your messages well 😄 

https://blog.getbootstrap.com/2021/05/05/bootstrap-5/

**Comment by Andrew-Chen-Wang** [comment]
lmao we're from the future :O Should we also get rid of the IE support (html shim) since bootstrap also dropped it? https://github.com/pydanny/cookiecutter-django/blob/c650acc19bd7aadeaca9ba4fa2a17a13a8ab0e68/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/templates/base.html#L11-L14

**Comment by ayush1810** [comment]
When can we expect this merged to main?

**Comment by Andrew-Chen-Wang** [comment]
@ayush1810 ref #3276 . Maybe test it out and see if it works. Besides that, can't say much else. It's up to @browniebroke's free time.

**Comment by renzyndrome** [comment]
looking forward to this

**Comment by mpoli** [comment]
#3276 works for me. 

Bootstrap 4 UI templates and general availability seems to be decreasing rapidly. Free template sites such as startbootstrap.com have updated all of their templates to 5. Off-the-shelf django templates are also starting to go 5. 

IMHO bootstrap5 is rapidly turning overdue.

**Comment by browniebroke** [comment]
> #3276 works for me.

Thanks for trying it out and providing feedback @mpoli! I'll try to get this in 😄
