### ISSUE TITLE
The container name "/postgres" is already in use by container "*"

### ISSUE THREAD

**Issue by dobleuber** [cookiecutter/cookiecutter-django#2849]
## What happened?
When I tried to create and run a new project with docker-compose I got these errors:
```
ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "...". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for docs  Cannot create container for service docs: Conflict. The container name "/docs" is already in use by container "...". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "...". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```
## What should've happened instead?
Should run the new project without any problem. When I renamed the containers they worked. We could add the project slug name to `container_name`.

## Additional details

I created a new project with docker support, then:
```
docker-compose -f local.yml build
```
Finally:
```
docker-compose -f local.yml up
```
<summary>
Logs:
<details>
<pre>
$ docker-compose -f local.yml up

Creating network "test_api_default" with the default driver
Creating volume "test_api_local_postgres_data" with default driver
Creating volume "test_api_local_postgres_data_backups" with default driver
Creating postgres ... 
Creating docs     ... error

Creating postgres ... error
ontainer to be able to reuse that name.

ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "*". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for docs  Cannot create container for service docs: Conflict. The container name "/docs" is already in use by container "*". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "*". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
</pre>
</details>
</summary>

**Comment by MartinSchmidt123** [comment]
When you remove the container name definition for the docker-compose services, the current folders name is used as prefix for the container name.
By default this is the project slug.
Removing the container names would also allow to pass the `--project-name` option to docker-compose to setup several environments (due to port collisions only one can run at a time though).

My preferred way would be to remove the container_name definitions from the docker-compose files and add the `--project-name={{project_slug}}` option in the documentation.

**Comment by sharmi** [comment]
Hi I develop multiple django projects on my dev machine. 

Adding specific names to the containers creates conflict between multiple django projects. The older method of not specifying any container_name worked quite well.

Is there any specific reason we adopted the 'container_name' param?

Is it possible to go back to not specifying container names atleast in local.yml?

**Comment by browniebroke** [comment]
This was added in #2545 and the PR explains the rationale. However, the problems described in this issue are more important than the problem it's solving, in my opinion. As I said in the original PR, `docker-compose` has commands to achieve the same thing.

All things considered, I agree with the suggestion to remove `container_name` in our compose file.

**Comment by abaart** [comment]
I noticed that it seems that container names are set properly in the `production.yml` file. I solved this error by adding `<project_name>_local_` in front of all `container_name` fields in `local.yml`. Like is done in `production.yml`. 

This would seem to be a reasonable 'fix' in my opinion.

**Comment by abaart** [comment]
On further inspection, this already seems implemented in `local.yml` in master (already a long time ago according to `blame`). 
So why this was not rendered properly in my case is a mystery to me...

**Comment by fhightower** [comment]
> On further inspection, this already seems implemented in `local.yml` in master (already a long time ago according to `blame`).

This is not implemented (as can be seen [here](https://github.com/pydanny/cookiecutter-django/blob/22d9f99500bd4ed87ecd6d9667a0d502a27ecbaa/%7B%7Bcookiecutter.project_slug%7D%7D/local.yml#L33)). I think you are looking at the `image` field rather than the `container_name` field.

**Comment by j0lle** [comment]
thought is was an easy fix but it breaks postgres
