### ISSUE TITLE
Docs fail to build with GeoIP

### ISSUE THREAD

**Issue by klvbdmh** [cookiecutter/cookiecutter-django#3068]
## What happened?

Adding `GEOIP_PATH` to the `base.py` file, as per [instructions in the Django documentation](https://docs.djangoproject.com/en/3.1/ref/contrib/gis/geoip2/), shows a Configuration error in `docs` container. Additionally, checking if `GEOIP_PATH` exists returns `False`.

## What should've happened instead?

I shouldn't return any errors, like in `django` containter.

## Additional details

```
django_1    |  * Detected change in '/app/config/settings/base.py', reloading
django_1    |  * Restarting with stat
django_1    | # print(GEOIP_PATH)
django_1    | /app/geoip
django_1    | # print(GEOIP_PATH.exists())
django_1    | True
docs_1      | | Running Sphinx v3.4.3
docs_1      | | # print(GEOIP_PATH)
docs_1      | | /app/geoip
docs_1      | | # print(GEOIP_PATH.exists())
docs_1      | | False
docs_1      | 
docs_1      | Configuration error:
docs_1      | There is a programmable error in your configuration file:
docs_1      | 
docs_1      | Traceback (most recent call last):
docs_1      |   File "/usr/local/lib/python3.8/site-packages/sphinx/config.py", line 326, in eval_config_file
docs_1      |     execfile_(filename, namespace)
docs_1      |   File "/usr/local/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
docs_1      |     exec(code, _globals)
docs_1      |   File "/docs/conf.py", line 25, in <module>
docs_1      |     django.setup()
docs_1      |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
docs_1      |     apps.populate(settings.INSTALLED_APPS)
docs_1      |   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
docs_1      |     app_config.import_models()
docs_1      |   File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
docs_1      |     self.models_module = import_module(models_module_name)
docs_1      |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
docs_1      |     return _bootstrap._gcd_import(name[level:], package, level)
docs_1      |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
docs_1      |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
docs_1      |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
docs_1      |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
docs_1      |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
docs_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
docs_1      |   File "/usr/local/lib/python3.8/site-packages/iprestrict/models.py", line 17, in <module>
docs_1      |     from .geoip import NO_COUNTRY, get_geoip
docs_1      |   File "/usr/local/lib/python3.8/site-packages/iprestrict/geoip.py", line 67, in <module>
docs_1      |     _geoip = AdaptedGeoIP2()
docs_1      |   File "/usr/local/lib/python3.8/site-packages/iprestrict/geoip.py", line 41, in __init__
docs_1      |     self._geoip = GeoIP2()
docs_1      |   File "/usr/local/lib/python3.8/site-packages/django/contrib/gis/geoip2/base.py", line 114, in __init__
docs_1      |     raise GeoIP2Exception('GeoIP path must be a valid file or directory.')
docs_1      | django.contrib.gis.geoip2.base.GeoIP2Exception: GeoIP path must be a valid file or directory.
```

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): 1.7.2
    * OS: Ubuntu 18.04.5 LTS
    * Python version: 3.8.7
    * Docker versions (if using Docker): 20.10.3

**Comment by browniebroke** [comment]
Looking at the logs, the `GEOIP_PATH` is created in the Django container, but not in the docs container.

The `docs` container is using [a different Dockerfile](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/docs/Dockerfile), so my guess is that you did the setup for the main Django image, but not for that one?

**Comment by klvbdmh** [comment]
I had this line in both `django/Dockerfile` and `docs/Dockerfile`:

```
&& apt-get install -y libmaxminddb0 libmaxminddb-dev mmdb-bin \
```
in the `RUN apt-get update` section.

I also made changes in `/config/settings/base.py`. That's where I put the print statements too. It's clear that the `docs` container reads `base.py`, since it outputs those print statements.

After reading your comment I looked at `docs/conf.py`, but I'm not sure what to do here. I tried adding 

```
os.environ["GEOIP_PATH"] = os.path.abspath("/app/geoip")
```
but the error still persists.

**Comment by browniebroke** [comment]
You also need to download a `GeoLite2....mmdb.gz` file from [the Maxmind website](https://dev.maxmind.com/geoip/geoip2/geolite2/), don't you? How are you doing that? The file should be copied inside the container...

Do you _really_ need this GeoIP to build the docs though? I would recommend writing your code in a way that makes it optional in you settings, and somehow disable it in the docs container.

At this point, this is merely an issue with Cookiecutter Django, it's more of an environment issue between the 2 Docker images...

**Comment by klvbdmh** [comment]
I downloaded the archives and unpacked them in the project directory, like so

```
app/
├─ compose/
├─ config/
├─ geoip/
│  ├─ GeoLite2-City.mmdb
│  ├─ GeoLite2-Country.mmdb
├─ locale/
├─ main_app/
├─ requirements/
├─ staticfiles/
```

The files are in the container, as `django` container can access them without any problems.

I don't expect GeoIP to be used by the docs and that's why I'm puzzled there's an error when building it.

It's not ideal, but I ended up disabling docs altogether, as per #2712

**Comment by mmmcorpsvit** [comment]
> 
> 
> I downloaded the archives and unpacked them in the project directory, like so
> 
> ```
> app/
> ├─ compose/
> ├─ config/
> ├─ geoip/
> │  ├─ GeoLite2-City.mmdb
> │  ├─ GeoLite2-Country.mmdb
> ├─ locale/
> ├─ main_app/
> ├─ requirements/
> ├─ staticfiles/
> ```
> 
> The files are in the container, as `django` container can access them without any problems.
> 
> I don't expect GeoIP to be used by the docs and that's why I'm puzzled there's an error when building it.
> 
> It's not ideal, but I ended up disabling docs altogether, as per #2712

confirm, use same and all fine
