### ISSUE TITLE
Replace Gulp with Webpack

### ISSUE THREAD

**Issue by michael-yin** [cookiecutter/cookiecutter-django#3091]
## Use Webpack as static build tool

Now this project is still using Gulp as frontend build tool, since Webpack is very popoular and the ecosystem is very mature. I think it is better to use Webpack as frontend build tool.

## Rationale

1. `Webpack` is the most popular bundle solution in the frontend community today, it has received 50k stars on Github.
1. It has a great ecosystem, many plugins, loaders. If we search `webpack` on npmjs.com, we can get 20k resulst.
1. If we do not need `React`, `Vue`, we can still use Webpack to help us compile `ES6`, `SCSS` and do many other things (Many people do not know that!)
1. With a proper config, Webpack can save time and let us build modern web application in quick way.

Actually, other community did quicker on this:

1. Laraval has [laravel-mix](https://github.com/JeffreyWay/laravel-mix)
1. Rails has [webpacker](https://github.com/rails/webpacker)

They all simplified the Webpack config job and make developer can quickly write ES6 and SCSS.

## How I solve the problem

I already created a project [python-webpack-boilerplate](https://github.com/AccordBox/python-webpack-boilerplate)

It contains:

1. A `Webpack project template` which has good structure, easy to use and customize. User can use it even they have no idea how to config Webpack.
1. Template tags which can help load Webpack bundle file in the templates, it is smart to `auto load` dependency files.

If some users want to use React or Vue, the `python-webpack-boilerplate` also supports them.

## Features

- **Supports Django and Flask** (will support more framework in the future)
- Automatic multiple entry points
- Automatic code splitting
- Hot Module Replacement (HMR)
- Easy to config and customize
- ES6 Support via [babel](https://babeljs.io/) (v7)
- JavaScript Linting via [eslint-loader](https://github.com/MoOx/eslint-loader)
- SCSS Support via [sass-loader](https://github.com/jtangelder/sass-loader)
- Autoprefixing of browserspecific CSS rules via [postcss](https://postcss.org/) and [autoprefixer](https://github.com/postcss/autoprefixer)
- Style Linting via [stylelint](https://stylelint.io/)

## Benefits

`python-webpack-boilerplate` is to only provide frontend solution, so it can be used with both `Django` and `Flask` projects. 

So Django developers and Flask developers can both contribute and help improve this project and make it better.

## Project link

https://github.com/AccordBox/python-webpack-boilerplate

If some people are interested in this, you can check my post [New Webpack Boilerplate Project for Django & Flask](https://www.accordbox.com/blog/new-webpack-boilerplate-project-django-flask/) to get more about this project.

And I will later create a PR.

**Comment by Afrowave** [comment]
Wow! @michael-yin,

Very good work. I am looking forward to it.

**Comment by demestav** [comment]
Very informative description @michael-yin . If possible, can you clarify the advantages over the current workflow with Gulp?

**Comment by Andrew-Chen-Wang** [comment]
Same. Definitely looking forward to this as well. I think adding JS frontend frameworks will increase maintenance by a long shot here since something like React and Vue are updated often and work differently.

I think web pack is not only becoming more popular and its performance is better but also it combines certain functionalities together like a combo of Gulp and Grunt.

**Comment by michael-yin** [comment]
@Afrowave @demestav @Andrew-Chen-Wang 

I already pushed PR, could you please check and give me feedback if you have?

Thx.
