### ISSUE TITLE
Move template and static to root

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3093]
## Description

Move the template directory and the static directory to the root level

## Rationale

It's mostly a uvicorn reloading issue. I haven't tested this yet, but the current configuration always reloads if HTML / static files are edited, but on Django they do not reload. Will look a little more into this.

**Comment by Andrew-Chen-Wang** [comment]
Although it may not be needed if Django can pull off an async dev server in Django 3.3...

**Comment by browniebroke** [comment]
I think we close this one now. Feel free to reopen if I missed anything
