### ISSUE TITLE
Redis on Pythonanywhere

### ISSUE THREAD

**Issue by razaltcom** [cookiecutter/cookiecutter-django#3124]
## What happened?

I created a new cookiecutter-django project directly on the Pythonanywhere ssh shell. Pythonanywhere does not support Redis currently, even though they say they are planning it. cookiecutter-django did not ask me whether I want to use Redis. But there is a Redis related config in the settings/production.py that breaks the "python manage.py" command.

I am following the related [pythonanywhere deployment documentation](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-pythonanywhere.html). When I issue 

`python manage.py migrate`

I get the error

```
  ...
  File "/home/examaddin/cookiecutterdjango/mysite/config/settings/production.py", line 62, in <module>
    "LOCATION": env("REDIS_URL"),
  File "/home/examaddin/.virtualenvs/cookiecutterdjango/lib/python3.8/site-packages/environ/environ.py", line 123, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/home/examaddin/.virtualenvs/cookiecutterdjango/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the REDIS_URL environment variable
```

This error indicates that I need to set REDIS_URL here in the settings file:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Mimicing memcache behavior.
            # https://github.com/jazzband/django-redis#memcached-exceptions-behavior
            "IGNORE_EXCEPTIONS": True,
        },
    }
}
```

Pythonanywhere does not have Redis support, so the settings file is buggy in this case. 

I am just starting my site so I do not think I need caching. So I just commented out this caching part for the time being. I hope that it works. Later if I have a busy enough site I can work on replacing this.

## What should've happened instead?

Some solutions that come to mind:
* cookiecutter-django can make using Redis a selection.
* This behaviour is not mentioned in "deploying to pythonanywhere" documentation section. This and its solution can be mentioned there.

**Comment by browniebroke** [comment]
It seems be [a long requested feature](https://www.pythonanywhere.com/forums/topic/1666/) indeed... Would be nice to add a paragraph about Redis in the PythonAnywhere page of our documentation. Might need to update the environment veriables which should be set as well.

I see several options here:

- Disable the cache entirely
- Use [a different cache](https://docs.djangoproject.com/en/3.1/topics/cache/) than Redis 
- If wanting to stick with Redis, signup to a separate service offering hosted Redis (Redislab, AWS, Google, ...)

I've never used Pythonanywhere so I don't know of the limitations of the 2 last options, in terms of filesystem/memory usage quota or colocation to hosted Redis server.

**Comment by razaltcom** [comment]
I read in stackoverflow that Pythonanywhere person Giles recommend your 3. option if you really need redis.

**Comment by 2firstnames** [comment]
Hi there @browniebroke, is there anyone who is able to update the documentation [here ](https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-pythonanywhere.html) ? It is good for the most  - thanks to your comment above I was able to get past the same error that I was getting as @razaltcom 

I updated in my WSGI.py the line: os.environ['DJANGO_AWS_STORAGE_BUCKET_NAME'] = '' as explained in the tutorial, but now Botocore is complaining about me setting the environment var to a blank string.

`File "/home/projectname/.virtualenvs/venv/lib/python3.9/site-packages/botocore/handlers.py", line 240, in validate_bucket_name
2021-09-18 13:55:01,717:     raise ParamValidationError(report=error_msg)
2021-09-18 13:55:02,672: Error running WSGI application
2021-09-18 13:55:02,679: botocore.exceptions.ParamValidationError: Parameter validation failed:
2021-09-18 13:55:02,679: Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"`


Thanks for your help
