### ISSUE TITLE
README.rst --> README.md

### ISSUE THREAD

**Issue by guettli** [cookiecutter/cookiecutter-django#3200]
## Description

I think Markdown has won. I think it makes no sense to learn re-structured-text any more.

If I were you, I would switch from rst to md.

**Comment by brioapp** [comment]
+1

**Comment by browniebroke** [comment]
Sure, why not. We already have a few other Markdown files in the root of the repo. Are you ok to send a pull request for that? It should be quite easy to do with [Pandoc](https://pandoc.org/).

**Comment by browniebroke** [comment]
See #3489, does it cover what you were suggesting?

**Comment by guettli** [comment]
This looks good. Thank you very much!
