### ISSUE TITLE
Add overview section to beginning of documentation.

### ISSUE THREAD

**Issue by paul-s-johnson** [cookiecutter/cookiecutter-django#3229]
## Description

Add an overview section or description of what cookiecutter-django is at the beginning of the documentation. Write for an audience who just stumbled on the cookiecutter-django documentation website and knows what Django is, but has heard nothing about cookiecutter before.

## Rationale

So people who have never heard of cookiecutter before can quickly get the gist of what it's about and whether it's something that can be helpful to them or not.

**Comment by browniebroke** [comment]
Good idea, I've reworded the intro in #3452. I'm open to suggestion to make it more newcomer friendly.
