### ISSUE TITLE
Django admin site not logging in after production

### ISSUE THREAD

**Issue by Shrawant13** [cookiecutter/cookiecutter-django#3250]
I am deploying my. django app on digital ocean. 

The site works fine, but I am not able to login to my admin page even with superuser credentials
I am being redirected to the django admin login page itself. 

Please help me out

**Comment by mhoonjeon** [comment]
Hey have you upgraded the django version to maybe 3.2.x?
There is a problem with the upgraded django version in admin site  - I remember it being something to do with 'subtitle' being added.

Downgrade django to 3.1.11 and it should work, I hope?

**Comment by browniebroke** [comment]
I'm closing this issue as I'm assuming the original issue was solved. Feel free to reopen with more details if the problem persists.

**Comment by xjlin0** [comment]
Some enabled settings in the production.py, such as `SECURE_SSL_REDIRECT`, `SESSION_COOKIE_SECURE`, `CSRF_COOKIE_SECURE`, etc, will get 302 and forward superusers to admin login even with correct credentials.
