### ISSUE TITLE
Update container_name for docker-compose YAML files

### ISSUE THREAD

**Issue by raiaman15** [cookiecutter/cookiecutter-django#3254]
## Description

It's a suggestion to have the default container_name  (django, postgres, docs)
set to 
container_<image_name>

## Rationale

The names "django", "postgres" and "docs" are not unique if one plans to create two projects and work on them simultaneously until they change one explicitly.

**Comment by pcampos119104** [comment]
Agree, or <project_slug>_django, <project_slug>_postgres, <project_slug>_docs and etc..

**Comment by browniebroke** [comment]
Care enough to send a PR to fix it @pcampos119104?

**Comment by browniebroke** [comment]
Also related: #2849

**Comment by pcampos119104** [comment]
Yes, would be my first time ever. What should I do? Just fork, fix, run tox(and pass) and make a PR?

**Comment by browniebroke** [comment]
First contribution, nice 😄 

You can do everything from your browser. Don't worry too much about tests, they are being run in our CI (more on that later). Here is what I recommend to do:

1. Fork the repo under your own account
2. Create a branch using the branch drop down: 
    <img width="370" alt="image" src="https://user-images.githubusercontent.com/861044/148962735-dce78b38-5209-4e87-897c-920bda183347.png">
3. Press "." which should redirect you to a VSCode in your browser, where you can make the changes you need
4. Commit using the source control panel: 
     <img width="324" alt="image" src="https://user-images.githubusercontent.com/861044/148962952-f7efd841-8919-4a9d-a206-bf51d215fae2.png">
5. Open your fork on github.com again, you should see a notification to create a pull request. If you go to the "Actions" tab on your fork, you can see the results of the tests.

If you want more details, GitHub has [a guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create pull requests, which you might find helpful.

**Comment by luzfcb** [comment]
@browniebroke what do you think of this approach? https://github.com/djangopackages/djangopackages/pull/755/files

**Comment by browniebroke** [comment]
@luzfcb sounds quite similar to the solution we're discussing, no? Is the difference that you're prefixing volume names as well?

**Comment by browniebroke** [comment]
@luzfcb I've added what you suggested to #3528. 

Without it (using the same volume name), I was having [the known authentication error](https://cookiecutter-django.readthedocs.io/en/latest/troubleshooting.html#docker-postgres-authentication-failed) in Postgres. It caused some confution in the past, and this seems like a nicer solution. See old issues:

- #1678
- #1785 
- #1672
