### ISSUE TITLE
Django 3.2

### ISSUE THREAD

**Issue by huydbui** [cookiecutter/cookiecutter-django#3274]
Could someone start a table to track when we can get Django 3.2 please? I have been watching but I haven't seen the question yet.

**Comment by Andrew-Chen-Wang** [comment]
ref #2795 thanks for keeping us updated. If someone wants to post the table again, that'd be great.

I think it's best if we somehow automate this ish because I'm too lazy to go one by one through each package. Especially with each new minor release.

**Comment by browniebroke** [comment]
I haven't tried, but it might be an "easy" upgrade: 3.2 is a LTS release so it has [no deprecations](https://docs.djangoproject.com/en/dev/internals/deprecation/).

So even if a 3rd party Django package doesn't officially declare support for 3.2, as long as they support 3.1, we might be good to go.

**Comment by Andrew-Chen-Wang** [comment]
Hm I wouldn't say so. Plenty of packages like django-celery-beat and django-allauth haven't released fixes for the breaking `DEFAULT_AUTO_FIELD` change. Lots of people accidentally created migrations in their virtual env and then migrated it... in other words, there are still breaking changes.

**Comment by mhoonjeon** [comment]
Our project was based on django-cookie-cutter, and one big problem we had when upgrading to 3.2.x was something to do with the [admin template](https://code.djangoproject.com/ticket/32681).

We tried to debug this issue for 2-3 days, but couldn't. So we reverted back to 3.1.x.

**Comment by mmmcorpsvit** [comment]
i use last version of django, all fine

**Comment by mhoonjeon** [comment]
I removed these lines from TEMPLATES["OPTIONS"] from the settings.py - and it worked fine.

```python	        
"django.template.context_processors.i18n",
"django.template.context_processors.media",
"django.template.context_processors.static",
"django.template.context_processors.tz",
...
"{{ cookiecutter.project_slug }}.utils.context_processors.settings_context",
```

**Comment by stemcc** [comment]
Django Allauth has been updated for better compatability with Django 3.2. Package just needs a new release now. I've tested the package from github master and have no issues. 

https://github.com/pennersr/django-allauth/commit/ea3720f196131bd9e5bde7f726b7d52a004d37d4

**Comment by browniebroke** [comment]
Closing this as we now have an automated issue #3398 that is kept up to date via GitHub actions
