### ISSUE TITLE
.envs/* exclusion in .gitignore may not be respected on Windows

### ISSUE THREAD

**Issue by chapb** [cookiecutter/cookiecutter-django#3292]
## What happened?

After working through "Getting Up and Running Locally With Docker", on a Windows machine, I ran git init, which triggered the addition of .env and .envs/* to .gitignore. 

However, .envs/* was not ignored. Examining .gitignore, the two added lines are terminated with CR, whereas all other lines are terminated CRLF. As such, the ignore was not respected in this instance. 

## What should've happened instead?

 .envs/* should be ignored, preventing production secrets from being exposed in source/version control. If I edit .gitignore manually and add line breaks, the ignore is respected.

## Additional details

* Host system configuration: 
    * Cookiecutter 1.7.3
    * Microsoft Windows 10 Pro, 19042
    * Python3.8.2
    * Docker  20.10.7
  
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  
    ```json
    {
  "cookiecutter": {
    "windows": "y",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "13.2",
    "js_task_runner": "None",
    "cloud_provider": "None",
    "mail_service": "Sendgrid",
    "use_async": "n",
    "use_drf": "n",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "n",
    "use_celery": "n",
    "use_mailhog": "n",
    "use_sentry": "n",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "None",
    "keep_local_envs_in_vcs": "n",
    "debug": "n",
    "_template": "gh:pydanny/cookiecutter-django"
  }
}
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/pydanny/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by chapb** [comment]
This function seems to be responsible for the addition to .gitignore.

https://github.com/pydanny/cookiecutter-django/blob/103cc9f2ffb594796b98b2916ecec043b8b5dd9e/hooks/post_gen_project.py#L130

**Comment by Andrew-Chen-Wang** [comment]
That's interesting. Could it be because of the mode we're in? We're using `os.linesep` which should work just fine...

**Comment by ArtSphere** [comment]
I have run into the same issue, not quite sure if I got it correctly, but in my mind it should actually have: 
".envs/", instead of: ".envs/*" - as according to this from the Git Docu, it would ignore only direct childs of /envs directory otherwise, but have as an example the path ".envs/.production/.postgres" included: 
> The pattern "foo/*", matches "foo/test.json" (a regular file), "foo/bar" (a directory), but it does not match "foo/bar/hello.c" (a regular file), as the asterisk in the pattern does not match "bar/hello.c" which has a slash in it.

It did do the trick for me, to have the ".envs" directory ignored. 
I am having trouble to re-add the .local directory though - this entry appears not to work for me "!/.envs/.local"

**Comment by Andrew-Chen-Wang** [comment]
@ArtSphere maybe try clearing the git cache and re add the new line in the gitignore

**Comment by browniebroke** [comment]
> This function seems to be responsible for the addition to .gitignore.
> 
> https://github.com/pydanny/cookiecutter-django/blob/103cc9f2ffb594796b98b2916ecec043b8b5dd9e/hooks/post_gen_project.py#L130

That's interesting... I'm wondering why we're doing that instead of the Jinja templating we do in the rest of the file. Has anyone tried it? That might fix it

**Comment by browniebroke** [comment]
> That's interesting. Could it be because of the mode we're in? We're using `os.linesep` which should work just fine...

Looks like you're right! From [the docs](https://docs.python.org/3/library/os.html#os.linesep):

> Do not use os.linesep as a line terminator when writing files opened in text mode (the default); use a single '\n' instead, on all platforms.
