### ISSUE TITLE
Move repo to Cookiecutter org

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter-django#3352]
## Description

Move to the [Cookiecutter](https://github.com/cookiecutter) org.

## Rationale

My ability to contribute or lead has been minimal for several years. My last commit was November 18th, 2020, about 11 months ago. 

Pros:

- Moving to the `Cookiecutter` org would empower core maintainers to do things they need to DM me to do
- Core maintainers would have more visibility in their roles
- Might be able to tie in meaningful project sponsorship more easily in an org

Cons:

- I no longer get top billing for a project I no longer maintain 😉 
- Might break some of the infrastructure

Thoughts?

**Comment by auvipy** [comment]
that would be good move forward

**Comment by browniebroke** [comment]
I'm +1 on this. Not being fully admin has sometimes prevented me from setting up/fixing some infrastructure. I suggest to also move the services we use (e.g. RTD, PyUp) to be under an org account, if possible.

About redirects, GitHub creates redirects and keep them for quite a while as far as I know, probably for ever. For instance, Black was moved from `https://github.com/ambv/black` to be the PSF org more than 2 years ago (22nd july 2019) and the redirect is still working. I don't know whether the cookiecutter CLI handles them though.

**Comment by browniebroke** [comment]
I should be free on Thursday evening (London timezone) between 6pm and 10pm UTC or Saturday during the afternoon. 

We can prepare a pull request ahead of time will all the known changes.

**Comment by browniebroke** [comment]
I've prepared #3357 to update all the links I could find.

**Comment by pydanny** [comment]
Apologies @browniebroke, dealing with a family emergency and couldn't get it done over the weekend. I will be attending [DjangoCon USA](https://2021.djangocon.us/) (100% online) this coming Friday and Saturday. Let's do it then - we can even celebrate it with attendees there.
