### ISSUE TITLE
Update to Debian Bullseye

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#3369]
## Description

Since august there is a new release of Debian named bullseye. Therefore I would propose to update our docker images from buster to bullseye. 

## Rationale

Stumbled into this issue when I was using the latest version of weasyprint requiring a newer version of libpango. 

Do some of you have experience with Bullseye being production ready?

**Comment by luzfcb** [comment]
I liked the idea, and a pull request is welcome.
Anyway, a requirements file to `Debian bullseye` also should be created in the [`utility`](https://github.com/pydanny/cookiecutter-django/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/utility) directory
