### ISSUE TITLE
Use django-environ interpolate option to proxy CELERY_BROKER_URL

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#3422]
## Description

What are you proposing? How should it be implemented?

> https://github.com/cookiecutter/cookiecutter-django/blob/57cbf8c2a8cc195bbe160fa0540173df7f36d94f/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/entrypoint#L9

I stumbled upon the `interpolate` option in the [Tips section](https://django-environ.readthedocs.io/en/latest/tips.html#proxy-value) of `django-environ`

Since `CELERY_BROKER_URL` is referring to `REDIS_URL` we can define it as `CELERY_BROKER_URL=$REDIS_URL` when we set `interpolate=True`. 

## Rationale

This gives us the possibility to use an other Redis instance as broker for Celery and makes the entrypoint a little smaler.

**Comment by browniebroke** [comment]
We had a bug a while back where we were hitting the maximum recursion limit when a variable was starting with `$` (https://github.com/cookiecutter/cookiecutter-django/issues/454) which seemed to indicate that it was enabled. Looks like there was some changes in the `django-environ` project to make it optional and disabled by default at some point. 

It seems like it would be useful in that case, but also a bit of a footgun to have enabled globally, it's a shame that this setting is on the while `Env()` object and not on individual settings.

**Comment by foarsitter** [comment]
I remember the recursion error but did not know the origin. Reading [this](https://github.com/joke2k/django-environ/issues/60#issuecomment-336724887) post in the the original `django-environ` issue thread convinced me it is not a good idea at all.
