### ISSUE TITLE
Invalid link to Discord in the README

### ISSUE THREAD

**Issue by mpoli** [cookiecutter/cookiecutter-django#3446]
## What happened?

https://github.com/cookiecutter/cookiecutter-django/commit/5ef345bd3a5c180db29d5c52b60b66d042251488 has updated the link from Slack to Discord in the README.

But the new [Discord link](https://discord.gg/bTfDa6Zz) results in "Invite Invalid".

## What should've happened instead?

The Discord server for Cookiecutter-Django should have been accessed.

## Additional details

No additional details should de necessary beyond clicking on the link. Unfortunately, I don't know the correct Discord link to PR.

**Comment by browniebroke** [comment]
This one works? https://discord.gg/9BrxzPKuEW

**Comment by mpoli** [comment]
Yes, it does.
