### ISSUE TITLE
Provide option for bootstrap 4.6

### ISSUE THREAD

**Issue by eygga** [cookiecutter/cookiecutter-django#3479]
## Description

Allow choosing between bootstrap 4.6 and 5 as a project generation option like what we have for Postgres versions now?

## Rationale

I foresee myself using bootstrap 4.6 for some time to come, I'm not ready to upgrade to bootstrap 5 yet.

**Comment by browniebroke** [comment]
I'm sorry, but no. That's not something we're willing to maintain, we just don't have the bandwidth. 

In the meantime, you can probably stick to [the commit](https://github.com/cookiecutter/cookiecutter-django/commit/41520bcb4d0edb2b8f8853f629717f82aff9b7b3) before the upgrade using the [`--checkout` option](https://cookiecutter.readthedocs.io/en/stable/advanced/cli_options.html#cmdoption-cookiecutter-c) when generating your project:

```
cookiecutter cookiecutter/cookiecutter-django --checkout 41520bcb4d0edb2b8f8853f629717f82aff9b7b3
```
