### ISSUE TITLE
Hiredis issue on Windows.

### ISSUE THREAD

**Issue by AlexanderTCHK** [cookiecutter/cookiecutter-django#3482]
## What happened?
When you install cookiecutter-django via cookiecutter gh:cookiecutter/cookiecutter-django and choose Windows [y] **AND** Docker [Y]it creates requirements/base.txt with dependency of hiredis==2.0.0  # https://github.com/redis/hiredis-py which is NOT available for Windows [proof.](https://pypi.org/project/hiredis/) 

## What should've happened instead?
When you install cookiecutter-django via cookiecutter gh:cookiecutter/cookiecutter-django and choose Windows [y] **AND** Docker [Y]it MUST creates requirements/base.txt with dependency of redis instead?

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.3
    * OS name and version: Microsoft Windows 10 Pro 10.0.19043 N/A Build 19043 

      On Linux, run
      ```bash
      lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
      ```

      On MacOs, run
      ```bash
      sw_vers
      ```

      On Windows, via CMD, run
      ```
      systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      ```

      ```bash
      # Insert here the OS name and version

      ```

    * Python version, run `python3 -V`: Python 3.10.0
    * Docker version (if using Docker), run `docker --version`: Docker version 20.10.11, build dea9396
    * docker-compose version (if using Docker), run `docker-compose --version`: docker-compose version 1.29.2, build 5becea4c
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)
    ```json
    # Insert here the replay file content
    ```
<summary>
Building wheels for collected packages: hiredis
  Building wheel for hiredis (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\user\Desktop\Work\Projects for portfolio\Django Cookiecutter\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-8pj1jxpl\\hiredis_e6a44bd92ede4c7294bfaa00ffe49adb\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-8pj1jxpl\\hiredis_e6a44bd92ede4c7294bfaa00ffe49adb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user\AppData\Local\Temp\pip-wheel-m9x6hfvf'
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-8pj1jxpl\hiredis_e6a44bd92ede4c7294bfaa00ffe49adb\
  Complete output (25 lines):
  C:\Users\user\AppData\Local\Temp\pip-install-8pj1jxpl\hiredis_e6a44bd92ede4c7294bfaa00ffe49adb\setup.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see 
the module's documentation for alternative uses
    import sys, imp, os, glob, io
  C:\Users\user\Desktop\Work\Projects for portfolio\Django Cookiecutter\venv\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please 
use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\hiredis
  copying hiredis\version.py -> build\lib.win-amd64-3.10\hiredis
  copying hiredis\__init__.py -> build\lib.win-amd64-3.10\hiredis
  copying hiredis\hiredis.pyi -> build\lib.win-amd64-3.10\hiredis
  copying hiredis\py.typed -> build\lib.win-amd64-3.10\hiredis
  running build_ext
  building 'hiredis.hiredis' extension
  creating build\temp.win-amd64-3.10
  creating build\temp.win-amd64-3.10\Release
  creating build\temp.win-amd64-3.10\Release\src
  creating build\temp.win-amd64-3.10\Release\vendor
  creating build\temp.win-amd64-3.10\Release\vendor\hiredis
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ivendor -IC:\Users\user\Desktop\Work\Projects for portfolio\Django Cookiecutter\venv\include -IC:\Users\user\AppData\Local\Programs\Python\Python310\include -IC:\Users\user\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcsrc\hiredis.c /Fobuild\temp.win-amd64-3.10\Release\src\hiredis.obj
  hiredis.c
  C:\Users\user\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for hiredis
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by Andrew-Chen-Wang** [comment]
The script and build command shows that you're not using Docker at all. Run `docker-compose -f local.yml up --build`

**Comment by browniebroke** [comment]
@Andrew-Chen-Wang is right. If you choose Docker, you do NOT need to run `pip install -r requirements/local.txt` on the host machine (the Windows one), this command [will be run inside of the Docker container](https://github.com/cookiecutter/cookiecutter-django/blob/acc6b1bf0062d93ce314375a07ca368294df7ced/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L53) when you run `docker-compose -f local.yml build`.

Did you follow [the documentation](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html) on that?
