### ISSUE TITLE
Integrate with `django-improved-user`

### ISSUE THREAD

**Issue by browniebroke** [cookiecutter/cookiecutter-django#3484]
## Description

Integrate with the [`django-improved-user` library](https://github.com/jambonsw/django-improved-user), as suggested by @jambonrose [a while ago](https://github.com/cookiecutter/cookiecutter-django/issues/1268#issuecomment-408985616).

Before going ahead with this, I'd like to gather some feedback to know what people think about such move. Reaction or comment welcome.

## Rationale

Our implementation excludes the fields we don't want by setting them to `None`(#2998), which works, but isn't very nice and can be confusing to newcomers.

Related to:
- #3119 
- #450

**Comment by huydbui** [comment]
**Notes:**
> This package supports up to Django 2.1
> Latest release was on Feb 16th, 2020
> Per jambonrose, he wasn't able to work on any OSS due to having a difficult 2020/2021

**Comment by browniebroke** [comment]
Hum, I missed that part. The latest alpha release supports up to Django 4.0.

**Comment by Andrew-Chen-Wang** [comment]
Are you still allowed to create a username field? Package looks like it's geared towards not having a username field.

**Comment by browniebroke** [comment]
Correct, this package has no username field, which in my opinion is a good thing. Using the email as username is a very common pattern and in this case, one doesn't need a username field. A comment would be enough to explain the rationale, yes. However, I'm hoping that adding this dependency would also avoid other issues/confusions (e.g. #3119).

**Comment by huydbui** [comment]
I don't know how many like me out there, but for projects that I built, I connect them to our company's active directory and it is a must. They only use username. Emails (not always available) are just for notifications. So the options for logging in (via username or email) would always be great.

**Comment by Afrowave** [comment]
@huydbui I completely understand what you are saying when integrating into a company.

For me, I build systems from the scratch and I find the use of the email for registration the easiest way to build for users. I have used the `None` (#2998) pattern and I agree, it's an anti-pattern.  
  
What do you think about using `short_name` for the username?

**Comment by Andrew-Chen-Wang** [comment]
I'm confused then; is the point to avoid a model anti pattern or to login with username or email? If it's to be able to authenticate with either one, django allauth already provides: `ACCOUNT_AUTHENTICATION_METHOD (=”username” | “email” | “username_email”)`

**Comment by browniebroke** [comment]
Given the above feedback, I'm going to close this. Setting some fields to `None` isn't a big annoyance, and the `username` field can easily be controleld via an option. I don't think these things justify bringing another package, and potentailly slowing down our capacity to upgrade to the most recent version of Django.
