### ISSUE TITLE
Port 7000 already in use (afs3-fileserver) Mac only

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3499]
For those who upgraded to MacOS 12.1, your AirPlay receiver may have started on Port 7000 and your docker may fail due to this port already being used. You can disable this port in System Preferences > Sharing > AirPlay receiver. Then you can run docs service in docker.

**Comment by ChuXuan0910** [comment]
Good solution! It works. thank you

**Comment by frersher** [comment]
thank you！thank you！

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke should we change the port...?

**Comment by browniebroke** [comment]
I don't see a reason to stay on 7000, it was probably picked arbitrarily. So yeah, we can change it.

**Comment by RandyMcMillan** [comment]
[Airdisplay Toggle](https://gist.github.com/RandyMcMillan/f0aff97f1840523aee9dac99902bf0ab)

**Comment by sachinsmc** [comment]
This option is moved to **System Settings -> General ->  Airdrop & Handoff -> Airplay receiver** in MacOS 13 Ventura, Previously it was in **Sharing**

**Comment by Aarbel** [comment]
had this problem also, solves it

**Comment by lukaszciastko** [comment]
> Good solution! It works. thank you

It doesn't work for me, because AirPlay stops working. How is that a solution?

**Comment by Andrew-Chen-Wang** [comment]
I recommend changing your program's port from 7000 to 7001 or something rather than disabling

**Comment by tonoman3g** [comment]
> [Airdisplay Toggle](https://gist.github.com/RandyMcMillan/f0aff97f1840523aee9dac99902bf0ab)

thanks!

**Comment by safwansamsudeen** [comment]
Brilliant solution!

**Comment by muskanag2k** [comment]
life saver :)

**Comment by muyiwaolurin** [comment]
Thank youuuu!!!
