### ISSUE TITLE
duplicate key value violates unique constraint "django_site_pkey"

### ISSUE THREAD

**Issue by lionelwust** [cookiecutter/cookiecutter-django#3507]
### Discussed in https://github.com/cookiecutter/cookiecutter-django/discussions/3506

<div type='discussions-op-text'>

<sup>Originally posted by **lionelwust** January  2, 2022</sup>
Hello Guys,

I've been running a django project based on cookie-cutter-django for a while.

Now, I'm trying to run 2 domains with the same project, so same DB and apps, but different urls and allowed_hosts. I am currently setting this up on pythonanywhere and in the meantime, I wanted to already add the second domain as a Site instance, in order to be able to use the Sites framework down the line.

But I got a duplicate key values error when trying to do that. The first Site instance has been created by the original cookie cutter migration. Did you already experience this behaviour and is there an obvious answer to that ?

Thanks a lot in advance !!
Lionel</div>

**Comment by browniebroke** [comment]
Let's discuss in the original discussion, no need to duplicate threads.

**Comment by browniebroke** [comment]
After doing a bit of research on the discussion, I think we should aim to improve the current behaviour, which isn't ideal.

**Comment by browniebroke** [comment]
See #3511 for a potential fix

**Comment by lionelwust** [comment]
@browniebroke thank you very much for your very swift help !
