### ISSUE TITLE
Initial project linter failed

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3517]
## What happened?

Linter on GitHub Actions failed on initial project generation

## What should've happened instead?

Good CI

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):
    * OS name and version:

      On Linux, run
      ```bash
      lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
      ```

      On MacOs, run
      ```bash
      sw_vers
      ```

      On Windows, via CMD, run
      ```
      systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      ```

      ```bash
      # Insert here the OS name and version

      ```

    * Python version, run `python3 -V`:
    * Docker version (if using Docker), run `docker --version`:
    * docker-compose version (if using Docker), run `docker-compose --version`:
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)
    ```json
    {
  "cookiecutter": {
    "project_name": "Blah",
    "project_slug": "Blah",
    "description": "Blah",
    "author_name": "Blah",
    "domain_name": "blah.com",
    "email": "blah@blah.com",
    "version": "0.1.0",
    "open_source_license": "Not open source",
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "y",
    "use_docker": "y",
    "postgresql_version": "14.1",
    "js_task_runner": "None",
    "cloud_provider": "AWS",
    "mail_service": "Mailgun",
    "use_async": "y",
    "use_drf": "y",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "y",
    "use_celery": "y",
    "use_mailhog": "y",
    "use_sentry": "y",
    "use_whitenoise": "n",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
    "_template": "gh:pydanny/cookiecutter-django"
  }
}
    ```
<summary>
Logs:

```
Run actions/setup-python@v2
2
  with:
3
    python-version: 3.9
4
    cache: pip
5
    token: ***
6
  env:
7
    DOCKER_BUILDKIT: 1
8
    COMPOSE_DOCKER_CLI_BUILD: 1
9
Successfully setup CPython (3.9.9)
10
Error: No file in /home/runner/work/demo-backend/demo-backend matched to [**/requirements.txt], make sure you have checked out the target repository
```

<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
Thanks for the report, should be fixed in #3520
