### ISSUE TITLE
High cpu usage on docker and runserver_plus

### ISSUE THREAD

**Issue by thibault** [cookiecutter/cookiecutter-django#3523]
## What happened?

I created a django project with cookiecutter-django. Whenever I start the development environnement with `docker-compose up`, without any other action, my laptop's fans start to scream while my cpu usage skyrockets.

## What should've happened instead?

Not touching any file nor running any additional process besides the normal development server should not eat a huge cpu amount.

## Additional details

I've traced the problem to [a documented issue with the way `runserver_plus` handles the auto-reload](https://django-extensions.readthedocs.io/en/latest/runserver_plus.html#io-calls-and-cpu-usage).

The fix is a simple as installing the `watchdog` package. Maybe it could be added to the requirements?

## System info

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.3
    * OS name and version:
      ```bash
        Distributor ID:	Ubuntu
        Description:	Ubuntu 20.04.3 LTS
        Release:	20.04
        Codename:	focal
      ```
    * Python version, run `python3 -V`: Python 3.8.10
    * Docker version (if using Docker), run `docker --version`: Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
    * docker-compose version (if using Docker), run `docker-compose --version`: docker-compose version 1.22.0, build f46880f

* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
```json
{
"cookiecutter": {
"project_name": "My Awesome Project",
"project_slug": "my_awesome_project",
"description": "Behold My Awesome Project!",
"author_name": "Daniel Roy Greenfeld",
"domain_name": "example.com",
"email": "daniel-roy-greenfeld@example.com",
"version": "0.1.0",
"open_source_license": "MIT",
"timezone": "UTC",
"windows": "n",
"use_pycharm": "n",
"use_docker": "y",
"postgresql_version": "13.2",
"js_task_runner": "Gulp",
"cloud_provider": "AWS",
"mail_service": "SendinBlue",
"use_async": "n",
"use_drf": "n",
"custom_bootstrap_compilation": "n",
"use_compressor": "y",
"use_celery": "y",
"use_mailhog": "n",
"use_sentry": "y",
"use_whitenoise": "y",
"use_heroku": "n",
"ci_tool": "Github",
"keep_local_envs_in_vcs": "y",
"debug": "n",
"_template": "https://github.com/pydanny/cookiecutter-django"
}
```

**Comment by browniebroke** [comment]
Thanks for the detailed report. 

We're already using watchgod:

https://github.com/cookiecutter/cookiecutter-django/blob/b4479359145ac81cf23acd2102c05ff761ab48e8/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/local.txt#L11

which supposingly solves the same problem. 

I think we add watchgod a while ago for [uvicron](https://github.com/encode/uvicorn). I think we were using watchdog at some point, but moved everything to a single package. Would be nice to not install both and use the same approach, but unfortunately, I don't see an easy way to use watchgod with Werkzeug or to use watchdog with uvicorn.

This was already discussed in https://github.com/cookiecutter/cookiecutter-django/pull/3109 but no actions came out of it.

Anyway, looks like it would be a useful addition. Personally, I would prefer to install this package [as extra to Werkzeug](https://github.com/pallets/werkzeug/blob/347291802fcf89bc89660cc9dc62eb1303337bc2/setup.py#L6) to make the dependency clear:

```diff
- Werkzeug==2.0.2 # https://github.com/pallets/werkzeug
+ Werkzeug[watchdog]==2.0.2 # https://github.com/pallets/werkzeug
```

**Comment by thibault** [comment]
Hi @browniebroke,

Thank you for your reply.

Indeed, I saw `watchgod` in the dependencies and tried to install it, but it does not solve the problem. It seems that Werkzeug does not pick on it.

I don't know what would be the best course of action:

 - fill an issue with werkzeug for them to add watchgod compatibility
 - fill an issue with uvicron for them to add watchdog compat
 - fill an issue with watchgod for them to add a watchdog compat api
 - add both in the requirements and be done with it
 - leave everything as is, but maybe add a reference to the problem and the solution somewhere in a documentation page?

Honestly, I don't know any of those packages enough to imagine what would be the best path. Do you have any idea?

**Comment by browniebroke** [comment]
For the first 2 options, we can try to suggest adding the missing integration to Werkzeug and uvicron, but I have no idea if they'll accept them. In their place, I wouldn't want to maintain 2 solutions to the same problem 😄 And unless one of the watchgod/watchdog package has a clear advantage, I don't think they'll want to switch.

For now, I think we can just update our `requirements/local.txt` as I suggested in my previous message, it's a good default and is fully actionable on our end.

**Comment by Andrew-Chen-Wang** [comment]
I'm +1 but be aware of the installation caveats: https://github.com/gorakhargosh/watchdog#installation-caveats

**Comment by thibault** [comment]
@browniebroke I just submitted a PR.

**Comment by browniebroke** [comment]
> I'm +1 but be aware of the installation caveats: [gorakhargosh/watchdog#installation-caveats](https://github.com/gorakhargosh/watchdog#installation-caveats)

I _think_ the Wekzeug [integration with `watchdog`](https://github.com/pallets/werkzeug/blob/af160e0b6b7ddd81c22f1652c728ff5ac72d5c74/src/werkzeug/_reloader.py#L286) is not making use of `watchmedo` script, so these shouldn't affect us, should they?
