### ISSUE TITLE
Celery worker offline on production but works well on local

### ISSUE THREAD

**Issue by hakube** [cookiecutter/cookiecutter-django#3530]
## What happened?
Celery worker is offline and is not executing tasks in production.
![image](https://user-images.githubusercontent.com/38914207/149258062-859f1df9-2002-45fe-b3c2-599b7352a774.png)

## What should've happened instead?
Should work like it did on local
## Additional details

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): 1.7.3
    * OS name and version: 

      ```bash
        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux-logo

      ```

    * Python version`: Python 3.10.1
    * Docker version: Docker version 20.10.12, build e91ed5707e
    * docker-compose version: docker-compose version 1.29.2, build unknown
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
    ```json
      {
        "cookiecutter": {
          "project_name": "dummy",
          "project_slug": "dummy",
          "description": "Behold My Awesome Project!",
          "author_name": "Daniel Roy Greenfeld",
          "domain_name": "example.com",
          "email": "daniel-roy-greenfeld@example.com",
          "version": "0.1.0",
          "open_source_license": "GPLv3",
          "timezone": "UTC",
          "windows": "n",
          "use_pycharm": "n",
          "use_docker": "y",
          "postgresql_version": "14.1",
          "js_task_runner": "None",
          "cloud_provider": "None",
          "mail_service": "Other SMTP",
          "use_async": "y",
          "use_drf": "y",
          "custom_bootstrap_compilation": "n",
          "use_compressor": "y",
          "use_celery": "y",
          "use_mailhog": "n",
          "use_sentry": "n",
          "use_whitenoise": "y",
          "use_heroku": "n",
          "ci_tool": "None",
          "keep_local_envs_in_vcs": "y",
          "debug": "n",
          "_template": "https://github.com/cookiecutter/cookiecutter-django"
        }
    ```

**Comment by Andrew-Chen-Wang** [comment]
do you have any docker logs to show celery failing?

**Comment by hakube** [comment]
Got it solved. I just restarted celery and it worked again. Not sure why I have to do that but in local, it works fine without having to restart it.

Thanks
