### ISSUE TITLE
Swagger UI Integration 

### ISSUE THREAD

**Issue by vik-y** [cookiecutter/cookiecutter-django#3533]
## Description

First of all, amazing template. Absolutely loved it. Would you be looking forward to integrate swagger support in this using https://drf-spectacular.readthedocs.io/en/latest/ ? 

I have already implemented it in a private fork of this project. Would like to contribute  it back if it's something that aligns with the project goals.

## Rationale

API Documentation is a very common requirement. Swagger is a great utility. The schema files generated by swagger can be directly imported into postman as well. Swagger integration in this project will be a huge value add.

**Comment by browniebroke** [comment]
Yes, adding API documentation would be a nice addition. I think we can do it whenever DRF is selected. Hopefully the integration isn't complicated and is not causing a lot of maintenance.

**Comment by vik-y** [comment]
Yes, in my fork I am enabling it only when DRF is enabled. I have been using it for a while now and it's not complicated. I will create a PR for it on the weekend. :)
