### ISSUE TITLE
Add Single Page Application(SPA) container

### ISSUE THREAD

**Issue by elcolie** [cookiecutter/cookiecutter-django#3545]
## Description
What are you proposing?
Django REST scale up the application from web, iOS, Android, IoT

How should it be implemented?
1. Add HTML, CSS, JavsScript app in one container
2. `local.yml` serve file
3. `production.yml` user have to build Dockerfile by themselv
4. `https` has route ready-made support `production.yml` and SPA

## Rationale
Why should this feature be implemented?
It will save up time a  lot with template SPA when working with `local.yml` and `production.yml`

**Comment by browniebroke** [comment]
Thanks for the suggestion, but I consider this out of the scope of this project.
