### ISSUE TITLE
Unable to access question forums

### ISSUE THREAD

**Issue by gamesbook** [cookiecutter/cookiecutter-django#3578]
_First, make sure to examine [the docs](https://cookiecutter-django.readthedocs.io/en/latest/)._
- _Join us on [Discord](https://discord.gg/bTfDa6Zz) and ask around._
- _Start [a discussion](https://github.com/cookiecutter/cookiecutter-django/discussions) on our project's GitHub._

These above links are invalid.  Can someone please supply the right Discord or discussion location?

**Comment by browniebroke** [comment]
The discussion link works for me, but I can confirm that the Discord link is broken.

**Comment by browniebroke** [comment]
Should be fixed now.
