### ISSUE TITLE
compressor.exceptions.UncompressableFileError: 'css/project.css' could not be found in the COMPRESS_ROOT '/app/staticfiles' or with staticfiles.

### ISSUE THREAD

**Issue by hnarayanan** [cookiecutter/cookiecutter-django#3582]
## What happened?

I created a brand new project with the following settings that I think are relevant to this issue:

````
"use_docker": "y",
"js_task_runner": "Gulp",
"custom_bootstrap_compilation": "y",
"use_compressor": "y",
"ci_tool": "Github",
"use_whitenoise": "y",
````

When I pushed this generated project to GitHub, it fails tests with multiple occurrences of the following:

````
compressor.exceptions.UncompressableFileError: 'css/project.css' could not be found in the COMPRESS_ROOT '/app/staticfiles' or with staticfiles.
````

Here is the complete log: [log.txt](https://github.com/cookiecutter/cookiecutter-django/files/8033060/log.txt)

## What should've happened instead?

Upon initial project creation, it should successfully be able to run tests on GitHub Actions.

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI: `Cookiecutter 1.7.3`
    * OS name and version:
   ````
   ProductName:	macOS
   ProductVersion:	12.2
   BuildVersion:	21D49
   ````
    * Python version, run `python3 -V`: Python 3.9.10
    * Docker version (if using Docker), run `docker --version`: Docker version 20.10.12, build e91ed57
    * docker-compose version (if using Docker), run `docker-compose --version`: Docker Compose version v2.2.3
* Options selected:
````
{
  "cookiecutter": {
    "project_name": "Project",
    "project_slug": "Project",
    "description": "Project Description",
    "author_name": "Harish Narayanan",
    "domain_name": "project.io",
    "email": "mail@harishnarayanan.org",
    "version": "0.1.0",
    "open_source_license": "Not open source",
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "14.1",
    "js_task_runner": "Gulp",
    "cloud_provider": "None",
    "mail_service": "SendinBlue",
    "use_async": "y",
    "use_drf": "y",
    "custom_bootstrap_compilation": "y",
    "use_compressor": "y",
    "use_celery": "y",
    "use_mailhog": "y",
    "use_sentry": "y",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
    "_template": "gh:cookiecutter/cookiecutter-django"
  }
}
````

Logs: [log.txt](https://github.com/cookiecutter/cookiecutter-django/files/8033060/log.txt)

**Comment by browniebroke** [comment]
As per #3535, I believe that selecting Gulp + Compressor doesn't make a ton of sense, as they achieve very similar things. At the moment, I believe that this combination isn't well supported. I _think_ you're having this issue because `css/project.css` is generated by Gulp and the CI isn't running it before running the tests...

**Comment by hnarayanan** [comment]
Ah, I see. I scaffolded another project before this without gulp and there, even locally, when attempting to load the site it loaded without static assets.

I will try this again with gulp and without compressor. Thank you!

**Comment by hnarayanan** [comment]
It works with gulp and without compressor!
