### ISSUE TITLE
gitlab-ci error in test stage

### ISSUE THREAD

**Issue by gjae** [cookiecutter/cookiecutter-django#3584]
## What happened?
gitlab-ci job fails in the test stage

```bash
Executing "step_script" stage of the job script
00:02
Using docker image sha256:c3e188a6b38fa7f54cac9963e11b049f7701b8a6354962218b6bbab0fba07bdf for docker/compose:latest with digest docker/compose@sha256:b60a020c0f68047b353a4a747f27f5e5ddb17116b7b018762edfb6f7a6439a82 ...
$ docker-compose -f local.yml build
The Compose file './local.yml' is invalid because:
Unsupported config option for services.celerybeat: 'platform'
Unsupported config option for services.celeryworker: 'platform'
Unsupported config option for services.django: 'platform'
Unsupported config option for services.docs: 'platform'
Unsupported config option for services.flower: 'platform'
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```
## What should've happened instead?
Pass all tests

## Additional details
I'm using docker and i chose gitlab as ci tool when ran the command
```bash  
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
```

**Comment by foarsitter** [comment]
This may be a regressions: https://github.com/cookiecutter/cookiecutter-django/pull/3562

**Comment by gjae** [comment]
> This may be a regression introduced by: #3562

After check the PR, i removed platform options from local.yml and everything ok now!.
Thanks.

**Comment by foarsitter** [comment]
By using `latest` as label you never now wat you get. The output in the gitlab runner gives `docker-compose version 1.26.2, build eefe0d3` for `docker-compose --version`. They stopped updating the `latest` label 2 years ago: https://hub.docker.com/r/docker/compose/tags?page=1&name=latest 

Pin the image to `docker/compose:1.29.2` will solve the underlying problemen. 

Further reading about the latest label: https://vsupalov.com/docker-latest-tag/

**Comment by browniebroke** [comment]
So, we should update this line then? 

https://github.com/cookiecutter/cookiecutter-django/blob/2279841de7d7c435145d270560ec27aa921e97c8/%7B%7Bcookiecutter.project_slug%7D%7D/.gitlab-ci.yml#L25
