### ISSUE TITLE
I keep getting any error on django4.0.

### ISSUE THREAD

**Issue by goophps** [cookiecutter/cookiecutter-django#3598]
I keep getting any error on django4.0. is this version not supported yet?

**Comment by luzfcb** [comment]
@goophps Django 4.0 is not supported yet since not all project dependencies officially support Django 4.0. 

Check the https://github.com/cookiecutter/cookiecutter-django/issues/3458

Note: Note: compatibility is identified based on the [`classifiers`](https://pypi.org/classifiers/) metadata of the package sent to PyPI, that is, the package must state that it supports the Django version as in: https://github.com/django-crispy-forms/django-crispy-forms/blob/c9dfa8ac238ab5bb8a20086652c4ad326866404c/setup.py#L33

**Comment by goophps** [comment]
So you want to wait until all project dependencies support 4.0 before you support it, right?

**Comment by browniebroke** [comment]
Yes, we're stuck until all django deps have been updated to fix any potential issues.

**Comment by goophps** [comment]
Don't wait for others.

**Comment by goophps** [comment]
I see a lot of software already supports 4.0

**Comment by luzfcb** [comment]
For anyone reading this, if you really want cookiecutter-django to support Django 4.0 asap, you can help us:

1 - For each of the projects that do not yet officially support Django 4.0 (Check the compatibility table on https://github.com/cookiecutter/cookiecutter-django/issues/3458), test it for compatibility with Django 4.0, implement everything necessary to support Django 4.0, including updating the metadata, migrations, documentation. Be careful to maintain backward compatibility by following the policy of supported versions of Django by each project.

2 - Wait for the maintainer of each project to publish a new version in PyPI

3 - Update cookiecuter-django's dependencies and implement changes needed to be compatible with Django 4.0 and newer versions of dependencies. cookiecuter-django does not maintain backward compatibility.

4 - Be careful to test all possible combinations available when generating a new cookiecuter-django based project.

**Comment by browniebroke** [comment]
> Don't wait for others.

@goophps please can you try to be considerate and respectful with your tone, this project is maintained by volunteers on their free time 😄 I appreciate that tone is tricky if/when English is not one's first language, so I'm going to assume that this was a honest mistake.

> I see a lot of software already supports 4.0

Unfortunately, "a lot" is not enough, it's an all or nothing scenario. As Fabio suggested, the best thing you can do to help this effort is to look into dependencies where support is lacking.

I'm going to close that now, we already have a dedicated issue.

**Comment by goophps** [comment]
Ok, thank you for your patience. I'm sorry for my bad tone.
