### ISSUE TITLE
The spectacular settings on the REST_FRAMEWORK value is missing 

### ISSUE THREAD

**Issue by smrf1093** [cookiecutter/cookiecutter-django#3600]
## What happened?
The URL 127.0.0.1:8000/api/docs/ is giving the following error :
Incompatible AutoSchema used on View <class 'drf_spectacular.views.SpectacularSwaggerView'>. 

## What should've happened instead?
The following value should be added to the REST_FRAMEWORK settings in base.py:
'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',## Additional details

**Comment by luzfcb** [comment]
Thanks for reporting the issue, however, this issue was already solved yesterday on  https://github.com/cookiecutter/cookiecutter-django/pull/3592/ and already merged on the master branch
