### ISSUE TITLE
Support Mysql8.0

### ISSUE THREAD

**Issue by luojunjiess** [cookiecutter/cookiecutter-django#3608]
## Description

Currently only supports Mysql5.7, expect to support 8.0.Because when using Mysql8 locally, an error will be reported

## Rationale

When using Mysql8.0 locally, executing ` python manage.py migrate`  will report an error, indicating that the version is inconsistent, specifically the file `root_path/contrib/sites/migrations/0003_set_site_domain_and_name.py` 
The specific method is `_update_or_create_site_with_sequence` 

The specific code is
```python
    if created:
        # We provided the ID explicitly when creating the Site entry, therefore the DB
        # sequence to auto-generate them wasn't used and is now out of sync. If we
        # don't do anything, we'll get a unique constraint violation the next time a
        # site is created.
        # To avoid this, we need to manually update DB sequence and make sure it's
        # greater than the maximum value.
        max_id = site_model.objects.order_by('-id').first().id
        with connection.cursor() as cursor:
            cursor.execute("SELECT last_value from django_site_id_seq")
            (current_id,) = cursor.fetchone()
            print(123123, current_id)
            if current_id <= max_id:
                cursor.execute(
                    "alter sequence django_site_id_seq restart with %s",
                    [max_id + 1],
                )

```
If you comment out `if created ` this code will not report an error

**Comment by luzfcb** [comment]
@luojunjiess Thanks for opening the issue, but cookiecutter-django only supports PostgreSQL. 
For the past 7 years, we have never supported MySQL at all, and we do not plan to add support to any SQL database other than PostgreSQL.

Because of that, I will close this issue.

**Comment by luzfcb** [comment]
@luojunjiess There is a fork that's supports MySQL

https://github.com/mabdullahadeel/cookiecutter-django-mysql

**Comment by luojunjiess** [comment]
@luzfcb Ok, thanks, sorry, I thought this was your fork at first, because even the style of the docs is the same; can I ask the reason why Mysql won't be supported?
