### ISSUE TITLE
Link broken at the docs.

### ISSUE THREAD

**Issue by adRn-s** [cookiecutter/cookiecutter-django#3626]
The notes at the end of step 5 in the [developing-locally docs](https://github.com/cookiecutter/cookiecutter-django/tree/master/docs/developing-locally.rst) have a broken link.

I propose we give a hint to the users of this cookiecutter to start using docker early. I found [this guide](https://davejansen.com/how-to-set-up-and-use-postgres-using-docker/) was understandable, and direct to the point.

Likewise, I'd be happy to open a PR with these changes

**Comment by browniebroke** [comment]
Which link is broken? They all work fine for me...

**Comment by adRn-s** [comment]
The note block, at the end of step 5. Now it uses archive.org so it's ok.
