### ISSUE TITLE
Add Python 3.10 support

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3629]
Also it would be great to have a Python 3.10 auto updater in a separate issue.

**Comment by theptrk** [comment]
Can you use python 3.10 with this if Django 3.2 already support python 3.10?

**Comment by foarsitter** [comment]
Tomorrow is the release party of 3.11 so we are slacking behind :upside_down_face:

I'm running 3.10 in production now and I think it is safe to update so will submit a pull request any minute.
