### ISSUE TITLE
[Question] --no-deps flag?

### ISSUE THREAD

**Issue by scheung38** [cookiecutter/cookiecutter-django#3659]
Is the --no-deps flag available 

https://docs.docker.com/compose/reference/up/

    --no-deps                  Don't start linked services.

if so how do we incorporate this into the docker-compose command?

**Comment by browniebroke** [comment]
I don't understand... The answer is in the link you provided:

```
Usage: docker-compose up [options] [--scale SERVICE=NUM...] [SERVICE...]
```

(meaning: you put it in whee `[options]` is)

**Comment by scheung38** [comment]
Thanks @browniebroke normally there is docker-compose --no-deps django, but wasnt sure how to do it within this context
