### ISSUE TITLE
Creating a duplicate user does not fail when inserting dots or plus signs into Gmail addresses

### ISSUE THREAD

**Issue by tronorama** [cookiecutter/cookiecutter-django#3662]
## What happened?

When using the unmodified, default signup form after running cookiecutter, I was able to register and verify the email (using mailhog) for 3 different users using variations of the same Gmail address (as Gmail allows this), e.g., myemail@gmail.com, my.email@gmail.com, myemail+filter@gmail.com

## What should've happened instead?

The signup form should've failed to add a new user, and warned me that a user with that email address already exists

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI: 1.7.3
    * OS name and version: Manjaro Linux 21.25.5 (Qonos)
    * Python version, run `python3 -V`: 3.10.2

**Comment by browniebroke** [comment]
> ## What should've happened instead?
> The signup form should've failed to add a new user, and warned me that a user with that email address already exists

I'm sorry, but no, I strongly disagree. That's not the expected behaviour, and even if it were, it's should not be fixed in this project.

**Comment by tronorama** [comment]
This project seems to be preventing duplicate case-sensitive usernames (vanilla Django isn't doing that), so where should a duplicate email address problem be fixed then?

**Comment by browniebroke** [comment]
Being case sensitive is a whole different thing that reimplementing a proprietary email aliasing logic specific to an email provider. 
It's a lot more complicated, and I don't want to have to support that in the project.
