### ISSUE TITLE
Should we optimize cookiecutter.XYZ == "y"?

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter-django#368]
I think we should move from this pattern:

``` jinja2
{% cookiecutter.XYZ == "y" %}
```

to this pattern:

``` jinja2
{% cookiecutter.XYZ.lower() in ["y", "yes"] %}
```

Thoughts?

**Comment by luzfcb** [comment]
although it is more verbose, it would be a nice addition, since cookiecutter-django is a good example of more complex cookiecutter usage

**Comment by audreyr** [comment]
I believe cookiecutter supports "ye" too:

    {% cookiecutter.XYZ.lower() in ["y", "ye", "yes"] %}

+1 for now, although long term it would be better to have cookiecutter provide a simpler way to check the value of an option.

**Comment by webyneter** [comment]
To my mind, we should refactor sets allowed positive and negative inputs we compare option values against. Summarizing the aforementioned comments, I see it as follows:

```jinja
{% cookiecutter.XYZ in cookiecutter.yes %} # having `is` instead of `in` here would be even better, however, I suppose it's not that easy to implement in jinja (if not impossible)
{% cookiecutter.XYZ in cookiecutter.no %}
```

Moreover, this seems like an ideal API to me:

```jinja
{% cookiecutter.XYZ %}
{% not cookiecutter.XYZ %}
```

Again, no idea if that's even feasible.

*Disclaimer: if I understand things right, that'd be the `cookiecutter`'s rather than `cookiecutter-django`'s realm, and the former I have no experience with*.

**Comment by luzfcb** [comment]
@webyneter I think this should be in `cookiecutter`.

maybe @hackebrot have some thoughts about this

**Comment by hackebrot** [comment]
Hi there! 👋 

Ideally we would move to a [new context format](https://github.com/audreyr/cookiecutter/pull/848) which supports typed Cookiecutter variables.

Doing so would allow us to better separate the UI from the template code, meaning that as a template author I would not have to care about accepted input values for variables, but only about the value that Cookiecutter writes to the context for that particular type.

For instance ``["y", "ye", "yes"]`` might be all valid values for a Boolean variable, but will be stored as ``True`` in the Cookiecutter context resulting in the following template code:

```python
{% if cookiecutter.XYZ %}
Hello {{ cookiecutter.name }}!
{% endif %}
```

I believe one of the reasons for Cookiecutter's popularity and adoption in the Python community is that it uses the Jinja2 template engine and folks don't have to learn yet another template language. So I'd prefer to not introduce any Cookiecutter specific APIs to templates.

**Comment by browniebroke** [comment]
See https://github.com/cookiecutter/cookiecutter/issues/1625

**Comment by browniebroke** [comment]
I suggest we close this issue until it's supported by cookiecutter itself, it's not very actionable at the moment. Thoughts?
