### ISSUE TITLE
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully

### ISSUE THREAD

**Issue by Malayke** [cookiecutter/cookiecutter-django#3681]
## What happened?
```
You should either use Whitenoise or select a Cloud Provider to serve static files
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

## What should've happened instead?
successfully create django project

### Version of cookiecutter CLI
```
$ cookiecutter --version 
Cookiecutter 1.7.3 from /usr/local/lib/python3.7/site-packages (Python 3.7)
```

### OS name and version:  

```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1824
```
### Python version
```
Python 3.7.12
```

### Docker version
```
Docker version 20.10.13, build a224086
```
### docker-compose version
```
Docker Compose version v2.3.3
```

```json
cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json
    
    {
  "cookiecutter": {
    "project_name": "My Awesome Project",
    "project_slug": "my_awesome_project",
    "description": "Behold My Awesome Project!",
    "author_name": "Daniel Roy Greenfeld",
    "domain_name": "example.com",
    "email": "daniel-roy-greenfeld@example.com",
    "version": "0.1.0",
    "open_source_license": "MIT",
    "timezone": "Asia/Singapore",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "13.5",
    "cloud_provider": "None",
    "mail_service": "Other SMTP",
    "use_async": "y",
    "use_drf": "n",
    "frontend_pipeline": "None",
    "use_celery": "y",
    "use_mailhog": "n",
    "use_sentry": "y",
    "use_whitenoise": "n",
    "use_heroku": "n",
    "ci_tool": "Gitlab",
    "keep_local_envs_in_vcs": "y",
    "debug": "y",
    "_template": "https://github.com/cookiecutter/cookiecutter-django"
  }
}
```
<summary>
Logs:
<details>
<pre>
You've downloaded /Users/user/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]: no
Do you want to re-use the existing version? [yes]:
project_name [My Awesome Project]:
project_slug [my_awesome_project]:
description [Behold My Awesome Project!]:
author_name [Daniel Roy Greenfeld]:
domain_name [example.com]:
email [daniel-roy-greenfeld@example.com]:
version [0.1.0]:
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]:
timezone [UTC]: Asia/Singapore
windows [n]:
use_pycharm [n]:
use_docker [n]: y
Select postgresql_version:
1 - 14.1
2 - 13.5
3 - 12.9
4 - 11.14
5 - 10.19
Choose from 1, 2, 3, 4, 5 [1]: 2
Select cloud_provider:
1 - AWS
2 - GCP
3 - None
Choose from 1, 2, 3 [1]: 3
Select mail_service:
1 - Mailgun
2 - Amazon SES
3 - Mailjet
4 - Mandrill
5 - Postmark
6 - Sendgrid
7 - SendinBlue
8 - SparkPost
9 - Other SMTP
Choose from 1, 2, 3, 4, 5, 6, 7, 8, 9 [1]: 9
use_async [n]: y
use_drf [n]:
Select frontend_pipeline:
1 - None
2 - Django Compressor
3 - Gulp
Choose from 1, 2, 3 [1]: 1
use_celery [n]: y
use_mailhog [n]:
use_sentry [n]: y
use_whitenoise [n]: n
use_heroku [n]: n
Select ci_tool:
1 - None
2 - Travis
3 - Gitlab
4 - Github
Choose from 1, 2, 3, 4 [1]: 3
keep_local_envs_in_vcs [y]:
debug [n]: y
You should either use Whitenoise or select a Cloud Provider to serve static files
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
> You should either use Whitenoise or select a Cloud Provider to serve static files

That's it really. We don't support this combinaison otherwise Static files don't work. Please choose whitenoise=y to get a working project.
