### ISSUE TITLE
Wrong option for postgres volume mounts in compose files

### ISSUE THREAD

**Issue by gabrielelucci** [cookiecutter/cookiecutter-django#3685]
Both in the `local.yml` and `production.yml` compose file, the postgres mounts are defined like this

```yml
volumes:
    - production_postgres_data:/var/lib/postgresql/data:Z
    - production_postgres_data_backups:/backups:z
```

However, why is the `z`/`Z` option there? 

docker-compose v2.4.1, even complains about this, reporting the following warning:
```
mount of type `volume` should not define `bind` option
```
That's because the syntax defines a volume mount but the `z`/`Z` option is for bind mounts and that's incompatible. Shouldn't the option be removed?

**Comment by browniebroke** [comment]
FWIW, I've started seeing this warning on macOS too
