### ISSUE TITLE
Running dockers with user privilages inside docker-compose.

### ISSUE THREAD

**Issue by pfk-beta** [cookiecutter/cookiecutter-django#3715]
## What happened?
When I'm running docker-compose with project created with django cookie cutter, i'm getting this warning/security message:
```
You're running the worker with superuser privileges: this is
absolutely not recommended!
```

## What should've happened instead?
I think that all of docker-compose stuff should be run with dedicated user inside it

**Comment by browniebroke** [comment]
I believe that's in local development only, right?

**Comment by xjlin0** [comment]
Are those root in the container or root in the host?

**Comment by browniebroke** [comment]
See also #1410 and #2284

**Comment by pfk-beta** [comment]
Closing, because of duplication of previous issues.
