### ISSUE TITLE
django-silk

### ISSUE THREAD

**Issue by tildebox** [cookiecutter/cookiecutter-django#3753]
Many recommend django-debug-toolbar and the package is included in cookiecutter-django.

The makers of django-debug-toolbar Jazzband also offer the django-silk package. django-silk is also popular.

Why isn't django-silk included in cookiecutter-django?
What speaks against it?

**Comment by luzfcb** [comment]
Adding one more library involves long-term support for the core team. django-silk seems to be simple to integrate so I don't see the need to ship it with cookiecutter-django
