### ISSUE TITLE
Django server doesn't reload after changes in app

### ISSUE THREAD

**Issue by BenjaminArmijo3** [cookiecutter/cookiecutter-django#3770]
## What happened?
Hi i have used a previous version of cookiecutter-django but the last one doest reload the developent server when the files change

* Host system configuration:
    * OS name and version:  Mac M1

**Comment by foarsitter** [comment]
Did you use it before on the Mac M1? Did you find some clues on the web about M1 + Django + reloading? Do you use docker?

**Comment by BenjaminArmijo3** [comment]
the diff is that in the newer version have the line platform, i tried to run with the line commented but the bug persist
  django: &django
    platform: linux/x86_64

**Comment by foarsitter** [comment]
Watchdog is configured through werkzeug in `requirements/local.txt`. Is your previous project using the `stat` reloader?

**Comment by BenjaminArmijo3** [comment]
I change to the older version and it restart with stat.

it seems that the problem is with watchdog

**Comment by foarsitter** [comment]
See [here how werkzeug](https://werkzeug.palletsprojects.com/en/2.1.x/serving/#reloader) decides which reloader is uses and [here how you can override](https://django-extensions.readthedocs.io/en/latest/runserver_plus.html?highlight=stat#configuration) the setting in runserver_plus.

**Comment by camrail** [comment]
Hi all, same issue - I just today switched to apple silicon.  I had a working project on my intel based mac and then after migrating to the new laptop, I spun up the containers and django was no longer seeing changes.

I think this may be talking about the same problem in this [Watchdog issue](https://github.com/gorakhargosh/watchdog/issues/838)

**Comment by BenjaminArmijo3** [comment]
> 

did you fixed it ?

**Comment by camrail** [comment]
> > 
> 
> did you fixed it ?

Not a fix but a workaround is to change runserver_plus reloader to stat rather than Watchman given Watchman isn't working.  Thanks @foarsitter.

@BenjaminArmijo3 you can add the following line to your local.py settings file.
`RUNSERVERPLUS_POLLER_RELOADER_TYPE = 'stat'`

Unfortunately the reload is takes a bit longer to trigger than you may be used to.

**Comment by Eugeny** [comment]
For me, switching the dev container to arm64 by removing `platform: linux/x86_64` from `local.yml` did the trick - apparently that's what prevented inotify from working on a mounted volume

**Comment by browniebroke** [comment]
> switching the dev container to arm64 by removing `platform: linux/x86_64` from `local.yml` did the trick

We just removed that option in #3957. I managed to get my hand on a M1 and test it, can confirm that it was causing the issue. Closing this.
