### ISSUE TITLE
manage.py startapp does not work as expected

### ISSUE THREAD

**Issue by PawelRoman** [cookiecutter/cookiecutter-django#3803]
## What happened?

1. Follow the tutorial in the README
2. Create virtualenv/conda and install all requirements
3. Activate virtualenv and navigate to where manage.py is
4. Run manage.py startapp my_app

Expected: app created in a project folder, and ready to use
Actual: app created in manage.py folder - not possible to use immediately, need to move it manually one level below and edit the name in the apps.py

**Comment by luzfcb** [comment]
@PawelRoman Thank you to open the issue but this is the expected behavior.
Read more in https://github.com/cookiecutter/cookiecutter-django/issues/1725#issuecomment-407493176

Feel free to help us to improve our documentation
