### ISSUE TITLE
Additional deploy guides

### ISSUE THREAD

**Issue by phommata** [cookiecutter/cookiecutter-django#3865]
## Description

Additional deploy guides on Google Compute Engine, gunicorn/uwsgi and Nginx. Add this to the deployment guide.

## Rationale

This should be implemented to help others productionize their project.

**Comment by Andrew-Chen-Wang** [comment]
altho this is for AWS, the concepts are fairly similar:
- EC2 deployment: https://github.com/Andrew-Chen-Wang/cookiecutter-django-ec2-github
- ECS deployment: https://github.com/Andrew-Chen-Wang/cookiecutter-django-ecs-github

**Comment by browniebroke** [comment]
This would be a welcome addition, but personally, I don't really want to maintain such thing: I'm not using GCE personally, so would be hard to review these. Unless someone at Google supports us to do so, I'm not willing to give my free time for that.

If someone wants to write a blog post like the above, I would happily include them in our README. No need to keep an issue around for that, hence closing this.
