### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#3915]
To my big surprise my codebase passed all tests with Python 3.11. With python 3.10 merged a view hours ago I hope we can adopt python 3.11 a little faster so we can benefit the faster cpython effort.

**Comment by jugurtha114** [comment]
i can't wait how fast django will be with the new 3.11 version of python

**Comment by foarsitter** [comment]
Just go ahead and try it! Posting your experiences over here will be valuable.

**Comment by Andrew-Chen-Wang** [comment]
This should be closed.

**Comment by browniebroke** [comment]
Fixed in #4256
