### ISSUE TITLE
WARN[0000] mount of type `volume` should not define `bind` option

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3934]
## What happened?

Launched production docker compose set up

`WARN[0000] mount of type `volume` should not define `bind` option `

## What should've happened instead?

No warning should appear? Not blocking anything from launching and not noticing a problem. Just wanted to record when it was seen

## Additional details

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`):
    * OS name and version:

      
      ```bash
      Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

      ```

    * Python version, run `python3 -V`:
    * Docker version (if using Docker), run `docker --version`: Docker version 20.10.21, build baeda1f

    * docker-compose version (if using Docker), run `docker-compose --version`:
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)
    ```json
    # Insert here the replay file content
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by foarsitter** [comment]
Duplicated of #3685 ?

**Comment by browniebroke** [comment]
Agree. Thanks for trying to capture it. Closing for now.
