### ISSUE TITLE
Issue with okteto deployment Syntax error volumes should be 'local_path:remote_path' or 'remote_path'

### ISSUE THREAD

**Issue by scheung38** [cookiecutter/cookiecutter-django#3944]
## What happened?
a sample Django app should be deployed on okteto cloud when issuing 
okteto deploy --build --wait

## What should've happened instead?
okteto deploy --build --wait
 x  Syntax error volumes should be 'local_path:remote_path' or 'remote_path'

## Additional details
I followed a sample Python Flask deploy and works fine
https://www.okteto.com/docs/samples/python/

But using cookiecutter-django app

and

okteto deploy --build --wait
 x  Syntax error volumes should be 'local_path:remote_path' or 'remote_path'

okteto.yml

```
build:
  django:
    image: sample_cookiecutter_11_july_2022_local_django
    context: .
deploy:
  compose: production.yml

```

* Host system configuration:
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.3 
    * OS name and version: Mac 12.5, Python 3.9.9

      On Linux, run
      ```bash
      lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
      ```

      On MacOs, run
      ```bash
      sw_vers
      ProductName:    macOS
      ProductVersion: 12.5
      BuildVersion:   21G72
      ```

      On Windows, via CMD, run
      ```
      systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      ```

      ```bash
      # Insert here the OS name and version

      ```

    * Python version, run `python3 -V`: 3.9.9
    * Docker version (if using Docker), run `docker --version`: Docker version 20.10.17, build 100c701
    * docker-compose version (if using Docker), run `docker-compose --version`: Docker Compose version v2.7.0
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and MacOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)
    ```json
    # Insert here the replay file content
    ```
<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by foarsitter** [comment]
My guess would be due to the :Z declaration in the volumes. But why do you think this repository is compatible with Okteto and this is a bug?
