### ISSUE TITLE
Small image for k8

### ISSUE THREAD

**Issue by monsad** [cookiecutter/cookiecutter-django#3947]
I want to prepare a small image for k8. Could you please give me advice how to resolve this?

**Comment by foarsitter** [comment]
Can you explain your goal a little bit better? 

K8S run's containers, this template produces a container. So the command for building the production container of this project would be `docker build -f ./compose/production/django/Dockerfile -t cookiecutter-django:0.1.0 .` 

Now it is up to you to orchestrate that container and provide the required services it need.

**Comment by browniebroke** [comment]
What @foarsitter said. not much to add
