### ISSUE TITLE
Add option for replacing username with email in User model

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#3956]
Ref #3484 

I'm not opposed to having an option to create a user model with only the email field and without a username field. I don't think a package (i.e. django-improved-user) requires that. I see myself always needing to alter the admin, user model, user manager, allauth configuration, user forms, the user migration file, drf api, `reverse` code, tests, and views. On the other hand, I also have seen at times that I do need a username field in addition to email (i.e. the code we see today).

Adding django-improved-user would still require changing the majority of the aforementioned code in cookiecutter-django. Propose adding an option in the template for email as username?

**Comment by luzfcb** [comment]
Although I've never used it, django-allauth already has the functionality to use email for authentication. The configuration in theory would look something like this:

```python
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # or 'username_email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
```
https://django-allauth.readthedocs.io/en/latest/configuration.html

![image](https://user-images.githubusercontent.com/807599/203382061-5a7f0fa7-ad60-4ced-bab2-728bc2ac3b34.png)

This configuration, in theory, also implies creating new migrations, which might work for new projects, but maybe some additional manual work on existing projects.

> Note: I just got these settings after reading the documentation, but I haven't run them in practice to see how it behaves in practice

**Comment by Andrew-Chen-Wang** [comment]
The account authentication method is only useful for login. Signing up would still require you to add a username. PR #3958 completely removes the username field. The allauth setting doesn't account for the actually username field itself in the User model.
