### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource through DRF-Spectacular

### ISSUE THREAD

**Issue by lev-slinsen** [cookiecutter/cookiecutter-django#3965]
## What happened?
Making requests through DRF-Spectacular UI returns `TypeError: NetworkError when attempting to fetch resource.` instead of proper response.

## What should've happened instead?
Proper response.

## Additional details
Making a plain request without DRF-Spectacular returns proper response.

**Comment by lev-slinsen** [comment]
Have replaced it with `drf-yasg`, it works fine. It looks like it's either a bug within spectacular itself or the way it's set up in cookiecutter django.

**Comment by browniebroke** [comment]
Is that on local dev or prod?

**Comment by lev-slinsen** [comment]
> 

On local, haven't tested on dev or prod.

**Comment by browniebroke** [comment]
Right, I can reproduce. I think that's a duplicate of #3593. Your error is showing in the UI, but there are more details in the JS console.
