### ISSUE TITLE
Improve the docker docs for newcomers

### ISSUE THREAD

**Issue by Omer-5** [cookiecutter/cookiecutter-django#3971]
I was trying to learn Django and was recommended to setup a project using [cookiecutter with docker](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html), unfortunately  the docs start of with

> The steps below will get you up and running with a local development environment. **All of these commands assume you are in the root of your generated project**.

Since I was new to cookiecutter as well, I had no idea what it meant (at first I thought I needed to clone the repo), I looked at the docs for [Getting Up and Running Locally](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html#getting-up-and-running-locally) which were more detailed and started from scratch.
I followed those steps, however I didn't know at what point I needed to stop which led to a lot of time wasted (more than I would like to admit)

I think that a more detailed docker docs would serve newcomers much better, if thats ok I can draft a PR.

**Comment by browniebroke** [comment]
That's a good point, the steps to generate the projects are missing from the Docker version. I see 2 possible ways of solving that:

a. Move the section on how to generate a project to a dedicated page, with the 2 getting up and running pages (Docker & non-Docke) linking to it. 
b. Make this section a common block (e.g. `generate.rst`) include it with `.. include:: generate.rst` (see mailgun.rst for example)

What do you think?

**Comment by Omer-5** [comment]
I think that option B makes more sense, it doesn't break the flow of the guide.

In the block we can link to [Project Generation Options](https://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html) for users that needs more details.

**Comment by Omer-5** [comment]
I am new to RST and I am facing an issue.

In the page [Getting Up and Running Locally](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html#getting-up-and-running-locally) the instructions are numbered and I can't seem to be able to link to a block because: 
`    .. include:: <block-name>.rst` is interpolated as text and not a command.

I have tried to search online but couldn't find a solution, if you could point me the right direction that would be great.
