### ISSUE TITLE
"docker-compose" is now "docker compose"

### ISSUE THREAD

**Issue by sebastianelsner** [cookiecutter/cookiecutter-django#3980]
## What happened?

docker-compose not a valid command any more in a fresh docker(-compose) install.

## What should've happened instead?
compose is now a plugin to docker. The command changed from docker-compose to docker compose. 

A update of the docs and code is needed.

**Comment by sebastianelsner** [comment]
Two of the three installation types detailed in the docker docs and linked in the cookiecutter-django docs result in the "new" command line (installing via Desktop, scenario one, and installing as a plugin, scenario two / with the hint of pypi being outdated). I would imagine going forward more and more people will have the new command line. So I suggest changing the commands in the docs as more people (like me, being a first time user) just copy/paste regularly from the docs. The question is for me, when is a good time, or is there even one.

**Comment by foarsitter** [comment]
Writing the docs so it serves first-time-users is a good idea. If you have the time to pull it off @sebastianelsner then the right time is there I should say.

**Comment by browniebroke** [comment]
> Compose is indeed a plugin but still available as standalone and even available through pypi (but outdated).

Just a note on that PyPI version: this is compose v1 which used to be written in Python. I think the current version (v2) is written in go. You can see that in their GitHub repo by switching between v2 branch and older v1.x branches.

Even though the standalone version installs v2, it's still `docker-compose`, this is indeed a bit confusing.

Maybe we could update the docs to just use `docker compose` with a note at the beginning saying that it might be with a `-`. I think beginners are more likely to get the version without `-`at this point.

**Comment by foarsitter** [comment]
According to the docs it is indeed rewritten in Go: https://github.com/docker/compose#about-update-and-backward-compatibility

> Maybe we could update the docs to just use docker compose with a note at the beginning saying that it might be with a -. I think beginners are more likely to get the version without -at this point.

This has my preferences

**Comment by infraredCoding** [comment]
@sebastianelsner Hello. I'm quite new to the codebase but I'd love to work on this issue if that's okay

**Comment by browniebroke** [comment]
Yes, it's okay, and there no need to ask for permission to pick up an issue 😄 The only requirement is that there is no pull request already opened for it (which is fine here).

Feel free to fork this repo, make the changes and send us a pull request. There are more details in [our contributing guide](https://github.com/cookiecutter/cookiecutter-django/blob/master/CONTRIBUTING.md).

**Comment by infraredCoding** [comment]
@browniebroke Thanks a lot. I've done a bit of digging around and found that some scripts and test files are also using `docker-compose` .Should I change those as well?

**Comment by browniebroke** [comment]
Probably, yes. Best to be consistent across the board.

**Comment by infraredCoding** [comment]
@browniebroke thanks. I'm on it
