### ISSUE TITLE
incorrect English translation into Spanish

### ISSUE THREAD

**Issue by antocaroca** [cookiecutter/cookiecutter-django#4025]
## What happened?
* incorrect English translation into Spanish

## What should've happened instead?
* The word sign up is translated into Spanish as Regístrarse, but the correct translation is Registrarse (without accent mark).
* There are some p html tags that are not translated into Spanish, but the code is included in {% blocktranslate trimmed %}.

**Comment by browniebroke** [comment]
This project is setup for translations but no translations are included by default. It's up to you to translate it. Perhaps this is coming from a third party django app?

**Comment by luzfcb** [comment]
I guess that it's a problem on django-allauth https://github.com/pennersr/django-allauth/blob/master/allauth/locale/es/LC_MESSAGES/django.po#L530
