### ISSUE TITLE
Rename ROOT_DIR to BASE_DIR

### ISSUE THREAD

**Issue by tildebox** [cookiecutter/cookiecutter-django#4075]
I installed the django-extensions package and noticed that some commands don't work because they access the BASE_DIR setting.

In cookiecutter-django it was renamed to ROOT_DIR. Anyone know why this happened?

What do you think about renaming ROOT_DIR to BASE_DIR, like in Django?

**Comment by browniebroke** [comment]
I didn't know there was a consensus or standard on this setting name. I've seen it use different names on projects I came across.

Do you have more details about which commands don't work?

**Comment by Afrowave** [comment]
In my opnion, I have found that ROOT works well and there is less cognitive effort with the base.py and base.txt, knowing that these are settings and not paths.

**Comment by tildebox** [comment]
> Do you have more details about which commands don't work?

I remember "notes" and "clean_pyc". Maybe there are other commands that don't work.

**Comment by browniebroke** [comment]
Ok I see, `BASE_DIR` is present in the default project template from Django, when running `startproject`, so some packages started to rely on it. It's not listed in the [settings documentation page](https://docs.djangoproject.com/en/4.1/topics/settings/), which I guess makes it pseudo standard...

> I have found that ROOT works well and there is less cognitive effort with the base.py and base.txt, knowing that these are settings and not paths.

That's an interesting point, I never thought of it that way, and it never really bothered me much, but I appreciate that there might be some confusion 🤔 

I'm personally +1 for this change, pull request welcome 👍🏻
