### ISSUE TITLE
Upgrade Traefik docker configurations to the latest Traefik version

### ISSUE THREAD

**Issue by luzfcb** [cookiecutter/cookiecutter-django#4119]
Currently, the Docker-based project is shipping with Traefik 2.2.11. 
The latest version of Traefik is 2.9.6, but 3.0.0 is close to being released.

It would be good for us to update to the latest available version of Traefik.
The files that maybe should be updated are:

https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/traefik/Dockerfile

https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/traefik/traefik.yml

Perhaps to perform the update you only need to update the Traefik version in the Dockerfile, however, it would be good to check if we are using deprecated or no longer recommended API (where are the Traefik Release Notes?), since there were many releases between 2.2.11 and 2.9.6

https://doc.traefik.io/traefik/deprecation/releases/

https://doc.traefik.io/traefik/deprecation/features/

Question: Is there some kind of service like dependabot/pyup but to update versions in Dockerfile/docker-compose.yml? Which are?

**Comment by browniebroke** [comment]
> Question: Is there some kind of service like dependabot/pyup but to update versions in Dockerfile/docker-compose.yml? Which are?

[Dependabot supports Docker](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem). The question is whether dependabot works with Dockerfile that include Jinja tags. It's not really an issue for Traefik, but would be nice it worked across the board...

**Comment by luzfcb** [comment]
Fixed on https://github.com/cookiecutter/cookiecutter-django/pull/4124
