### ISSUE TITLE
Postgres not installing or configuring when using cookiecutter

### ISSUE THREAD

**Issue by jpanknin** [cookiecutter/cookiecutter-django#4155]
I'm new to django and walking through "A Wedge of Django" by Dan and Audrey Roy Greenfeld.  Terminal snippets are below.  According to the instructions in the book, postgres should be installed after entering the commands listed, but I get the following errors:

```
(everycheese) joshpanknin@joshs-mbp-2 everycheese % pg_isready
zsh: command not found: pg_isready
(everycheese) joshpanknin@joshs-mbp-2 everycheese % psql
zsh: command not found: psql
(everycheese) joshpanknin@joshs-mbp-2 everycheese % postgres -V
zsh: command not found: postgres
```

Full walkthrough is:
```
(everycheese) joshpanknin@joshs-mbp-2 wedge_django % cookiecutter gh:feldroy/django-crash-starter
You've downloaded /Users/joshpanknin/.cookiecutters/django-crash-starter before. Is it okay to delete and re-download it? [yes]: yes
project_name [EveryCheese]:
project_slug [everycheese]:
description [The Ultimate Cheese Index!]:
author_name [Your name here]:
domain_name [everycheese.com]:
email [your-name-here@example.com]:
timezone [UTC]:
windows [n]:
Select database:
1 - PostgreSQL
2 - SQLite
Choose from 1, 2 [1]: 1
(everycheese) joshpanknin@joshs-mbp-2 wedge_django % ls
everycheese	hellodjango

(everycheese) joshpanknin@joshs-mbp-2 wedge_django % cd everycheese 
(everycheese) joshpanknin@joshs-mbp-2 everycheese % ls
CONTRIBUTORS.md         env.sample.windows      requirements
COPYING                 everycheese             requirements.txt
README.md               locale                  setup.cfg
config                  manage.py
env.sample.mac_or_linux pytest.ini

(everycheese) joshpanknin@joshs-mbp-2 everycheese % pip install -r requirements/
local.txt

(everycheese) joshpanknin@joshs-mbp-2 everycheese % cp env.sample.mac_or_linux .env
(everycheese) joshpanknin@joshs-mbp-2 everycheese % pg_isready
zsh: command not found: pg_isready
(everycheese) joshpanknin@joshs-mbp-2 everycheese % psql
zsh: command not found: psql
(everycheese) joshpanknin@joshs-mbp-2 everycheese % postgres -V
zsh: command not found: postgres
```

Don't know why postgres is not installing/configuring.  Some have suggested installing and configuring postgres manually, but cookiecutter is supposed to take care of all of that automatically, so I want to figure out why it didn't so I don't have to do it manually in the future.

**Comment by foarsitter** [comment]
You are on the wrong repository, https://github.com/feldroy/django-crash-starter is the right one. The commands you are showing has nothing to do with installing postgres. However there is an install script in there repository: https://github.com/feldroy/django-crash-starter/blob/master/installers/ubuntu/install_postgresql_13_ubuntu.sh, did you run that one?

**Comment by luzfcb** [comment]
@jpanknin

> I'm new to django and walking through "A Wedge of Django" by Dan and Audrey Roy Greenfeld. Terminal snippets are below. According to the instructions in the book, postgres should be installed after entering the commands listed, but I get the following errors:

By the error described, something went wrong in the installation/configuration of PostgreSQL on your Mac. Look at `1.6.2 Installing PostgreSQL on Mac` chapter.

You can probably get some additional help, missing steps in https://postgresapp.com/

Note: When the "A Wedge of Django" book was written, there was no Macbook with M1 processor (which uses ARM architecture and is incompatible with software for X86 architecture for Intel/AMD processors)

> Some have suggested installing and configuring postgres manually, but cookiecutter is supposed to take care of all of that automatically

This is a false conclusion. Cookiecutter just dynamically fills the customizable parts of a previously created project template, in order to reduce rework, however, by default it is not able to install and configure any software whatsoever, such as PostgreSQL

**Comment by luzfcb** [comment]
Since this issue is not related to the `cookiecutter-django` project itself, but it is related to problems installing and configuring PostgreSQL on OSX, I will close this issue.
