### ISSUE TITLE
inotify/watchdog detects a non-existent change in files, restarts Werkzeug/WSGI server unnecessarily

### ISSUE THREAD

**Issue by apkallum** [cookiecutter/cookiecutter-django#4179]
## What happened?
When I add a `breakpoint()` or ipdb in a Django view, and use `docker-compose -f local.yml run --rm --service-ports django` to start a server, the server restarts before I can touch the debugger. Here is an example with pdb, with a `breakpoint()` in a view: 

```
Django version 4.0.9, using settings 'config.settings.local'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 228-341-415
 * Detected change in '/usr/local/lib/python3.10/_strptime.py', reloading
 * Detected change in '/usr/local/lib/python3.10/pdb.py', reloading
 * Detected change in '/usr/local/lib/python3.10/cmd.py', reloading
 * Detected change in '/usr/local/lib/python3.10/bdb.py', reloading
> /app/zumr/circles/views.py(38)create_closed_circle()
-> circle = Circle.objects.create_private_circle(
 * Detected change in '/app/zumr/circles/views.py', reloading
(Pdb)  * Restarting with watchdog (inotify)
Performing system checks...
```  

## What should've happened instead?
I should have acess to the debugger.

**Comment by apkallum** [comment]
Actually the `watchdog` restarts when I touch any file, for example simply navigating to url will trigger it. Switching to the default stat backend of Werkzeug and rebuilding the stack works.

**Comment by sevdimali** [comment]
@apkallum could you please elaborate more, on how you can solve it? 
I am facing the same issue.

**Comment by sevdimali** [comment]
> Actually the `watchdog` backend of Werkzeug restarts the WSGI server despite the absence of any editing of project files. For example, simply navigating to a url will trigger a restart. Switching to the default stat backend of Werkzeug and rebuilding the stack solves the problem.

I had the same issue, solved as you described.

**Comment by spuigdengolas** [comment]
> Actually the `watchdog` backend of Werkzeug restarts the WSGI server despite the absence of any editing of project files. For example, simply navigating to a url will trigger a restart. Switching to the default stat backend of Werkzeug and rebuilding the stack solves the problem.

Could you explain to me how you did it? I'm having the same issue. Thanks

**Comment by apkallum** [comment]
@spuigdengolas Go to the file /requirements/local.txt, you will find `Werkzeug[watchdog]` listed. Remove watchdog and leave `Werkzeug`. Then reinstall the requirements or rebuild the containers.

**Comment by apkallum** [comment]
I wonder where should I open an issue, at the Werkzeug or Watchdog repo.

**Comment by spuigdengolas** [comment]
Thanks! I'll try what you propose.
I opened a discussion here:
https://github.com/cookiecutter/cookiecutter-django/discussions/4185

**Comment by paulsermon-gemfair** [comment]
A +1 on this.
I noticed it happened after updating Docker Desktop.

**Comment by browniebroke** [comment]
Seems relevant: https://github.com/pallets/werkzeug/issues/2603
