### ISSUE TITLE
Add a fallback service for maintenance mode

### ISSUE THREAD

**Issue by masavini** [cookiecutter/cookiecutter-django#4199]
## Description

It would be nice to have a simple "maintenance mode" static page to be displayed when the Django app is down for some reason.

I guess this could be implemented adding a new service in `production.yml` and configuring Traefik, what do you think about?

**Comment by browniebroke** [comment]
Good idea on the implementation (separate service + static page), but my first reaction is that it sounds outside of the scope of this project 🤔 Just a gut feeling though...

PS: cross referencing another issue where a similar feature was requested with a different approach #1083

**Comment by masavini** [comment]
you may consider this just like the postgres maintenance scripts or the vscode dev container setup: maybe a little out of the project scope, but surely a small investment for a big return...

**Comment by Andrew-Chen-Wang** [comment]
I think it's outside the scope as in it's a personal preference in deployment scenarios. There's Django maintenance package that does this. Another instance: some AWS ECS junkies will want a clean docker compose file. I personally write my own scripts to create blue/green deployments. So I think there are too many ways and depends on your deployment environment.

**Comment by browniebroke** [comment]
As discussed, closing as out of scope.
