### ISSUE TITLE
Stop lint checking PRs

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#4261]
## Description

Stop lint checking PRs during generation testing process

## Rationale

It's caused me a lot of pain trying to test PRs for lint errors. In the end, the user after they generate their templates can just run pre-commit run --all-files

It'll cause a CI to break initially for most users if they don't lint immediately, but it's not like that hasn't happened before due to unnoticed errors in PRs here anyway.

**Comment by browniebroke** [comment]
Thanks for opening this issue, it's definitely time to take a step back and re-evaluate the value these tools are bringing us vs the pain they cause.

> It's caused me a lot of pain trying to test PRs for lint errors

I've been struggling quite a bit with that myself with #3958 and #3827, and I'm quite familiar with the project, so it's fair to say that new contributors are probably put off with it.

> It'll cause a CI to break initially for most users if they don't lint immediately, but it's not like that hasn't happened before due to unnoticed errors in PRs here anyway.

Agree. Also, tools like black and isort wrap lines or not depending on the length of the `project_slug`, so even with our current setup, this might already happen.

I think it's important to make the distinction between auto-formatters, which will fix your offending code automatically, and pure linters which users would have to fix manually (e.g. flake8). IMO we should still run tools like flake8. 

It would be nice to have a way to run a few auto-formatters on demand, in case one wants to see how we're doing. But by default don't run these on CI.

**Comment by Andrew-Chen-Wang** [comment]
Agree with flake8 remaining as it catches so interesting things. And agree to disable black and isott in CI which are usually most of the errors I believe.

**Comment by browniebroke** [comment]
Here are some ideas:

1. Replace `pre-commit run` from `test_bare.sh` and `test_dcoker.sh` (along with the 2 git init + add) by just running flake8: 
    https://github.com/cookiecutter/cookiecutter-django/blob/cbb0e19de75eed12cfa84ca4e6d6e8a34ebe926e/tests/test_docker.sh#L17-L22
    Either remove pre-commit completely, or run just the flake8 hook: 
    `pre-commit run flake8 --show-diff-on-failure -a`
2. Add a pytest conditional skip to `test_black_passes`, which we don't include by default on CI (e.g. `@pytest.mark.skipif(os.getenv("ADVANCED_STYLES") == 1)`)
3. Add other similar pytest functions for `pyupgrade` and `isort`, with the same conditional skip

What do you think?

**Comment by Andrew-Chen-Wang** [comment]
1. Definitely works
2 and 3. I also think this works with disabling these tests when CI=true

**Comment by browniebroke** [comment]
Yes, that's true. I suggested a different env variable because I think that for new contributors, it would be nice to have tests run the same locally and CI by default. Otherwise people might spend time fixing tests that don't matter too much.

**Comment by Andrew-Chen-Wang** [comment]
I see. That makes sense to disable autoformat tests locally as well.
