### ISSUE TITLE
New Django project not building on Raspberry Pi

### ISSUE THREAD

**Issue by pmontgo33** [cookiecutter/cookiecutter-django#4280]
## What happened?
Getting error on initial build of new cookiecutter django project with docker.
ran docker compose -f local.yml build

## What should've happened instead?
Should have built the docker image.

## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 2.1.1
  - OS name and version:

    On Linux, run

    ```bash
    lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
    ```

    On MacOs, run

    ```bash
    sw_vers
    ```

    On Windows, via CMD, run

    ```
    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    ```

    ```bash
    # Insert here the OS name and version

    ```

  - Python version, run `python3 -V`:
  - Docker version (if using Docker), run `docker --version`:
  - docker-compose version (if using Docker), run `docker-compose --version`:
  - ...

- Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and macOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)

```json

```

<summary>
Logs:
<details>
<pre>
#0 155.2       Building wheels for collected packages: cffi
#0 155.2         Building wheel for cffi (setup.py): started
#0 155.2         Building wheel for cffi (setup.py): finished with status 'error                                                                                                                                                             '
#0 155.2         error: subprocess-exited-with-error
#0 155.2
#0 155.2         × python setup.py bdist_wheel did not run successfully.
#0 155.2         │ exit code: 1
#0 155.2         ╰─> [38 lines of output]
#0 155.2             /usr/local/lib/python3.11/site-packages/setuptools/config/s                                                                                                                                                             etupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is depr                                                                                                                                                             ecated, use license_files instead.
#0 155.2               warnings.warn(msg, warning_class)
#0 155.2             running bdist_wheel
#0 155.2             running build
#0 155.2             running build_py
#0 155.2             creating build
#0 155.2             creating build/lib.linux-armv7l-cpython-311
#0 155.2             creating build/lib.linux-armv7l-cpython-311/cffi
#0 155.2             copying cffi/error.py -> build/lib.linux-armv7l-cpython-311                                                                                                                                                             /cffi
#0 155.2             copying cffi/cparser.py -> build/lib.linux-armv7l-cpython-3                                                                                                                                                             11/cffi
#0 155.2             copying cffi/vengine_gen.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/lock.py -> build/lib.linux-armv7l-cpython-311/                                                                                                                                                             cffi
#0 155.2             copying cffi/recompiler.py -> build/lib.linux-armv7l-cpytho                                                                                                                                                             n-311/cffi
#0 155.2             copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-cp                                                                                                                                                             ython-311/cffi
#0 155.2             copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-cp                                                                                                                                                             ython-311/cffi
#0 155.2             copying cffi/commontypes.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/model.py -> build/lib.linux-armv7l-cpython-311                                                                                                                                                             /cffi
#0 155.2             copying cffi/ffiplatform.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/api.py -> build/lib.linux-armv7l-cpython-311/c                                                                                                                                                             ffi
#0 155.2             copying cffi/__init__.py -> build/lib.linux-armv7l-cpython-                                                                                                                                                             311/cffi
#0 155.2             copying cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython                                                                                                                                                             -311/cffi
#0 155.2             copying cffi/verifier.py -> build/lib.linux-armv7l-cpython-                                                                                                                                                             311/cffi
#0 155.2             copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/_cffi_include.h -> build/lib.linux-armv7l-cpyt                                                                                                                                                             hon-311/cffi
#0 155.2             copying cffi/parse_c_type.h -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/_embedding.h -> build/lib.linux-armv7l-cpython                                                                                                                                                             -311/cffi
#0 155.2             copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             running build_ext
#0 155.2             building '_cffi_backend' extension
#0 155.2             creating build/temp.linux-armv7l-cpython-311
#0 155.2             creating build/temp.linux-armv7l-cpython-311/c
#0 155.2             gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -                                                                                                                                                             fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -                                                                                                                                                             I/usr/include/libffi -I/usr/local/include/python3.11 -c c/_cffi_backend.c -o bui                                                                                                                                                             ld/temp.linux-armv7l-cpython-311/c/_cffi_backend.o
#0 155.2             c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file o                                                                                                                                                             r directory
#0 155.2                15 | #include <ffi.h>
#0 155.2                   |          ^~~~~~~
#0 155.2             compilation terminated.
#0 155.2             error: command '/usr/bin/gcc' failed with exit code 1
#0 155.2             [end of output]
#0 155.2
#0 155.2         note: This error originates from a subprocess, and is likely no                                                                                                                                                             t a problem with pip.
#0 155.2         ERROR: Failed building wheel for cffi
#0 155.2         Running setup.py clean for cffi
#0 155.2       Failed to build cffi
#0 155.2       Installing collected packages: wheel, typing-extensions, setuptoo                                                                                                                                                             ls, pycparser, packaging, setuptools_scm, cffi
#0 155.2         Running setup.py install for cffi: started
#0 155.2         Running setup.py install for cffi: finished with status 'error'
#0 155.2         error: subprocess-exited-with-error
#0 155.2
#0 155.2         × Running setup.py install for cffi did not run successfully.
#0 155.2         │ exit code: 1
#0 155.2         ╰─> [40 lines of output]
#0 155.2             /usr/local/lib/python3.11/site-packages/setuptools/config/s                                                                                                                                                             etupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is depr                                                                                                                                                             ecated, use license_files instead.
#0 155.2               warnings.warn(msg, warning_class)
#0 155.2             running install
#0 155.2             /usr/local/lib/python3.11/site-packages/setuptools/command/                                                                                                                                                             install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use                                                                                                                                                              build and pip and other standards-based tools.
#0 155.2               warnings.warn(
#0 155.2             running build
#0 155.2             running build_py
#0 155.2             creating build
#0 155.2             creating build/lib.linux-armv7l-cpython-311
#0 155.2             creating build/lib.linux-armv7l-cpython-311/cffi
#0 155.2             copying cffi/error.py -> build/lib.linux-armv7l-cpython-311                                                                                                                                                             /cffi
#0 155.2             copying cffi/cparser.py -> build/lib.linux-armv7l-cpython-3                                                                                                                                                             11/cffi
#0 155.2             copying cffi/vengine_gen.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/lock.py -> build/lib.linux-armv7l-cpython-311/                                                                                                                                                             cffi
#0 155.2             copying cffi/recompiler.py -> build/lib.linux-armv7l-cpytho                                                                                                                                                             n-311/cffi
#0 155.2             copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-cp                                                                                                                                                             ython-311/cffi
#0 155.2             copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-cp                                                                                                                                                             ython-311/cffi
#0 155.2             copying cffi/commontypes.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/model.py -> build/lib.linux-armv7l-cpython-311                                                                                                                                                             /cffi
#0 155.2             copying cffi/ffiplatform.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/api.py -> build/lib.linux-armv7l-cpython-311/c                                                                                                                                                             ffi
#0 155.2             copying cffi/__init__.py -> build/lib.linux-armv7l-cpython-                                                                                                                                                             311/cffi
#0 155.2             copying cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython                                                                                                                                                             -311/cffi
#0 155.2             copying cffi/verifier.py -> build/lib.linux-armv7l-cpython-                                                                                                                                                             311/cffi
#0 155.2             copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/_cffi_include.h -> build/lib.linux-armv7l-cpyt                                                                                                                                                             hon-311/cffi
#0 155.2             copying cffi/parse_c_type.h -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             copying cffi/_embedding.h -> build/lib.linux-armv7l-cpython                                                                                                                                                             -311/cffi
#0 155.2             copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpyth                                                                                                                                                             on-311/cffi
#0 155.2             running build_ext
#0 155.2             building '_cffi_backend' extension
#0 155.2             creating build/temp.linux-armv7l-cpython-311
#0 155.2             creating build/temp.linux-armv7l-cpython-311/c
#0 155.2             gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -                                                                                                                                                             fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -                                                                                                                                                             I/usr/include/libffi -I/usr/local/include/python3.11 -c c/_cffi_backend.c -o bui                                                                                                                                                             ld/temp.linux-armv7l-cpython-311/c/_cffi_backend.o
#0 155.2             c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file o                                                                                                                                                             r directory
#0 155.2                15 | #include <ffi.h>
#0 155.2                   |          ^~~~~~~
#0 155.2             compilation terminated.
#0 155.2             error: command '/usr/bin/gcc' failed with exit code 1
#0 155.2             [end of output]
#0 155.2
#0 155.2         note: This error originates from a subprocess, and is likely no                                                                                                                                                             t a problem with pip.
#0 155.2       error: legacy-install-failure
#0 155.2
#0 155.2       × Encountered error while trying to install package.
#0 155.2       ╰─> cffi
#0 155.2
#0 155.2       note: This is an issue with the package mentioned above, not pip.
#0 155.2       hint: See above for output from the failure.
#0 155.2
[+] Building 169.8s (8/15)
 => [internal] load build definition from Dockerfile                       0.5s
 => => transferring dockerfile: 1.82kB                                     0.0s
 => [internal] load .dockerignore                                          0.3s
 => => transferring context: 174B                                          0.0sr                                                                                                                                                              => [internal] load metadata for docker.io/library/python:3.11.3-slim-bul  0.9s
 => [internal] load build context                                          1.0s
 => => transferring context: 3.80kB                                        0.8s
 => [python 1/1] FROM docker.io/library/python:3.11.3-slim-bullseye@sha25  0.0sy                                                                                                                                                              => CACHED [python-run-stage 1/7] RUN apt-get update && apt-get install -  0.0s
 => CACHED [python-build-stage 1/3] RUN apt-get update && apt-get install  0.0s
 => CACHED [python-build-stage 2/3] COPY ./requirements /requirements      0.0s
 => [python-build-stage 3/3] RUN pip wheel --no-cache-dir --wheel-dir /  166.9s
 => => # ta 0:00:00                                                            b                                                                                                                                                              => => # Collecting argon2-cffi-bindings
 => => #   Downloading argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)
 => => #      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 14.5 MB/s eta
 => => #  0:00:00
 => => #   Installing build dependencies: started
failed to solve: process "/bin/sh -c pip wheel --wheel-dir /usr/src/app/wheels                                                                                                                                                                 -r ${BUILD_ENVIRONMENT}.txt" did not complete successfully: exit code: 1
</pre>
</details>
</summary>

**Comment by luzfcb** [comment]
Looks like there is a missing non-python dependency required to compile and install cffi. Try to add `libffi-dev \`  after https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L12

**Comment by pmontgo33** [comment]
Looks like the same error after adding and trying to build again. I noticed this line in the error output. Could this be the problem?

 c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
 15 | #include <ffi.h>
      |                ^~~~~~~

**Comment by browniebroke** [comment]
It's working on CI and on my machine, so that's weird. Can you give us more details about your OS and its version, the version of Docker and docker-compose please? The issue template explains how to get those

**Comment by browniebroke** [comment]
> Distributor ID: Raspbian
> Description: Raspbian GNU/Linux 11 (bullseye)

Are you running your project on a Raspberry Pi? Waw... 

Are you able to run `pip install cffi` on your host machine (outside of Docker)? I looked through [their repo](https://foss.heptapod.net/pypy/cffi) to find similar issues, nothing specific to Raspian came up, but they have a [few closed issues](https://foss.heptapod.net/pypy/cffi/-/issues/?search=fatal+error%3A+ffi.h%3A+No+such+file&sort=created_date&state=closed&first_page_size=20) with that error message.

**Comment by pmontgo33** [comment]
I was able to successfully run pip install cffi with no errors. Im going to spin up an Ubuntu server vm on another machine and see if I can get it to work there instead of the pi.

**Comment by browniebroke** [comment]
One last thing that would be worth trying is running the commands from the Dockerfile manually:

```
# Run the base docker image
docker run -it python:3.11.3-slim-bullseye bash

# In the prompt from the container:
pip install cffi
```

If that reproduces the problm, you can try installing the same OS level dependencies than from the Dockerfile: 

https://github.com/cookiecutter/cookiecutter-django/blob/cbcade52ca6c7bfff57e3b80b3fd132124bef06d/%7B%7Bcookiecutter.project_slug%7D%7D/compose/local/django/Dockerfile#L9-L14

Or the ones that are recommended from non-Docker setup:

https://github.com/cookiecutter/cookiecutter-django/blob/cbcade52ca6c7bfff57e3b80b3fd132124bef06d/%7B%7Bcookiecutter.project_slug%7D%7D/utility/requirements-bullseye.apt#L1-L23

**Comment by browniebroke** [comment]
So I tried to look at it today and was able to reproduce the problem with the following steps:

```
# Run the base docker image
docker run -it python:3.11.3-slim-bullseye bash

# Install OS level dependencies Inside the image
apt-get update && apt-get install --no-install-recommends -y build-essential

# Try to install the package
pip install cffi  --> same error as reported
```

I was able to fix it with @luzfcb suggestion:

```
apt-get update && apt-get install --no-install-recommends -y libffi-dev

# Try to install the package again
pip install cffi  --> works fine
```

**Comment by browniebroke** [comment]
There is also the solution to add an extra index like: https://www.piwheels.org

**Comment by Andrew-Chen-Wang** [comment]
might be worth having an option use_raspbian kinda like use_windows option

**Comment by husnainsaeed00** [comment]
As a new developer am learning a lot from your discussion.

regards

**Comment by browniebroke** [comment]
Unless there is a huge demand for deploying on Raspberry Pi and someone is willing to do the work, I don't think it's worth the effort to fix this. In particular, cryptography takes forever to build from source on Raspberry Pi, which makes it impractical to use in its current state.

It would probably be more beneficial to the overall community if instead folks focused their effort on getting more wheels built for Raspberry PI, by supporting the [PiWheels](https://www.piwheels.org/) project, for example. It feels like a problem outside of the scope of this project.
