### ISSUE TITLE
Need example of .env file for making DB connection

### ISSUE THREAD

**Issue by vidarbrekke** [cookiecutter/cookiecutter-django#4331]
I'm a novice, but I got as far as the last step of the setup, i.e. `python manage.py migrate`

I get this error, which I assume means that the .env file I created is not formatted correctly (I placed it in app root where manage.py is located). 

I would assume that when you follow the step-by-step prompts to set up the project (I am on Windows), there is a specific formatting of the .env  that's expected.  Also, in case this matters, I downloaded the latest PostgreSQL (which is 14.7) as I assumed all minor versions of v14 would work. If this is not the case, please let me know. 

Here is my current .env file. Can you tell if this is not what's required:
# PostgreSQL
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=my_app
POSTGRES_USER=postgres
POSTGRES_PASSWORD=my_pass

**Comment by vidarbrekke** [comment]
i hardcoded the db values into the base.py and that worked.

**Comment by foarsitter** [comment]
Your .env is only read when `READ_DOT_ENV_FILE=True`. See https://github.com/cookiecutter/cookiecutter-django/blob/54d78f733ef97e3077418affa54cac7b74dbb35d/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#LL13C1-L13C18 for the implementation. 

If you need more help you can open an discussion.

**Comment by vidarbrekke** [comment]
Thank you for getting back to me. The value was set to True, but that didn't work. It worked when I hardcoded the DB credentials into the base.py file. It is possible that the .env file had the wrong key/value pair, e.g. was "POSTGRES_HOST" the right key? I also ran the following commands in Powershell on Windows, which may or may not have made a difference:
setx DB_NAME "my_app"
setx DB_USER "postgres"
setx DB_PASSWORD "my_pass"
setx DB_HOST "localhost"
setx DB_PORT "5432"

**Comment by foarsitter** [comment]
The correct names can be found here: https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.envs/.local/.postgres 

You can try setting the default of the line I mentioned in my previous post to `True` while testing.

**Comment by vidarbrekke** [comment]
Very helpful, thank you!
