### ISSUE TITLE
Brand-new project doesnt' comply with 'pre-commit' rules

### ISSUE THREAD

**Issue by matheusjardimb** [cookiecutter/cookiecutter-django#4332]
## What happened?
When creating a new project (I've tested with multiple configs) the generated code doesn't comply with the pre-commit original configuration.

The project created is fully functional, but it becomes bothersome the need to fix the newly generated code. 

## What should've happened instead?

The brand-new project should comply with the pre-commit rules by default.

## Additional details

To reproduce the issue, simply create a new project and run the pre-commit command available in the .gitlab-ci.yml file:

```pre-commit run --show-diff-on-failure --color=always --all-files```

Later, when running `git status` these files appear changed (haven't opened the project into Pycharm yet): 
```
 M .idea/project_greenpath.iml
 M .idea/runConfigurations/pytest___.xml
 M .idea/runConfigurations/pytest__users.xml
 M .idea/runConfigurations/runserver.xml
 M .pre-commit-config.yaml
 M project/users/tests/test_views.py
 M project/users/urls.py
 M local.yml
```

- Host system configuration:
 - Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 2.1.1 from (Python 3.11.3 (main, May 11 2023, 09:53:46) [GCC 11.3.0])

  - OS name and version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

  - Python version: Python 3.11.3  
  - Docker version (if using Docker): Docker version 23.0.6, build ef23cbc
  - docker-compose version (if using Docker): Docker Compose version v2.17.3

**Comment by browniebroke** [comment]
If you run it again, does it passes?

**Comment by browniebroke** [comment]
I just checked, and the pe-commit "failures" come from prettier and isort, which are automatically fixed. We don't garantee that auto-fixables pre-commit checks pass (see #4261), we just try to minimise them.

For isort, it's not even possible, as the lines with several imports may wrap or not depending on the length of the project name.

Feel free to send a PR to reduce the likelyhood of such failures.
