### ISSUE TITLE
add support to multi-tenant (Django tenant package)

### ISSUE THREAD

**Issue by jugurtha114** [cookiecutter/cookiecutter-django#4334]
Hi there,

I hope you're doing well. I wanted to discuss a feature request that I believe would greatly enhance the functionality of Django Cookie Cutter.

**Description**
I am proposing the addition of support for Django Tenant in the Django Cookie Cutter. This would involve integrating the necessary packages, configurations, and templates to seamlessly incorporate Django Tenant into the project structure generated by Cookie Cutter.

To implement this feature, the Django Cookie Cutter  can be updated to include Django Tenant as a dependency. The necessary configurations, such as setting up tenant-specific databases and managing tenant routing, can be added to the generated project's settings and URL files. Additionally, sample templates and views demonstrating multi-tenancy can be included to guide developers in implementing tenant-based functionality.

**Rationale**
There are several compelling reasons to implement support for Django Tenant in Django Cookie Cutter:

- Simplified Multi-Tenancy Setup: With built-in support for Django Tenant, developers using Django Cookie Cutter can quickly and easily set up multi-tenant applications without the need for manual integration. This saves time and effort during the initial project setup.

- Standardization and Consistency: By incorporating Django Tenant into the Cookie Cutter template, the implementation of multi-tenancy becomes standardized across projects. Developers can follow a consistent approach, reducing the chances of errors and ensuring a reliable and maintainable codebase.

- Improved Developer Experience: Adding support for Django Tenant in Django Cookie Cutter enhances the overall developer experience by providing a seamless workflow for building multi-tenant applications. Developers can focus on implementing tenant-specific features and functionality rather than dealing with the complexities of setting up multi-tenancy from scratch.

- 
- Community Adoption: Django Tenant is a widely used package for multi-tenancy in Django projects. By including native support for Django Tenant in Django Cookie Cutter, the template becomes more attractive to developers working on multi-tenant applications. This can help foster wider adoption and promote the growth of the Django Cookie Cutter community.

I believe that incorporating support for Django Tenant in Django Cookie Cutter would greatly benefit developers and streamline the process of building multi-tenant applications.

**Comment by browniebroke** [comment]
This was suggested before (https://github.com/cookiecutter/cookiecutter-django/issues/3849) and closed as won't fix. Our position hasn't changed on this. I consider multi tenancy to not be common enough to justify the added complexity. Not to mention that with each extra 3rd party Django packages, we're adding friction when it comes time to upgrade to the next major Django.
