### ISSUE TITLE
LOG:  unexpected EOF on client connection with an open transaction

### ISSUE THREAD

**Issue by mirodil1** [cookiecutter/cookiecutter-django#4343]
I've used `cookiecutter-django` on my projects, but on my last two projects I am getting error `LOG:  unexpected EOF on client connection with an open transaction` when installed `cookiecutter-django` with celery and admin page also getting slower.

**Comment by browniebroke** [comment]
Please follow the issue template to provide more information, this is VERY little to get by. Help us help you.
