### ISSUE TITLE
Getting error from postgres service on docker when using celery.

### ISSUE THREAD

**Issue by mirodil1** [cookiecutter/cookiecutter-django#4368]
## What happened?
Getting `LOG:  unexpected EOF on client connection with an open transaction` from postgres  in admin page when project is running with celery, and   **This page isn’t working** **127.0.0.1** didn’t send any data. `ERR_EMPTY_RESPONSE` from browser. This also happened while trying to open admin page which is used `StackedInline` or `TabularInline`. After reloading the page few times, getting response.
## What should've happened instead?
Load the page whithout any errors
## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): 2.1.1
  - OS name and version: Ubuntu 22.04.2 LTS
  - Python version, run `python3 -V`: 3.10.6
  - Docker version (if using Docker), run `docker --version`: 24.0.0
  - docker-compose version (if using Docker), run `docker-compose --version`: 1.29.2

- Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and macOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
```json
{
  "cookiecutter": {
    "project_name": "project",
    "project_slug": "project",
    "description": "project",
    "author_name": "Full Name",
    "domain_name": "ddd",
    "email": "email@gmail.com",
    "version": "0.1.0",
    "open_source_license": "Not open source",
    "timezone": "Asia/",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "y",
    "postgresql_version": "14",
    "cloud_provider": "None",
    "mail_service": "Other SMTP",
    "use_async": "n",
    "use_drf": "y",
    "frontend_pipeline": "None",
    "use_celery": "y",
    "use_mailhog": "n",
    "use_sentry": "n",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
    "_template": "https://github.com/cookiecutter/cookiecutter-django",
    "_output_dir": "/home/path/to/"
  }

```

<summary>
Logs:
<details>
<pre>
_local_django | Django version 4.0.8, using settings 'config.settings.local'
_local_django | Development server is running at http://0.0.0.0:8000/
_local_django | Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
_local_django | Quit the server with CONTROL-C.
_local_django |  * Debugger is active!
_local_django |  * Debugger PIN: 100-506-377
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/auth/__init__.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/auth/middleware.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/admin/sites.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/views/decorators/cache.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/admin/options.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/cProfile.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/whitenoise/middleware.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/werkzeug/debug/__init__.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/werkzeug/serving.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/http/server.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/auth/backends.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/forms/models.py', reloading
_local_django |  * Detected change in '/usr/local/lib/python3.10/site-packages/django/contrib/auth/forms.py', reloading
_local_postgres | 2023-06-05 06:42:14.704 UTC [830] LOG:  unexpected EOF on client connection with an open transaction
_local_django |  * Restarting with watchdog (inotify)
_local_django | Performing system checks...

</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
I see in your logs that the problem seems to start with a detected change by Werkzeug, did you see this other issue: #4179? 

I can see you're running Python 3.10, but the template was updated to Python 3.11 almost 2 months ago (in #4256) so you might be running an older version of Werkzeug before the issue was fixed. Could you confirm which version of Werkzeug is currently installed in your project? If you're using a version <2.3.0, your problem might be solved by upgrading.

**Comment by mirodil1** [comment]
I was using a version ==2.2.2, now upgraded, I think everything is fine now. Thanks!

**Comment by browniebroke** [comment]
Cool! Thanks for reporting back. Going to close this issue then.
