### ISSUE TITLE
Django Issue Checker error?

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [cookiecutter/cookiecutter-django#4424]
## What happened?

Was looking to use asyncio httpx instead of requests, but I found the issue checker is running into errors?

https://github.com/cookiecutter/cookiecutter-django/actions/runs/5397595858/jobs/9802447698

**Comment by browniebroke** [comment]
Yes it failed this morning for some reasons. I just retried it and it worked. Might have been a flaky failure.

**Comment by browniebroke** [comment]
Well, it ran, but it re-opened the issue despite the fact that we are now on Django 4.2... So maybe there is something to fix after all 😄
