### ISSUE TITLE
Project incorrectly generated if a Pycharm is picked as Editor

### ISSUE THREAD

**Issue by tmajerech** [cookiecutter/cookiecutter-django#4442]
## What happened?
I generated a cookiecutter-django project with PyCharm selected as my Editor, but the initial run configurations for my PyCharm editor were unexpectedly absent.

## What should've happened instead?
The initial run configuration for PyCharm should have been present.

## Additional details
It seems that the only thing related to my specific issue is a typo in recent changes. I opened a PR #4441  hopefully fixing it.

**Comment by browniebroke** [comment]
Right, it was caused by #4198
