### ISSUE TITLE
Improve test coverage of production build/config

### ISSUE THREAD

**Issue by browniebroke** [cookiecutter/cookiecutter-django#4462]
## Description

Add some automated check for the production build and configuration. While it would be tricky to do an actual deployment, it would be nice to at least try to install dependencies for prod, and run a simple Django command like [`manage.py check --deploy`](https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/#run-manage-py-check-deploy).

## Rationale

Currently our CI isn't covering the production setup at all, and some issues won't be caught unless we do an actual deployment, which needs some manual work.

**Comment by Ahmed-Qaisar** [comment]
Hi, would it be possible for this issue to be assigned to me please?

**Comment by foarsitter** [comment]
Sure thing @Ahmed-Qaisar, next time just create a PR and submit it.
