### ISSUE TITLE
Upload media permission denied in production

### ISSUE THREAD

**Issue by Tshibek** [cookiecutter/cookiecutter-django#4478]
Hello, with new Django version 4.2.3, i need add in STORAGES default
`STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}`
and after it i added, i tried upload files in production and get ERROR500, in console is
log like that `PermissionError: [Errno 13] Permission denied: '/app/{project_name}/media/file'`

**Comment by browniebroke** [comment]
**We have a set of issue templates, please help us help you: follow them to report a bug, they have questions we _really_ need answers from, otherwise it's really hard to answer.**

Might be related to https://github.com/cookiecutter/cookiecutter-django/issues/4209 which OP mentioned a permission issue:

> in order to create my own media folder with django:django as the owner:group, because in the PR doesn't include the media folder creation and when I build containers this media folder was created with root:root ownership, so my django app crashed when I tried to upload any file because doesn't have permissions to write on that folder.

**Comment by Tshibek** [comment]
From the above just did 
> The only one modification I made was in /compose/production/django/Dockerfile, I added this line: RUN mkdir ${APP_HOME}/proveemax/media && chown django:django ${APP_HOME}/proveemax/media
> I think @edwardigarashi might be onto something. The rule for `web-media-router` needs to have priority over the rule for `web-secure-router`. Traefik looks at the rule length to determine this when no explicit priority is set.
> 
> These rules are defined in [this file (traefik.yml)](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/traefik/traefik.yml).
> 
> Adding a high priority like 1000 (just has to be higher than the length of the rule in `web-secure-router`) will make Traefik prioritize this rule.
> 
> ```
>     web-media-router:
>       rule: "Host(`{{ cookiecutter.domain_name }}`) && PathPrefix(`/media/`)"
>       entryPoints:
>         - web-secure
>       middlewares:
>         - csrf
>       service: django-media
>       tls:
>         certResolver: letsencrypt
>       priority: 1000
> ```
> 
> Alternatively, you can manually set the priority for both rules. Which might be a better solution to merge in case this solves the issue. Or we could even add the `www` subdomain to the media router rule like this:
> 
> ```
> rule: "(Host(`{{ cookiecutter.domain_name }}`) || Host(`www.{{ cookiecutter.domain_name }}`)) && PathPrefix(`/media/`)"
> ```
> 
> This would always make the media router rule have priority when consistent with the `web-secure-router` rule.
> 
> @maponzzi This is definitely happening in your case. Your first rule has a priority of 70 and the media rule has a priority of 56. So nothing will ever be sent to the media router.

> try changing the nginx container from nginx:1.17.8-alpine to nginx:1.23-alpine in [the Docker file for nginx](https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/nginx/Dockerfile) and see if that fixes the issue.
