### ISSUE TITLE
Unused gulp dependency added to package.json when Webpack is chosen

### ISSUE THREAD

**Issue by acyment** [cookiecutter/cookiecutter-django#4513]
## What happened?
package.json has reference to `"gulp-concat": "^2.6.1"` even though it is not used when Webpack has been chosen

## What should've happened instead?
No reference to gulp-concat at all when using Webpack

## Additional details

    Host system configuration:
        Cookiecutter 2.1.1
        Ventura 13.5
        Python 3.11.4
        Docker version 24.0.2, build cb74dfc
        Docker Compose version v2.19.1

**Comment by browniebroke** [comment]
Good catch! For anyone who wants to contribute to the project, the value should be added here:
 https://github.com/cookiecutter/cookiecutter-django/blob/master/hooks/post_gen_project.py#L182-L192

**Comment by acyment** [comment]
Tks, will directly send a pull request next time then👍🏼On 11 Aug 2023, at 15:02, Bruno Alla ***@***.***> wrote:﻿
Good catch! For anyone who wants to contribute to the project, the value should be added here:
https://github.com/cookiecutter/cookiecutter-django/blob/master/hooks/post_gen_project.py#L182-L192
