### ISSUE TITLE
Collectfast is no longer maintained

### ISSUE THREAD

**Issue by browniebroke** [cookiecutter/cookiecutter-django#4523]
While trying to test #4477, I went over the collectfast repo today and noticed that [the repo is archived](https://github.com/antonagestam/collectfast). There was [an issue](https://github.com/antonagestam/collectfast/issues/212) opened a while back to try to look for new maintainers, which didn't really go anywhere. There is also a note at the top of the readme for that.

I don't think it's causing any problems, but if anything arises, we'll probably have to drop the dependency. It's not heavily integrated nor is it linked to any options, so it should be relatively simple to remove. I couldn't find a fork that looked actively maintained and I don't know of a good replacement. 

Why keep it? I haven't used it in a while, but I remembered that it provided a massive speed boost to `collectstatic` which went down from a couple of minutes to a few seconds.

Opening this for visibility, let's see if it breaks

**Comment by casualuser** [comment]
I'm experiencing issues with Django 4.2 and collectfast with connection to s3 just freeze at the end. So switched off it for now but this increase our collect static from several minutes up to a hour because collectstatic copy all images once again there.
It will be really nice if you can fork and start supporting collectfast as maintainers.

**Comment by jasongi** [comment]
I've forked this and spent a bit of time getting it working with 4.2+
https://github.com/jasongi/collectfasta

**Comment by DmytroLitvinov** [comment]
Hi @jasongi ,
May I ask you then open Issues in your fork in case you plan to actively support it?

**Comment by jasongi** [comment]
@DmytroLitvinov sure - I didn’t realise issues weren’t automatically enabled after forking 😅
