### ISSUE TITLE
Invalid HTTP_HOST header: <ip>. You may need to add <ip> to ALLOWED_HOSTS. (yes, again)

### ISSUE THREAD

**Issue by lev-slinsen** [cookiecutter/cookiecutter-django#4533]
I am trying to launch my project on an AWS machine. I have tried both `ALLOWED_HOSTS = ["*"]` as well as hardcoding public address of my AWS EC2 instance. Both times I get the error. What might be missing?..

**Comment by foarsitter** [comment]
Try stackoverflow for this type of questions. Since a value of '*' will match anything, your problem lies elsewhere. Probably you did not restart your server properly since the change isn't taken into account.
