### ISSUE TITLE
Addressing E203 Whitespace Error in Pre-commit using flake8 Configuration

### ISSUE THREAD

**Issue by SungMinWoo** [cookiecutter/cookiecutter-django#4538]
## Description

What are you proposing? How should it be implemented?

I propose adding the `extend-ignore = E203` option to the flake8 configuration in the project's pre-commit configuration file. This would address the issue of the `E203 "whitespace before ':'"` error that appears in the code snippet below:

`foo[index + 1 :]`

## Rationale

Why should this feature be implemented?

This issue seems to have been a long-standing topic of discussion, as seen in this GitHub issue: https://github.com/PyCQA/pycodestyle/issues/373. It appears to be a recurring problem for many developers.

Furthermore, the recommendation to add the `extend-ignore = E203` option comes from Black's official documentation in the context of ensuring compatibility with other tools like flake8: https://github.com/psf/black/blob/main/docs/guides/using_black_with_other_tools.md#flake8.

Is it acceptable if I submit a pull request to address this issue?

**Comment by browniebroke** [comment]
Hey! Thanks for the suggestion. It makes sense to me, indeed, I checked a few of my projects where I have it set. Pull request welcome.
