### ISSUE TITLE
Why prefer python than bash for wait the service start

### ISSUE THREAD

**Issue by AdrianPardo99** [cookiecutter/cookiecutter-django#4539]
## Description

In this file

https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/entrypoint

Why don't use some tcp listener for docker like [wait-for](https://github.com/eficode/wait-for) or [wait-for-it.sh](https://github.com/vishnubob/wait-for-it)

## Rationale

I think executing the python live code its a perfect idea but if we can implement a native script (bash) for implement another services that need to start first in the app maybe can replicate in other projects or services, maybe its only fork the script or the bash function.

Or maybe its only wait for the start of the service in a single file for wait until the database service is already started and exit.

**Comment by browniebroke** [comment]
I honestly don't know why it's been done like this, maybe the original pull request has some details. Have you tried to search in the git history? 

I personally don't really have an issue with the current solution, but simplifications are always welcome. I'd be happy to replace it with an off the shelves solution.

**Comment by foarsitter** [comment]
Adding wait-for to the project also comes in handy as `HEALTHCHECK` as discussed in https://github.com/cookiecutter/cookiecutter-django/issues/4428
