### ISSUE TITLE
waiting for postgres to become available..

### ISSUE THREAD

**Issue by akashverma0786** [cookiecutter/cookiecutter-django#4670]
### Discussed in https://github.com/cookiecutter/cookiecutter-django/discussions/4669

<div type='discussions-op-text'>

<sup>Originally posted by **akashverma0786** November  7, 2023</sup>
![image](https://github.com/cookiecutter/cookiecutter-django/assets/138790903/30f1c600-db5d-42f8-81ab-f829151e76fe)
I followed the documentation but I am getting the same issue even after starting a new project.</div>

**Comment by foarsitter** [comment]
The error message is pretty clear, just read the logs in the screenshot from top to bottom.

**Comment by akashverma0786** [comment]
using postgres version 11 solved the issue

**Comment by akashverma0786** [comment]
![image](https://github.com/cookiecutter/cookiecutter-django/assets/138790903/20e6273b-8ada-4697-bd4a-8c702a7fb240)
Now it shows password authentication failed

**Comment by foarsitter** [comment]
Make sure your container is initiated with the same credentials. 
Search the docker volume `docker volume ls` and delete it `docker volume rm <volume_name>`. Then start your postgres instance again. Make sure you have enough memory left as your first screenshot shows you didn't. Then everything will be fine.
