### ISSUE TITLE
Waiting for postgres to become available..

### ISSUE THREAD

**Issue by akashverma0786** [cookiecutter/cookiecutter-django#4676]
![image](https://github.com/cookiecutter/cookiecutter-django/assets/138790903/4cfd42c7-c0d7-4c46-9a62-c63b6d5f6a3b)
Now this time it is showing this error. what should i do now?

**Comment by foarsitter** [comment]
1) Stop spamming 
2) This is not a Q&A section 
3) Learn the basics and start with less movable parts as possible. If this is your first time docker & django? Start with a django project without docker & postgres.
