### ISSUE TITLE
VSCode extensions are deprecated

### ISSUE THREAD

**Issue by mpsantos** [cookiecutter/cookiecutter-django#4677]
The tools support for the Python extension in VS Code is [deprecated](https://devblogs.microsoft.com/python/python-in-visual-studio-code-april-2022-release/#pylint-extension), **breaking the dev container**. 

The [recommendation](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions#linting-and-formatting-settings-deprecation) is to use separate extensions for linting and formatting.

**Comment by browniebroke** [comment]
Would like to send a pull request to fix that?

**Comment by mpsantos** [comment]
I might try, but my knowledge about these tools configurations is limited.

**Comment by mpsantos** [comment]
After further testing, the deprecation was not the cause for breaking the dev container.
But the vscode settings for the dev container are still deprecated.

**Comment by browniebroke** [comment]
Cc @masavini

**Comment by matheus-pereira-drm** [comment]
I think we can close this issue as ruff replaced those extensions

**Comment by browniebroke** [comment]
Ok thanks
