### ISSUE TITLE
pre-commit hook id: check-json FAILING on '//' commented out lines devcontainer.json

### ISSUE THREAD

**Issue by HilbertSpecs** [cookiecutter/cookiecutter-django#4697]
## What happened?
After successfully creating cookiecutter-django project following steps in documentation at:
https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html

Trying to commit: pre-commit hooks run producing output:

trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check json...............................................................Failed
- hook id: check-json
- exit code: 1

.devcontainer/devcontainer.json: Failed to json decode (Expecting value: line 1 column 1 (char 0))

NOTE: if I remove the first line in file commented out the following output is produced by pre-commit hooks output (producing an error at the next commented out line):

.devcontainer/devcontainer.json: Failed to json decode (Expecting property name enclosed in double quotes: line 24 column 5 (char 526))

check toml...............................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
debug statements (python)................................................Passed
check builtin type constructor use.......................................Passed
check for case conflicts.................................................Passed
check docstring is first.................................................Passed
detect private key.......................................................Passed
django-upgrade...........................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
djLint formatting for Django.............................................Passed
djLint linting for Django................................................Passed

## What should've happened instead?

All pre-commit hooks should of Passed.

trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check json...............................................................Passed
check toml...............................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
debug statements (python)................................................Passed
check builtin type constructor use.......................................Passed
check for case conflicts.................................................Passed
check docstring is first.................................................Passed
detect private key.......................................................Passed
django-upgrade...........................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
djLint formatting for Django.............................................Passed
djLint linting for Django................................................Passed

## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): 2.5.0
  - OS name and version: 

    ```bash
    # Insert here the OS name and version
    MacOs Ventura 13.5

    ```

  - Python version, run `python3 -V`: 3.11.4
  - Docker version (if using Docker), run `docker --version`: 24.0.6
  - docker compose version (if using Docker), run `docker compose --version`: v2.23.0-desktop.1

# Original File: was generated by cookiecutter was not altered in any way.
devcontainer.json: pre-commit is failing for this file- not able to parse '//' commented out lines.

```json
// For format details, see https://containers.dev/implementors/json_reference/
{
    "name": "django_app_dev",
    "dockerComposeFile": [
        "../local.yml"
    ],
    "init": true,
    "mounts": [
        {
            "source": "./.devcontainer/bash_history",
            "target": "/home/dev-user/.bash_history",
            "type": "bind"
        },
        {
            "source": "/tmp",
            "target": "/tmp",
            "type": "bind"
        },
        {
            "source": "~/.ssh",
            "target": "/home/dev-user/.ssh",
            "type": "bind"
        }
    ],
    // Tells devcontainer.json supporting services / tools whether they should run
    // /bin/sh -c "while sleep 1000; do :; done" when starting the container instead of the container’s default command
    "overrideCommand": false,
    "service": "django",
    // "remoteEnv": {"PATH": "/home/dev-user/.local/bin:${containerEnv:PATH}"},
    "remoteUser": "dev-user",
    "workspaceFolder": "/app",
    // Set *default* container specific settings.json values on container create.
    "customizations": {
    },
    // Uncomment the next line if you want start specific services in your Docker Compose config.
    // "runServices": [],
    // Uncomment the next line if you want to keep your containers running after VS Code shuts down.
    // "shutdownAction": "none",
    // Uncomment the next line to run commands after the container is created.
    "postCreateCommand": "cat .devcontainer/bashrc.override.sh >> ~/.bashrc"
}

```

<summary>
Summary:
<pre>

### Followed documentation:
https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html

### Project created using:
% cookiecutter gh:cookiecutter/cookiecutter-django
Migrations successfully applied and run server successful.

### The ONLY PROBLEM is I can't commit to Git Repo because: <br>
check-json hook is failing for devcontainer.json file.
</pre>
</summary>

**Comment by HilbertSpecs** [comment]
I did not want to simply just delete the '//' commented out lines in the file in case they were needed later.

Goal: To get the pre-commit hooks to all pass and to preserve the original contents of the file.

I was able to get the pre-commit hooks to all pass by adding the following dictionary key-value structures for each '//' commented out line.

 "_commenti": "// ......",

The final file that worked is:

```json
{
    "_comment0": "Added _comments for all // commented out lines used forward slash (fs) preceding nested commas remove fs as needed",
    "_comment1": "// For format details, see https://containers.dev/implementors/json_reference/",
    "name": "django_app_dev",
    "dockerComposeFile": [
        "../local.yml"
    ],
    "init": true,
    "mounts": [
        {
            "source": "./.devcontainer/bash_history",
            "target": "/home/dev-user/.bash_history",
            "type": "bind"
        },
        {
            "source": "/tmp",
            "target": "/tmp",
            "type": "bind"
        },
        {
            "source": "~/.ssh",
            "target": "/home/dev-user/.ssh",
            "type": "bind"
        }
    ],
    "_comment2": "// Tells devcontainer.json supporting services / tools whether they should run",
    "_comment3": "// /bin/sh -c \"while sleep 1000; do :; done\" when starting the container instead of the container’s default command",
    "overrideCommand": false,
    "service": "django",
    "_comment4": "// \"remoteEnv\": {\"PATH\": \"/home/dev-user/.local/bin:${containerEnv:PATH}\"},",
    "remoteUser": "dev-user",
    "workspaceFolder": "/app",
    "_comment5": "// Set *default* container specific settings.json values on container create.",
    "customizations": {
    },
    "_comment6": "// Uncomment the next line if you want start specific services in your Docker Compose config.",
    "_comment7": "// \"runServices\": [],",
    "_comment8": "// Uncomment the next line if you want to keep your containers running after VS Code shuts down.",
    "_comment9": "// \"shutdownAction\": \"none\",",
    "_comment10": "// Uncomment the next line to run commands after the container is created.",
    "postCreateCommand": "cat .devcontainer/bashrc.override.sh >> ~/.bashrc"
}
```
<br>
<br>
I'm not sure what the standard is but seems like might be a better way if anyone has any pointers?

**Comment by foarsitter** [comment]
JSON does not support comments, use your git history to revert and comment changes.

**Comment by HilbertSpecs** [comment]
> JSON does not support comments, use your git history to revert and comment changes.

I’m not sure what you mean your response does not offer any explanation or concise meaning. I know json does not support comments BUT they are In the auto generated files that cookie cutter produces.

1. Why have them in an auto generated format that is not allowed to pass all pre-commit hooks? 
2. What do people normally do when starting a cookie cutter project with the comments in this devcontainer.json file to get the check-json pre-commit hook to pass?

**Comment by mpsantos** [comment]
I usually exclude the devcontainer.json from the pre-commit

**Comment by browniebroke** [comment]
> I usually exclude the devcontainer.json from the pre-commit

Is this file JSON5 format? If so, JSON5 supports comments, yes, probably best to exclude it from the pre-commit config. Anyone fancy sending a PR?

**Comment by mpsantos** [comment]
Done: https://github.com/cookiecutter/cookiecutter-django/pull/4702

**Comment by browniebroke** [comment]
Thanks
