### ISSUE TITLE
Sentry is not creating issues

### ISSUE THREAD

**Issue by rene-schwabe** [cookiecutter/cookiecutter-django#4731]
I used the cookie cutter tempalte with sentry-logging.

Just set the SENTRY_DSN to my URL:
![Screenshot 2023-12-11 at 14 29 18](https://github.com/cookiecutter/cookiecutter-django/assets/49638517/bb226f9c-bb28-456f-a6ce-dc4367b62b50)

Sentry is not opening issues even when I´m creating a VIEW with an error500 (division to 0 for example)

How do I debug the sentry-integration to find the issue?

**Comment by foarsitter** [comment]
Sentry only works in production. When modifying env vars in docker you need te restart the container.

**Comment by rene-schwabe** [comment]
> Sentry only works in production. When modifying env vars in docker you need te restart the container.

The Docker-Container is already running in production. The containers has been restarted several times.

**Comment by foarsitter** [comment]
Providing more info will help finding the issue. Did you 
enter the container and `echo $SENTRY_DSN` to verify the correct url? Another option is to set https://docs.sentry.io/platforms/python/configuration/options/#debug. Try using the `capture_exception()` method directly may give you some intel.

**Comment by rene-schwabe** [comment]
Thanks for your help. The .env-File wasn´t read correctly.
