### ISSUE TITLE
Github Actions Pre Commit Failed

### ISSUE THREAD

**Issue by animemoeus** [cookiecutter/cookiecutter-django#4732]
## What happened?
I created a project and uploaded it to Github, but the linter CI failed.
- https://github.com/animemoeus/glowing-fortnight/actions/runs/7168696147/job/19517440043

## What should've happened instead?
This is a freshly created project, so it should have no errors.

## Additional details

- Host system configuration:

```bash
Cookiecutter 2.4.0 from /home/arter/.local/lib/python3.10/site-packages (Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
```

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by browniebroke** [comment]
Yes, these can happen (see #4332). The template only ensure that pre-commits which aren't autofixable are passing (e.g. flake8). 

Reason being that templated cookicutter files are extremely difficult to make compatible with all formatting, but it's trivial to fix after generation: just run pre-commit and it should format all your files.
