### ISSUE TITLE
Prettier Pre-Commit always return failed

### ISSUE THREAD

**Issue by riso-tech** [cookiecutter/cookiecutter-django#4752]
## What happened?
<img width="676" alt="image" src="https://github.com/cookiecutter/cookiecutter-django/assets/80811037/bf335420-c587-45ca-9f83-0c7fa3d82790">

I think https://github.com/pre-commit/mirrors-prettier is not stable we should rollback to latest version

**Comment by browniebroke** [comment]
What's the error?

**Comment by riso-tech** [comment]
there is no error message to trace, I try v4.0.0-alpha.4 still working fine

**Comment by jkaeske** [comment]
The pre-commit version of prettier is now `v4.0.0-alpha.8`.
I just ran it without any problems.
Maybe that new version solved it already @riso-tech?
