### ISSUE TITLE
Add a citation file

### ISSUE THREAD

**Issue by cmatKhan** [cookiecutter/cookiecutter-django#4755]
Hi all -- I am using this in academic software. I would like the cite the repository, which I can of course do, but I would also like to credit authors and maintainers more explicitly.

I suggest that it would be a good idea to create a citation file, and possibly add a zenodo config, to make it easier to appropriately cite/credit this excellent work in grants and papers.

**Comment by pydanny** [comment]
We do provide a contributors.md file at https://github.com/cookiecutter/cookiecutter-django/blob/master/CONTRIBUTORS.md.

Any reason why that doesn't suffice?

**Comment by browniebroke** [comment]
The contributors.md is generated from a JSON file: https://github.com/cookiecutter/cookiecutter-django/blob/master/.github/contributors.json so that's the source of truth at the moment.

**Comment by foarsitter** [comment]
Just put the url of this repo in a footnote, that should be enough in my opinion. This is not an academic piece of work so should not be used in someones bibliography.I know it looks very dignified and I too spent a lot of time creating scientific references to a lot of stuff that isn't scientific but in the end it isn't worth your time.

**Comment by cmatKhan** [comment]
^^ point taken. The motivation is just gratitude -- I wouldn't use django if it wasn't for this cookiecutter. But, you're right -- just the repo link is likely best
