### ISSUE TITLE
Line length of 88 chars

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#4792]
It seems like django lowered its max line length a while ago to 88: https://github.com/django/django/commit/ba94488196a74e312177ef2621fbd427956836ef

Should we follow?

**Comment by browniebroke** [comment]
I'm neutral on this, but happy to change if folks what to. What are the pros and cons of changing? Here are the ones I see:

- Pros: remove one setting from black and use the default.
- Cons: migration effort, as our files aren't valid Python code, we can't "just run" black.

**Comment by foarsitter** [comment]
I think the django people have put enough debate in it so I trust them blindly. 

Is it an option to change the setting and not put any effort in the migration? Pre-commit will pick it up on the first commit like the other linting inconveniences.

**Comment by browniebroke** [comment]
> Is it an option to change the setting and not put any effort in the migration? Pre-commit will pick it up on the first commit like the other linting inconveniences.

That's true, [I did mention in the past](https://github.com/cookiecutter/cookiecutter-django/issues/4732#issuecomment-1850247353) that the linting rules that are auto-fixed by pre-commit aren't expected to pass on first run, so that's definitely an option.
