### ISSUE TITLE
Integrate React as the frontend using a hybrid approach.

### ISSUE THREAD

**Issue by jinto-ag** [cookiecutter/cookiecutter-django#4802]
# Description

Provide users with the option to choose React as the frontend framework when generating the project. Adopt a hybrid approach, utilizing ViteJS for scaffolding the frontend part. Additionally, incorporate a utility function to generate types for the models, facilitating their use in the frontend.

# Rationale

This feature will offer flexibility to developers during project generation. By allowing them to opt for React as the frontend, it enhances customization possibilities. The hybrid approach ensures efficient scaffolding with ViteJS, promoting a smoother development experience. The inclusion of a utility function addresses the need for generating types, providing better integration between the Django backend and the React frontend.

**Comment by browniebroke** [comment]
While adding React has been requested a few times, we have no intention to add React support: we don't really have the bandwidth, nor the expertise to do so in the team. 

While React is popular, the front-end ecosystem is vast, and there are a number of competing framework we could go for: Vue, Svelte, Astro, etc... If we add React, the other will follow soon after, and supporting all these combinations simply isn't sustainable for us. Even just in React-land, there are a couple of meta-framework (e.g. Next.js) and [the React docs actually recommends using one of these](https://react.dev/learn/start-a-new-react-project).

So it's a -1 for me, definitely not keen on this.

**Comment by shivaam** [comment]
I have added react and vitjes for own project. I can either send a pr for the template or maybe we can link the git repo for examples. I am still developing it at the moment.
