### ISSUE TITLE
Allauth template elements

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#4819]
Looking into #4691 I stumbled upon the [elements](https://github.com/pennersr/django-allauth/tree/main/allauth/templates/allauth/elements) directory.  

Since 0.58.0 (2023-10-26) it is possible to override just the elements instead of overriding the templates completely: https://docs.allauth.org/en/latest/common/templates.html#styling-the-existing-templates

This feature lowers our effort to keep up-to-date with `allauth` but I'm not sure if we can achieve the same quality.

**Comment by rage236** [comment]
I would love to have a look at solving this issue, however as I am still new, I am a little confused on what a fix would look like, and some extra guidance would be greatly appreciated

**Comment by foarsitter** [comment]
Submit a PR and I will have a look at it. I have some time on Monday en Tuesday next week.

**Comment by rage236** [comment]
I need more clarification on the issue before I can start. I have created a local branch, but I am not sure where to go from here

**Comment by foarsitter** [comment]
The template/account folder contains an implementation of the allauth templates. These templates can be removed in favor of the elements that allauth provides: https://github.com/pennersr/django-allauth/tree/main/allauth/templates/allauth/elements 

Thats it. if you are familiair with how django templates work it is a game of trail and error te find out which elements need customization and which base templates need to be overridden. If this still sounds like gibberish to you then I advice to learn the django fundaments first before contributing.
