### ISSUE TITLE
You probably don't need `get_user_model`

### ISSUE THREAD

**Issue by mfosterw** [cookiecutter/cookiecutter-django#4872]
## Description

Import `User` directly, rather than using `get_user_model`.

## Rationale

`get_user_model` is meant for *reusable* apps, while it is my understanding this project is targeted more towards creating websites than packages. Especially within the `users` app it doesn't make any sense to use it (are we expecting users to create a new user model in a custom app but then keep the `users` app in their project?) , and switching can prevent new users from assuming they have to use it in all their custom apps (which may or may not be what happened to me). For a more in-depth explanation of why it's an anti-pattern, read this [blog post](https://adamj.eu/tech/2022/03/27/you-probably-dont-need-djangos-get-user-model/).

**Comment by browniebroke** [comment]
Thank you for bringing this to our attention, the blog post is super clear and makes a great case. I noticed a few times that the function didn't play nice with type checker, that makes sense now.

Do you want to send us a pull request?
