### ISSUE TITLE
CI should test against production environment, not local

### ISSUE THREAD

**Issue by acyment** [cookiecutter/cookiecutter-django#4878]
## What happened?
CI scripts (I only checked Github and Gitlab) run tests against local.yml

## What should've happened instead?
I believe it makes more sense for CI to run tests against production.yml

**Comment by browniebroke** [comment]
The image from `production.yml` doesn't include development and test dependencies (e.g. pytest), so how do you suggest we run tests without them? 

We do that intentionally to keep the production image small
