### ISSUE TITLE
Incorrect Python version in Docker.

### ISSUE THREAD

**Issue by NikolayCherniy** [cookiecutter/cookiecutter-django#4903]
## What happened?
Aliases for Docker image builds aren't functioning as intended. Currently, Python version 3.11 is specified, but the image is built from 3.12 because aliases aren't used in stages 2 and 3, and the reference to Python is made without specifying the version. As a result, besides having the incorrect Python version, each image also occupies about ~1.5 gigabytes instead of ~800 megabytes.

## What should've happened instead?
The image should be built based on the base image with the specified version.

**Comment by browniebroke** [comment]
Good catch, I believe it has been introduced in #4804, where the aliases were changed to `docker.io/...`
