### ISSUE TITLE
Africacryptochainx 

### ISSUE THREAD

**Issue by Patrickoto91** [cookiecutter/cookiecutter-django#4917]
## What happened?
I attempted to utilize Hummingbot to facilitate peer-to-peer (P2P) transactions in the cryptocurrency space.

## What should've happened instead?
I expected to successfully configure Hummingbot to enable seamless P2P transactions, leveraging my experience in the cryptocurrency domain.

## Additional details

- Host system configuration:

  - Version of Hummingbot CLI (get it with `hummingbot --version`): [Please insert version here]
  - OS name and version: 

    - On Linux, run
    ```bash
    lsb_release -a 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
    ```
    - On MacOS, run
    ```bash
    sw_vers
    ```
    - On Windows, via CMD, run
    ```
    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    ```
    ```
    # Insert here the OS name and version
    ```
  - Python version, run `python3 -V`: [Please insert Python version here]
  - Docker version (if using Docker), run `docker --version`: [Please insert Docker version here]
  - Docker Compose version (if using Docker), run `docker-compose --version`: [Please insert Docker Compose version here]

- Options selected and/or replay file:

```json
// Please provide any options selected or replay file used
```

<summary>
Logs:
<details>
<pre>
# Please insert any relevant logs here
</pre>
</details>
</summary>

**Comment by foarsitter** [comment]
@Patrickoto91 wrong repo perhaps?
