### ISSUE TITLE
Integrate PostgreSQL 16 Support in Django Cookiecutter

### ISSUE THREAD

**Issue by bvedad** [cookiecutter/cookiecutter-django#4920]
## Description

I propose to add PostgreSQL 16 as a selectable option for the database setup within the Django Cookiecutter project template. This update would necessitate adjustments to Docker configuration files, database connectivity settings, and potentially updating version-specific dependencies to ensure compatibility. Incorporating PostgreSQL 16 will enable users to leverage the latest improvements in database functionality, performance enhancements, and security features offered by the most recent version of PostgreSQL.

## Rationale

The integration of PostgreSQL 16 into the Django Cookiecutter template is essential to keep the template up-to-date with current database technologies, providing users with the best possible tools for their projects. This addition will cater to developers looking to use the latest database features and optimizations in their new projects, enhancing the template's appeal and utility. Furthermore, staying current with database versions can improve application security and performance, aligning with best practices in software development and deployment.

**Comment by browniebroke** [comment]
Sounds good, assuming the version of Django and psycopg we use support it (I didn't check). 

Want to send us a pull request? You can probably find the one for Postgres 15 as an example.
