### ISSUE TITLE
Adopt Collectfasta

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#4938]
[Collectfast](https://github.com/antonagestam/collectfast) is archived, long live [Collectfasta](https://github.com/jasongi/collectfasta). 

The django newletter contained a link to the succssor of collectfast: https://jasongi.com/2024/03/04/speed-up-djangos-collectstatic-command-with-collectfasta/ 

Should be easy to adopt I think.

**Comment by browniebroke** [comment]
We already have https://github.com/cookiecutter/cookiecutter-django/issues/4523

**Comment by foarsitter** [comment]
Closing as duplicate of https://github.com/cookiecutter/cookiecutter-django/issues/4523
