### ISSUE TITLE
ValueError: Another profiling tool is already active

### ISSUE THREAD

**Issue by eracle** [cookiecutter/cookiecutter-django#5043]
## What happened?
By upgrading to python 3.12 we inherited a bug from django-debug-toolbar
Here's the issue:
https://github.com/jazzband/django-debug-toolbar/issues/1875

**Comment by eracle** [comment]
I fixed with 
exec python manage.py runserver_plus 0.0.0.0:8000 --nothreading

can't provide a PR atm, github seems kind of down

**Comment by browniebroke** [comment]
See https://github.com/cookiecutter/cookiecutter-django/issues/4644#issuecomment-2082235125 for a potential solution, PR welcome

**Comment by browniebroke** [comment]
What do you think of this? https://github.com/cookiecutter/cookiecutter-django/pull/5069
