### ISSUE TITLE
Migrate gulpfile to ESM

### ISSUE THREAD

**Issue by browniebroke** [cookiecutter/cookiecutter-django#5072]
## Description

There are a few dependabot PRs for Gulp packages which are opened and seem to need to migrate our `gulpfile.js` file to ESM:

- https://github.com/cookiecutter/cookiecutter-django/pull/4949
- https://github.com/cookiecutter/cookiecutter-django/pull/5052

Some more reading on this:

- Guide with high level steps to follow: https://gist.github.com/noraj/007a943dc781dc8dd3198a29205bae04
- Link from gulp-imagemin: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- Commonjs to ESM codemod: https://github.com/azu/commonjs-to-es-module-codemod might be helpful, although I presume it would need to run on the generated file (without Jinja tags)

Doesn't seem very difficult, but not exactly trivial either. 

## Rationale

Keep up to date with the JS ecosystem.

**Comment by GOUTHAM-2002** [comment]
Can i work on this ?

**Comment by browniebroke** [comment]
Yes sure. No need to ask for permissions 😄

**Comment by foarsitter** [comment]
Gulp seems also to be breaking with node v22 https://github.com/cookiecutter/cookiecutter-django/pull/5039

**Comment by browniebroke** [comment]
Fixed in https://github.com/cookiecutter/cookiecutter-django/pull/4949
