### ISSUE TITLE
Gitlab docker tag is remove

### ISSUE THREAD

**Issue by foarsitter** [cookiecutter/cookiecutter-django#5148]
It looks like the docker tag is remove from the runner. 

![image](https://github.com/cookiecutter/cookiecutter-django/assets/3885256/7e10305c-f42c-407e-ba0e-f8a66076a38b)

https://docs.gitlab.com/ee/update/deprecations.html#removal-of-tags-from-small-saas-runners-on-linux

**Comment by browniebroke** [comment]
Looks like we could remove the `docker` and `python` tags from gitlab CI config? https://about.gitlab.com/blog/2023/08/15/removing-tags-from-small-saas-runner-on-linux/#how-to-avoid-jobs-getting-stuck

Does someone know the difference between changing them to `saas-linux-small-amd64` vs removing them? Not clear to me...

**Comment by foarsitter** [comment]
Removing them solved the issue for me but couldn't find the answer on your question either.

**Comment by browniebroke** [comment]
Ok, so remove and see how it goes? If someone reports any issues, we can look at that...
