### ISSUE TITLE
Preparing metadata (pyproject.toml) ... error: [Errno 2] No such file or directory: 'pg_config'

### ISSUE THREAD

**Issue by Rhiz3K** [cookiecutter/cookiecutter-django#5165]
## What happened?
$ pip install -r requirements/local.txt
...
 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
error: [Errno 2] No such file or directory: 'pg_config'
...
## What should've happened instead?
"sudo apt-get install libpq-dev" should've been included
https://stackoverflow.com/questions/11618898/pg-config-executable-not-found
## Additional details

- Host system configuration:
  - Version of cookiecutter CLI (get it with `cookiecutter --version`):
  -   -   Cookiecutter 2.6.0 from /home/coder/apartman27/.venv/lib/python3.11/site-packages (Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0])
  - OS name and version:
  -   - Distributor ID: Debian
  -   - Description:    Debian GNU/Linux 12 (bookworm)
  -   - Release:        12
  -   - Codename:       bookworm
  - Python version, run `python3 -V`:
  -   - Python 3.11.2  - 

- Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and macOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)

```json
{
  "cookiecutter": {
    ...
    "username_type": "username",
    "timezone": "Europe/Prague",
    "windows": "n",
    "editor": "VS Code",
    "use_docker": "y",
    "postgresql_version": "16",
    "cloud_provider": "None",
    "mail_service": "Other SMTP",
    "use_async": "y",
    "use_drf": "n",
    "frontend_pipeline": "None",
    "use_celery": "n",
    "use_mailpit": "y",
    "use_sentry": "n",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "y",
    "_template": "https://github.com/cookiecutter/cookiecutter-django",
    ...
    "_repo_dir": "/home/coder/.cookiecutters/cookiecutter-django",
    "_checkout": null
  }
```

<summary>
Logs:
<details>
<pre>
$ pip install -r requirements/local.txt
...
 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-bm6tw1x6/psycopg_c.egg-info
      writing /tmp/pip-modern-metadata-bm6tw1x6/psycopg_c.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-bm6tw1x6/psycopg_c.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-bm6tw1x6/psycopg_c.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-bm6tw1x6/psycopg_c.egg-info/SOURCES.txt'
      couldn't run 'pg_config' --includedir: [Errno 2] No such file or directory: 'pg_config'
      error: [Errno 2] No such file or directory: 'pg_config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
</pre>
</details>
</summary>

**Comment by luzfcb** [comment]
@Rhiz3K the non-python dependencies are available/documented in the `utility` directory 
https://github.com/cookiecutter/cookiecutter-django/tree/315724b797d0150cf0e869fce3963d74fd167545/%7B%7Bcookiecutter.project_slug%7D%7D/utility


```bash

cd utility
sudo ./install_os_dependencies.sh install
```

Please, run it, and if it solves the problem, reopen this issue.
