### ISSUE TITLE
AttributeError: This FileResponse instance has no `content` attribute. Use `streaming_content` instead.

### ISSUE THREAD

**Issue by ShubhamKarala** [cookiecutter/cookiecutter-django#5196]
## What happened?
```AttributeError: This FileResponse instance has no `content` attribute. Use `streaming_content` instead.```

I am getting this error while clicking on any media download link in django admin. I checked inside docker container and files are stored properly. I have used cookiecutter to start the project.

When i
## What should've happened instead?

File should be downloaded.

## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): Cookiecutter 1.7.3 from C:\Python310\lib\site-packages (Python 3.1)
  - OS name and version:

    On Linux, run

    ```bash
    lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
    ```

    On MacOs, run

    ```bash
    sw_vers
    ```

    On Windows, via CMD, run

    ```
    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    ```

    ```bash
    # OS Name:                   Microsoft Windows 10 Home Single Language
    # OS Version:                10.0.19045 N/A Build 19045

    ```

  - Python version, run `python3 -V`: Python 3.12.3
  - Docker version (if using Docker), run `docker --version`: Docker version 26.1.4, build 5650f9b
  - docker compose version (if using Docker), run `docker compose --version`: Docker Compose version v2.27.1-desktop.1
  - ...

- Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and macOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)

```json

```

<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by browniebroke** [comment]
Weird I never seen this problem

**Comment by surfgreendev** [comment]
Having the same issue. Any updates?

**Comment by browniebroke** [comment]
Would be helpful if one of you could share the options they used to generate their project, as there is very little to go by right now. Help us help you 😄

**Comment by surfgreendev** [comment]
Hi there,

the Django Debug Toolbar is responsible for the Attribute Error, deactivating all options, than reactivating solved the issue. Sorry for the inconvenience.
