### ISSUE TITLE
Error running awscli upload

### ISSUE THREAD

**Issue by hleroy** [cookiecutter/cookiecutter-django#5217]
## What happened?

Running  `awscli upload` fails with the following error : "aws: error: argument command: Invalid choice, valid choices are:" (followed by a long list of options).

## What should've happened instead?

Upload successful on S3.

## Additional details

With the exact same setup it works with previous awscli docker image.

e.g.: 
"FROM docker.io/amazon/aws-cli:2.15.58" ==> failure
"FROM "docker.io/garland/aws-cli-docker:1.16.140" ==> success

**Comment by browniebroke** [comment]
The upload script ([as documented here](https://cookiecutter-django.readthedocs.io/en/latest/docker-postgres-backups.html#backup-to-amazon-s3)) is located here: https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/aws/maintenance/upload

I'm going to assume that it fails at line 23, altough it would have been helpful to get the actual output to confirm it.

**Comment by hleroy** [comment]
I took more time to understand the error. The upload script is not executed. The Amazon aw-cli image differs from garland image. It has an `ENTRYPOINT ["/usr/local/bin/aws"]`. The ENTRYPOINT takes precedence over CMD and is always run. So the effective command that is executed is: `/usr/local/bin/aws upload`. Upload is not a valid choice of argument for the `aws` command.

We need to clear the ENTRYPOINT in the derived image in order to execute the `upload` or `download` scripts passed as parameter. I will give it a try later today and report back.
