### ISSUE TITLE
[awscli service] - Django Container Fails to Run After Generating Project with Latest cookiecutter-django

### ISSUE THREAD

**Issue by alexkanavos** [cookiecutter/cookiecutter-django#5241]
I’m experiencing an issue with the latest version of cookiecutter-django. When I generate a new project using the most recent version of the template and deploy it to a VPS, the Django container fails to start. However, if I deploy a project generated using an older version of cookiecutter-django from about 6 months ago, it works as expected.

- Cookiecutter 2.4.0 from /home/alex/.local/lib/python3.12/site-packages (Python 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)])
  
- OS name and version (VPS):

- Distributor ID:	Ubuntu
  Description:	Ubuntu 22.04.4 LTS
  Release:	22.04
  Codename:	jammy

- Docker version 27.0.3
- Docker Compose version v2.3.3

- Options selected:

{
  "cookiecutter": {
    "project_name": "testproject",
    "project_slug": "testproject",
    "description": "Behold My Awesome Project!",
    "author_name": "alex",
    "domain_name": "example.com",
    "email": "alex@example.com",
    "version": "0.1.0",
    "open_source_license": "Not open source",
    "username_type": "email",
    "timezone": "Europe/Rome",
    "windows": "n",
    "editor": "None",
    "use_docker": "y",
    "postgresql_version": "16",
    "cloud_provider": "AWS",
    "mail_service": "Mailgun",
    "use_async": "n",
    "use_drf": "n",
    "frontend_pipeline": "None",
    "use_celery": "y",
    "use_mailpit": "y",
    "use_sentry": "y",
    "use_whitenoise": "y",
    "use_heroku": "n",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "y",
    "debug": "n",
    "_template": "https://github.com/cookiecutter/cookiecutter-django",
    "_output_dir": "/home/alex/Projects",
    "_repo_dir": "/home/alex/.cookiecutters/cookiecutter-django",
    "_checkout": null
  },

```
$ docker compose -f docker-compose.production.yml down
$ docker compose -f docker-compose.production.yml build
$ docker compose -f docker-compose.production.yml run --rm django python manage.py migrate
$ docker compose -f docker-compose.production.yml up

```

```
warN[0000] mount of type `volume` should not define `bind` option
 ⠋ Container testproject-awscli-1        Creating                                      0.0s 
 ✔ Container testproject-redis-1         Running                                       0.0s 
 ✔ Container testproject-postgres-1      Running                                       0.0s 
 ⠋ Container testproject-django-1        Creating                                      0.0s 
 ⠋ Container testproject-celerybeat-1    Creatin...                                    0.0s 
 ⠋ Container testproject-celeryworker-1  Creat...                                      0.0s 
 ⠋ Container testproject-flower-1        Creating                                      0.0s 
Error response from daemon: no command specified
```

**Comment by alexkanavos** [comment]
I did run it with `-d` flag but the result was the same. The only 2 containers that are running are the ones you seen above, that is redis and postgres. They seem to start for a moment and then just fail. The other two remain active.

**Comment by foarsitter** [comment]
So all the python containers are failing and the only error you are seeing is `Error response from daemon: no command specified`? 

What is listed in your `docker-compose.production.yml` file under the command section for the failing containers? 

Is there a `COMMAND` or `ENTRYPOINT` instruction in the Dockerfiles you are using?

**Comment by foarsitter** [comment]
- When building, you are in the correct directory?
- The `/compose/production/django/celery/*/start` files are there? 
- Are the .production environment variables present?

**Comment by alexkanavos** [comment]
Yes to all three.

**Comment by luzfcb** [comment]
@alexkanavos I faced the same problem last week. The solution was to update docker and compose docker plugin to the latest version and make sure there is no docker compose plugin cache installed in your user home.

```bash
# Note that this path is on Linux, I'm not sure if the the same on MacOS
rm -rf "${HOME}/.docker/cli-plugins/docker-compose"
```

My versions after removing the plugin on my HOME and updating all from the official deb repository

```bash
$ docker --version
Docker version 27.1.0, build 6312585

$ docker compose version
Docker Compose version v2.29.0
```

**Comment by alexkanavos** [comment]
Hey @luzfcb Thanks for your answer. I just tested it, but unfortunately it's not working. Still same error. Do you run your containers on a VPS as well?

**Comment by luzfcb** [comment]
from:

```
warN[0000] mount of type `volume` should not define `bind` option
 ⠋ Container testproject-awscli-1        Creating                                      0.0s 
 ✔ Container testproject-redis-1         Running                                       0.0s 
 ✔ Container testproject-postgres-1      Running                                       0.0s 
 ⠋ Container testproject-django-1        Creating                                      0.0s 
 ⠋ Container testproject-celerybeat-1    Creatin...                                    0.0s 
 ⠋ Container testproject-celeryworker-1  Creat...                                      0.0s 
 ⠋ Container testproject-flower-1        Creating                                      0.0s 
Error response from daemon: no command specified
```
The `Error response from daemon: no command specified` error message is displayed because there is no `command` on `awscli` service on `docker-compose.production.yml`, which is required. 

It looks like it's an unexpected side effect from #5221


Try to change the awscli service and add something like:

```yml
    command: /bin/bash
    restart: "no"
```

sample:

```yml
  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    command: /bin/bash
    restart: "no"
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

```

**Comment by alexkanavos** [comment]
Aaand we are live!! You are really the best @luzfcb ! They should probably add the new lines by default in the next version. Maybe create a PR.

In any case thank you very much for all your help and guidance. I'm kinda new to Docker ecosystem, so my apologies if that caused any confusion. 

![Screenshot from 2024-07-22 18-14-51](https://github.com/user-attachments/assets/4b225750-ceab-4b91-b266-0310ca0145ef)

**Comment by browniebroke** [comment]
cc @hleroy

**Comment by foarsitter** [comment]
@luzfcb nice one, good work!

**Comment by hleroy** [comment]
> cc @hleroy

Just created a pull request to restore a CMD command ( ["/bin/bash"]) in the derived aws-cli container. It seems clearing the ENTRYPOINT also has the side effect of clearing the CMD command from the original container. Sorry for introducing this issue 😔
