### ISSUE TITLE
Any authenticated user can view other user's profiles

### ISSUE THREAD

**Issue by Fuzzwah** [cookiecutter/cookiecutter-django#5253]
## What happened?

Any authenticated user can view other user's profiles

## What should've happened instead?

Users should only be able to view their own profile

## Additional details

https://github.com/cookiecutter/cookiecutter-django/blob/207a9e576c5cef9e1c757279d67bb0a752fcdf6e/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/views.py#L12

**Comment by browniebroke** [comment]
See https://github.com/cookiecutter/cookiecutter-django/issues/1752
