### ISSUE TITLE
Starting new project as Postgresql

### ISSUE THREAD

**Issue by lvalics** [cookiecutter/cookiecutter-django#5301]
I have created the new project and tried to run mypy inside django container. I got error with database (set up as Postgresql) and CELERY_URL

File "/app/config/settings/base.py", line 48, in <module>
    DATABASES = {"default": env.db("DATABASE_URL")}

 File "/app/config/settings/base.py", line 281, in <module>
    CELERY_BROKER_URL = env("CELERY_BROKER_URL")

I have fixed to add to base.py 

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    },
}

and to .envs/.local/.django 

CELERY_BROKER_URL=redis://redis:6379/0

This fixed. Dunno if this is a bug or I missconfigured something.

**Comment by browniebroke** [comment]
Can you please paste the command you ran and the whole stack trace, as it's hard to help you without it.

**Comment by lvalics** [comment]
For this one I runned this mypy comic_life_online  ...

**Comment by browniebroke** [comment]
Ok, and what did you do before running mypy? There are several ways of accessing a container...

**Comment by lvalics** [comment]
git init
pre-commit install
git add .
git commit -m "first awesome commit"
git remote add origin [git@github.com:lvalics/comic_life_online](mailto:git@github.com)
git push -u origin master

docker compose -f docker-compose.local.yml build
docker compose -f docker-compose.local.yml up -d

inside the docker

mypy comic_life_online

**Comment by browniebroke** [comment]
And how did you do "inside the docker"? `docker run` or `docker exec`?

**Comment by browniebroke** [comment]
I think it's the same issue as https://github.com/cookiecutter/cookiecutter-django/issues/3224

This is a known limitation: https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html#execute-management-commands
