### ISSUE TITLE
Autocompletion Issues in PyCharm with Django-Cookiecutter Projects

### ISSUE THREAD

**Issue by 0luv69** [cookiecutter/cookiecutter-django#5390]
PyCharm Autocompletion Issues with Django-Cookiecutter
Description
After migrating a large-scale project to the Django-Cookiecutter framework, we encountered significant issues with PyCharm, particularly with autocompletion in HTML templates. Template tags such as {% include ... %} and {% static ... %} were not recognized correctly, disrupting the development workflow.
We managed to partially fix the {% include ... %} tag issue by marking relevant directories as "Template Directories" within PyCharm. However, this approach did not resolve the autocompletion issues for {% static ... %} tags and other Django-specific template tags.
Investigation

Initially, we suspected that our project-specific settings were causing these issues. However, upon testing with a freshly generated Django-Cookiecutter project, we observed the same problem, suggesting that the issue lies within PyCharm's handling of Django projects created with Cookiecutter templates.
To identify the root cause, we systematically rebuilt the Cookiecutter setup step-by-step and monitored PyCharm's behavior. We discovered that a specific line in local.py was contributing to the issue:
pythonCopyINSTALLED_APPS = ["whitenoise.runserver_nostatic", *INSTALLED_APPS]
This line uses unpacking within the INSTALLED_APPS list, which appears to cause PyCharm to misinterpret the project's structure, resulting in a "no apps found" message and broken autocompletion.

Root Cause
PyCharm seems unable to handle Python's unpacking operation (*INSTALLED_APPS) within the context of INSTALLED_APPS. This causes PyCharm's Django integration to fail in recognizing the proper Django structure, leading to issues with autocompletion, especially in templates.
Solution
To resolve this issue, we modified the assignment of INSTALLED_APPS as follows:
pythonCopyINSTALLED_APPS.insert(0, "whitenoise.runserver_nostatic")
This modification allows PyCharm to correctly detect the project's structure, restoring autocompletion and functionality for all template tags.
Additional Suggestions

PyCharm Configuration Check: Ensure that your PyCharm settings are properly configured for Django. Sometimes, enabling Django support explicitly within PyCharm settings can help.
Refresh PyCharm Caches: After modifying the project setup, invalidating caches and restarting PyCharm can sometimes resolve lingering integration issues.
Test Across Versions: If the issue persists, test with different versions of PyCharm or report the bug to JetBrains as it might be related to specific IDE versions or configurations.
Use Consistent Template Tagging: Ensure that {% load static %} or other required template tag libraries are properly included at the top of your HTML files to aid PyCharm's autocompletion.

Testing Environment

PyCharm Professional Edition
Version: Build #PY-241.18034.82, built on June 24, 2024
Issue also observed in older versions of PyCharm

Attachments
Relevant screenshots or log files illustrating the issue.
Ways to Fix PyCharm Autocompletion Issues with Django-Cookiecutter

Modify INSTALLED_APPS Declaration:

Problem: PyCharm struggles with the unpacking syntax (*INSTALLED_APPS) in the INSTALLED_APPS setting, leading to issues in recognizing the Django structure.
Fix: Modify the declaration to avoid unpacking.
pythonCopy# Original problematic code:
INSTALLED_APPS = ["whitenoise.runserver_nostatic", *INSTALLED_APPS]

# Modified code:
INSTALLED_APPS.insert(0, "whitenoise.runserver_nostatic")

Outcome: This adjustment helps PyCharm correctly parse and recognize the apps, restoring autocompletion functionality.

Mark Template Directories in PyCharm:

Problem: PyCharm does not automatically recognize some directories as template sources, leading to missing autocompletion for template tags.
Fix:

Right-click on your template directories (e.g., templates folder) in the PyCharm Project Explorer.
Select Mark Directory as > Template Folder.

Outcome: This enables PyCharm to understand where templates are located, improving the recognition of {% include %}, {% block %}, and similar tags.

Invalidate Caches and Restart PyCharm:

Problem: Caches and outdated index files might interfere with PyCharm's ability to correctly parse and autocomplete Django project files.
Fix:

Go to File > Invalidate Caches / Restart in PyCharm.
Click Invalidate and Restart.

Outcome: This clears PyCharm's caches, often resolving issues with autocompletion by forcing PyCharm to re-index the project files.

Explicitly Enable Django Support in PyCharm:

Problem: Sometimes, PyCharm does not automatically detect that a project is using Django, which can disable Django-specific features like autocompletion.
Fix:

Navigate to Settings > Languages & Frameworks > Django.
Ensure that the Enable Django Support checkbox is ticked, and configure the correct settings (project root, settings file, etc.).

Outcome: This explicitly enables Django integration, helping PyCharm handle Django-related autocompletions better.

Ensure Template Tag Libraries are Loaded:

Problem: Missing {% load static %} or other required libraries at the top of templates can prevent proper tag recognition.
Fix: Always include the necessary {% load %} statements at the beginning of your templates, such as:
djangoCopy{% load static %}

Outcome: Ensures that PyCharm recognizes the correct context for {% static %} and other template tags, restoring autocompletion.

Upgrade PyCharm and Django Plugins:

Problem: Compatibility issues between PyCharm and Django-Cookiecutter could arise due to outdated versions.
Fix:

Update PyCharm to the latest stable version via Help > Check for Updates.
Update any relevant plugins, such as the Django plugin, from Settings > Plugins.

Outcome: Keeping PyCharm and its plugins up-to-date can often resolve unexpected bugs and improve integration.

Test on a Clean Django-Cookiecutter Project:

Problem: Specific project configurations could be affecting PyCharm integration.
Fix:

Create a new Django-Cookiecutter project and test PyCharm integration.
Compare settings between the new project and your existing one to identify any discrepancies.

Outcome: Identifying problematic settings in your project can help you make targeted adjustments to resolve integration issues.

**Comment by luzfcb** [comment]
Hello, thank you for reporting a possible issue, however you did not respect our issue template and did not provide the minimum information requested. Furthermore, all the text in your report seems to have been generated by some AI GPT tool. Additionally, issues with autocomplete in Pycharm are Pycharm's problem and we cannot do anything about them. You should report them directly to Jetbrains.

**Comment by foarsitter** [comment]
Duplicate of https://github.com/cookiecutter/cookiecutter-django/issues/5239
