### ISSUE TITLE
Missing OS requirements for `ubuntu-latest`

### ISSUE THREAD

**Issue by browniebroke** [cookiecutter/cookiecutter-django#5465]
## What happened?

The CI of the template is currently broken: https://github.com/cookiecutter/cookiecutter-django/actions/runs/11318953105/job/31474266324?pr=5463#step:8:22

We're missing OS requirements for `ubuntu-latest`, most likely because the GitHub runner OS was updated

## What should've happened instead?

CI should  pass.

## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): latest
  - OS name and version: `ubuntu-latest` TBC what version is actually used:

    On Linux, run

    ```bash
    lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
    ```

    ```bash
    # Insert here the OS name and version

    ```

  - Python version, run `python3 -V`: 3.12

**Comment by browniebroke** [comment]
The very first step of the job gives some details about the OS: https://github.com/cookiecutter/cookiecutter-django/actions/runs/11318953105/job/31474266324?pr=5463#step:1:8 which we can compare against the latest green run: https://github.com/cookiecutter/cookiecutter-django/actions/runs/11308996288/job/31452396112?pr=5461#step:1:8

It changed from `ubuntu-22.04` to `ubuntu-24.04`

**Comment by foarsitter** [comment]
Does Dependabot supports updating the `runs-on` labels?  If so, we should pin it to ubuntu-22.04. This will trigger Dependabot to create a pull request (PR) that will fail due to the missing apt file.
