### ISSUE TITLE
Integration of preflyt for better checks

### ISSUE THREAD

**Issue by burhan** [cookiecutter/cookiecutter-django#624]
It is great that we offer a lot of choice for components and I think we should make the template even more flexible (more on this soon); however the more components we offer, it creates a more complex decision tree of variable and configurations that have to be checked for a successful deployment. 

For example, it could be a way to deal with #602 

In order to test for and resolve this, I am proposing the integration of [`preflyt`](https://github.com/humangeo/preflyt). It is a way to script checks for certain values (for example, environment variables are set, database is actually accessible, etc.) before an application is launched.

This best makes sense for "local" deployments, as if you are deploying on Heroku then these configuration values are set by the respective addon in your environment.

I am not quite sure where best to integrate it; I don't think its wise to start messing with `manage.py`, but its not really a _test_ per-se as it doesn't check your code, but rather your environment so I am not sure it belongs in the normal test suite.

Any thoughts?

**Comment by luzfcb** [comment]
@burhan first problem: [preflyt](https://github.com/humangeo/preflyt) is Python3 [only](https://github.com/humangeo/preflyt/blob/master/setup.py#L29)

**Comment by pydanny** [comment]
@luzfcb @burhan see #1129!

**Comment by webyneter** [comment]
Unfortunately, it seems like [preflyt](https://github.com/humangeo/preflyt) hasn't been maintained for more than two years now,.

**Comment by browniebroke** [comment]
Closing as the project appears unmaintained now.
